intel/cve-bin-tool

cve_bin_tool/cli.py
test/test_scanner.py

* Scanner should not scan symlinks
Fixes: #8

scanner: Ignore symlinks

---

test/test_scanner.py

test: Remove errant double scan

---

cve_bin_tool/cli.py

extractor: Scan file then attempt extraction

---

cve_bin_tool/extractor.py
test/test_extract.py

extractor: Add apk support

---

test/binaries/test-png-1.4.11.c
test/binaries/test-png-1.6.36.c
test/test_scanner.py

I have added scanner tests for versions `1.6.36` and `1.4.11`

Add new scanner tests for Libpng 

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/systemd.py
test/binaries/test-systemd-239.c
test/test_scanner.py

Adds systemd checker
closes #32

Add systemd checker

---

test/test_cli.py
test/test_definitions.py
test/test_extract.py
test/test_nvd.py
test/test_scanner.py
test/test_util.py

Not done yet, but @pdxjohnny might want to check my docstrings in the nvd section before I finish.

Pylint fixes in test directory

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/sqlite.py
test/binaries/test-sqlite-3.12.2.c
test/test_scanner.py

Add Sqlite checker

---

cve_bin_tool/NVDAutoUpdate.py

Add cache location in warning message

---

cve_bin_tool/extractor.py

Added some error messages for other dependencies
Partial #38

error_messages

---

.travis.yml

My travis-fu is a bit weak but I think this will do the trick and get us one pylint job that's allowed to fail, as a precursor to making everything lint-free.

Add pylint to travis

---

test/test_cli.py
test/test_definitions.py
test/test_extract.py

Cache packages

---

cve_bin_tool/NVDAutoUpdate.py
test/test_nvd.py

nvd: Add ability to not update supplemental data

---

cve_bin_tool/checkers/curl.py
cve_bin_tool/checkers/expat.py
cve_bin_tool/checkers/libcurl.py
cve_bin_tool/checkers/libgcrypt.py
cve_bin_tool/checkers/libnss.py
cve_bin_tool/checkers/libtiff.py
cve_bin_tool/checkers/node.py
cve_bin_tool/checkers/openssl.py
cve_bin_tool/checkers/png.py
cve_bin_tool/checkers/systemd.py
cve_bin_tool/checkers/xerces.py
cve_bin_tool/checkers/zlib.py
cve_bin_tool/util.py

* Created regex_find function in util
* Removed similar functions from checkers. Checkers now
call regex_find.

checkers: Abstract regex into util

---

cve_bin_tool/cli.py

Use system strings/file if available (for performance)

---

test/test_scanner.py

#107 
Hi, sorry I have been busy dealing with my midterm and finally get rid of it. I will add more test cases in this week.

add sqlite rpm test

---

test/test_scanner.py

add xml2 rpm test. I have tested on my environment and it's good.

add xml2 rpm test

---

test/test_scanner.py

The goal here is to have at least one "real file" test for every checker.  This is currently a work in progress, shared as a PR so others can see the results.
Not all of these initial tests are working, I'll note them as I go so I can file bugs in the future.

Add rpm/deb/other package tests for every checker

---

.deepsource.toml

Hey @terriko!
I've added a customized `.deepsource.toml` as part of the PR that you can start using directly to run DeepSource analysis. As part of the anlaysis, tools like pylint, flake8 (style and code verification), bandit (security) and a bunch of custom anti-pattern analyzers run on every pull-request. DeepSource is free for open-source!
To continue running analysis on every PR, just follow these simple steps:
1. **Merge this PR.**
2. **Sign up on DeepSource** and grant access to this repository [here](https://deepsource.io/signup/).
3. **Activate analysis on this repo** [here](http://deepsource.io/gh/intel/cve-bin-tool).
Tip: You can also take a look at the [docs](https://deepsource.io/docs/guides/quickstart.html).
Please let me know if you have any questions! :)

Add code quality and security analysis with DeepSource

---

cve_bin_tool/NVDAutoUpdate.py
cve_bin_tool/cli.py
test/test_nvd.py

NVDAutoUpdate probably needs some refactoring to do this more elegantly instead of passing the flag all over, but this will at least work. (Fixes #142)

Make NVDAutoUpdate recognize the quiet flag (Fixes #142)

---

cve_bin_tool/checkers/xml2.py

This checker may need a refactoring, but I'm just adding to it for now to fix the immediate issue.

Add signature for fedora's xml2. fixes #133

---

README.md

Trying out gitter in case it's useful for casual communication

Add gitter to readme

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/icu.py
test/binaries/test-icu-3.8.1.c
test/test_scanner.py

icu checkers

---

.travis.yml
test/test_json.py

Adding a test to validate the latest json (with an eye to maybe noticing if something corrupts the json).  This might be better done in the nvd loader rather than as a separate test, but the performance hit is non-trivial, so I'm putting it in the test suite for diagnostic purposes instead.

Add json validation test

---

setup.py

This is used for the sha256sum check.

Add jsonschema to requirements

---

cve_bin_tool/NVDAutoUpdate.py
cve_bin_tool/checkers/systemd.py
cve_bin_tool/file.py
setup.py
test/test_json.py
test/test_scanner.py

Changes:
- Fix undefined names in `cve_bin_tool/NVDAutoUpdate.py` and `test/test_json.py`
- Remove unused imports in `cve_bin_tool/file.py`, `setup.py` and `test/test_scanner.py`
- Fix anomalous backslash in `cve_bin_tool/checkers/systemd.py`

Fix some bug risks and quality issues

---

cve_bin_tool/NVDAutoUpdate.py
test/test_json.py

This still fails a few unit tests because of data changes, but I think it's better to get something that 90% works than something that 0% works.

Initial fix for NVD's 1.1 json format

---

cve_bin_tool/cli.py

changed " ".join to "".join #261

string confusion solved

---

MANUAL.md
README.md
cve_bin_tool/cli.py

Closes https://github.com/intel/cve-bin-tool/issues/286

Reintroduce quiet mode

---

test/test_scanner.py

Closes https://github.com/intel/cve-bin-tool/issues/273

Add icu file test

---

cve_bin_tool/log.py

Closes https://github.com/intel/cve-bin-tool/issues/292

Set default log level

---

test/test_scanner.py

I have changed the URL in test_scanner.py

test_nss_rpm_3_26_2 needs replacement #295 solution

---

cve_bin_tool/cli.py
cve_bin_tool/cvedb.py

sync cache and database update

---

cve_bin_tool/checkers/icu.py
test/test_scanner.py

As noted in 305 -- there aren't a lot of version strings to be had here.  We might have some luck with trying to get 4.2 instead of 4.2.1, but I'll leave that experiment for someone else.

Improve icu checker. fixes #305

---

cve_bin_tool/checkers/README.md
test/test_cli.py
test/test_json.py

I've removed the meta checker, since it's now being done inline.  I can't decide if we want to do the jsonschema test inline (it's kind of slow) so I've updated the test suite test instead.

Clean up unused and broken tests.

---

test/test_cli.py

Add test for skips flag

---

test/test_cli.py

Test for update flag

---

cve_bin_tool/cli.py
test/test_cli.py

Support runs option

---

test/test_csv2cve.py

Fix deprecation warning in test_csv2cve

---

cve_bin_tool/checkers/systemd.py
test/test_scanner.py

* Sort lines in systemd to improve matching 
* fixes #171 
* add additional systemd tests with other packages from several distros
* add additional signatures to cover new packages

Systemd checker improvements

---

cve_bin_tool/cli.py

Last PR failed the black formatting test, fixed it.
Fixes #345

Added filename in UNKNOWN version warning

---

.gitignore
cve_bin_tool/cli.py
test/binaries/test-sqlite-3.30.1.c
test/test_scanner.py

I have added test-sqlite-3.30.1.c to generate fake binary.
I have also added unittest for the fake binary.

Added unittest for package: sqlite3 and version: 3.30.1

---

test/test_scanner.py

Add python 3.8.2 rpm test

---

cve_bin_tool/cli.py

* Grouped a few like arguments
* Specified relevant defaults
* Improved formatting in checker display

Improve help text

---

cve_bin_tool/checkers/icu.py
cve_bin_tool/cli.py

A rogue print() statement and a missing check before output_cves() was breaking quiet mode.

Make quiet mode actually quiet

---

.github/workflows/pythonapp.yml
setup.py
test/README.md
test/test_scanner.py

Closes https://github.com/intel/cve-bin-tool/issues/340

Use pytest parametrize

---

.github/workflows/pythonapp.yml
requirements.txt

added pytest to requirements.txt

---

cve_bin_tool/checkers/icu.py
cve_bin_tool/checkers/sqlite.py

icu documentation updated.

---

cve_bin_tool/cvedb.py

fixed:nvd data mismatch results in critical error

---

cve_bin_tool/checkers/bluez.py

Make bluez checker work for "contains"

---

.gitignore

These are folders created by PyCharm IDE specific to each user

Added ".idea" and "/venv/"

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/bzip2.py
test/binaries/test-bzip2-1.0.3.c
test/binaries/test-bzip2-1.0.6.c
test/test_scanner.py

Add new checker for bzip2

---

test/binaries/test-gnutls-cli-2.1.6.c
test/binaries/test-gnutls-serv-2.1.6.c
test/test_scanner.py

Add test using real files for gnutls

---

test/binaries/test-openssh-6.9.c
test/test_scanner.py

Add test using real files for openssh

---

MANUAL.md
README.md
cve_bin_tool/cli.py

Solves issue #490
Also changed Readme document with the same.

Changed Version argument from -v to -V

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/rsyslog.py
test/binaries/test-rsyslog-5.5.6.c
test/test_scanner.py

Add checker for rsyslog

---

test/binaries/test-zlib-1.2.2.c
test/test_scanner.py

Add test using real files for zlib

---

test/test_checkers.py

Hi, here is a pull request for curl corresponding to one element of this issue : #411

Add curl filename checker test

---

test/binaries/test-tiff-4.0.2.c
test/test_scanner.py

 Add test using real files for tiff

---

CSV2CVE.md
README.md

**Additions**
- Updated the list of available checkers
- Updated the example_output of CSV2CVE.md

Updated Readme.md and CSV2CVE.md

---

test/binaries/test-expat-2.2.2.c
test/test_scanner.py

 Add test using real files for expat

---

test/test_scanner.py

test: Temporarly remove node filetest

---

cve_bin_tool/checkers/binutils.py

Fixed Binutils.py showing fasle positives

---

test/test_scanner.py

fixed Failing tests on test_scanner.py

updated links for failing tests

---

cve_bin_tool/checkers/python.py
test/binaries/test-py_thon-3.7.1_1.c
test/binaries/test-py_thon-3.7.1_2.c
test/binaries/test-py_thon-3.7.1_3.c
test/test_scanner.py

Changes
------------
- Added few binaries that will increase the coverage 
- Updated python checker. While I was writing python checker I thought if a file contains "python" keyword then that file may python but Now I think I was wrong and this was possibly producing some false positives. Although the files didn't contain the version and they were not appearing on the final_output but still I want to update the checker.

improved coverage for python

---

.pre-commit-config.yaml
README.md

* Also, update pre-commit hook to remove explicit python 3.6 version.

Include pre-commit for black in contributor info

---

cve_bin_tool/OutputEngine.py
cve_bin_tool/cli.py
cve_bin_tool/html/Example/example.html
cve_bin_tool/html/css/style.css
cve_bin_tool/html/templates/base.html
requirements.txt

This PR is just for making my code public  for task 1 ( template code )

Html report Stage 1 Task 1 ( Probabbly don't want to merge )

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/openafs.py
test/binaries/test-open.afs-1.6.12.c
test/binaries/test-openafs-1.6.7.c
test/test_scanner.py

New checker - openafs
CVE Data - https://www.cvedetails.com/product/2873/Openafs-Openafs.html?vendor_id=1664
Strings found used in regex

Add checker for openafs

---

cve_bin_tool/checkers/syslogng.py
test/binaries/test-syslogng-1.5.15.c
test/binaries/test-syslogng-3.2.4.c
test/test_scanner.py

#681 Updated Vendor Product pairs as well as binary for Syslog-ng checker

updated syslog-ng checker

---

cve_bin_tool/cvedb.py
cve_bin_tool/extractor.py

Normalizing relative / non-relative imports in cvedb.py and extractor.py 
Reference : Issue #659

Normalizing imports

---

.github/workflows/pythonapp.yml
requirements.txt

Now it only takes 3-4 minutes to complete test_scanner with LONG_TESTS flag set !!!

parallelize pytest to reduce testing time.

---

cve_bin_tool/OutputEngine.py

Corrected the generate_filename function

---

cve_bin_tool/checkers/python.py

checkers: python: Remove print statement

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/bash.py
test/binaries/test-b.ash-1.14.1.c
test/binaries/test-bash-1.14.0.c
test/test_scanner.py

Add checker for bash

---

cve_bin_tool/OutputEngine.py
cve_bin_tool/log.py
requirements.txt
test/test_output_engine.py

Fixes: #752 
Changes
-------------
Beautiful Colored tabular output for console Output. Updated Logs with coloured logs with syntax highlighting.

Added Support for Coloured Console Output

---

cve_bin_tool/extractor.py

Fix test to verify cpio command success 

---

cve_bin_tool/OutputEngine.py
test/test_output_engine.py

Changes
------------
- We'll now also have Vendor name in CSV, JSON, Console Output.
- Updated Tests for the same.

Added Vendor in Console, CSV and JSON output

---

cve_bin_tool/version_scanner.py
test/test_scanner.py

Changes
------------
- Added Feature to Log the specific file_path. I'm not storing the file path as that is out of the scope for this PR.
- Fixes #780, Fixes #793 
@terriko @pdxjohnny - PR is ready for review

Full specific path to the file

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/glibc.py
test/test_data/__init__.py
test/test_data/glibc.py

Add checker for glibc 

---

test/test_scanner.py

Fix problem with escape sequence in strings of test_false_positive function.

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/mariadb.py
test/test_data/__init__.py
test/test_data/mariadb.py

Add mariadb checker

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/mysql.py
test/test_data/__init__.py
test/test_data/mysql.py

Add mysql checker

---

cve_bin_tool/checkers/bind.py
cve_bin_tool/checkers/libarchive.py
cve_bin_tool/checkers/samba.py

removed VERSION_PATTERNS from CONTAINS_PATTERNS

---

cve_bin_tool/error_handler.py

OutputEngine: filename generation bug fix

---

cve_bin_tool/cve_scanner.py

This is will improve scanning time significantly by avoiding unnecessary database query.

CVEScanner: short circuit path updation logic if product already scanned.

---

cve_bin_tool/error_handler.py
cve_bin_tool/output_engine/__init__.py

I have used epitext here but since Harmandeep Singh has been using Google style docstring for quite a while and because it's more popular among Python developer. I hink it would be good to switch to it.

Improved ErrorHandler and Migrated to Google style docstring.

---

cve_bin_tool/checkers/README.md

In reference to #866 
Closes #877

tests for checkers in checkers README

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/subversion.py
test/test_data/__init__.py
test/test_data/subversion.py

Added subversion checker

---

cve_bin_tool/cli.py
test/config/cve_bin_tool_config.toml
test/config/cve_bin_tool_config.yaml
test/test_cli.py

#786. Option -x retained for backward compatability

Change default for extraction from archives (#786)

---

cve_bin_tool/cvedb.py
requirements.txt

With many thanks to @imsahil007 and @anthonyharrison for the diagnosis and fix in the master branch.
Notes: 
- The CI is going to be broken, because some links have changed since the 1.0 test suite was written.  That's ok and I don't think i'm going to backport test suite fixes at this time (there's not much point with 2.0 looming).
- This code itself isn't working for me locally, so this PR is up for review/help from anyone with fresher eyes

 Backport nvd scraping patch to 1.0

---

cve_bin_tool/version.py

Note that this is going cause a merge conflict on #927 , but I think that PR needs some additional revision before it can be merged anyhow so that shouldn't be a big deal.

Version bump to 2.0a for upcoming 2.0 alpha release

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/gcc.py
test/test_data/__init__.py
test/test_data/gcc.py

Hey @terriko, please review my code 
#715 
It is my 1st time contributing to open source

new checker - gcc

---

cve_bin_tool/output_engine/print_mode.py
cve_bin_tool/version_scanner.py

https://lgtm.com/projects/g/intel/cve-bin-tool?mode=list

Fix LGTM issues

---

cve_bin_tool/checkers/gcc.py

Simple change that addresses the issue (adding gcc, gcc to the vendor/product list for gcc checker) #939 
Please let me know if there is something that I have missed out on thanks!
@terriko I notice that the gimp tests are failing I'm not sure if this is related to the MR you recently merged? (As I don't think this should be affecting that test from what I can tell) #943

Add gcc,gcc to vendor/product for gcc checker

---

README.md

It should **want** instead of  **wan**

Typo fixed  in README

---

doc/MANUAL.md
doc/conf.py

update readthedocs -format checker list table

---

doc/MANUAL.md

fixed typo in MANUAL.md

---

cve_bin_tool/version.py
doc/RELEASE.md

This is a draft of the 2.0 release notes
@Niraj-Kamdar @SinghHrmn and @SaurabhK122 in particular, let me know if there's anything else you wanted to highlight from your summer of code projects!

2.0 Release notes

---

cve_bin_tool/output_engine/html.py
cve_bin_tool/output_engine/print_mode.py

Bandit recommended enabling jinja2's autoescape for HTML.

Enable jinja2 autoescape

---

test/test_data/gimp.py

Update gimp test to use centos7 version

---

test/test_data/bash.py
test/test_data/curl.py
test/test_data/ffmpeg.py
test/test_data/icecast.py
test/test_data/international_components_for_unicode.py
test/test_data/libvirt.py
test/test_data/mariadb.py
test/test_data/nss.py
test/test_data/python.py
test/test_data/radare2.py
test/test_data/samba.py
test/test_data/systemd.py

update 404 binary urls for long tests

---

test/README.md

It's test_checkers.py  instead of test_checker.py

Fixed typo

---

cve_bin_tool/checkers/README.md

I wrote up a workflow that I've used before to find the version signature of
checkers. I thought it might be helpful.
Please let me know any thoughts

checkers: README: Add signature finding quickstart

---

.github/workflows/pythonapp.yml

Add a CI job to build the HTML docs
Related: #1023

ci: Build docs

---

doc/CONTRIBUTORS.md

found small spelling error while reading the guide for new contributors

fix typo in doc/CONTRIBUTORS.md

---

cve_bin_tool/checkers/zlib.py

Closes #1012 
zlib version string will work on now. There was some change in CONTAINS_PATTERN as well.

Update zlib checker version and contains pattern

---

README.md
doc/CONTRIBUTORS.md

In #1033  I have added isort with black compatibility.
Here are the contributor's guide and readme update changes

add isort contributors guide and update readme

---

cve_bin_tool/checkers/glibc.py

Fix glibc.py SyntaxWarning

---

cve_bin_tool/checkers/README.md

fixed some spelling and grammatical errors

fix typo in checkers/README.md

---

README.md

I also rearranged so black and isort are grouped together.

Add ReadTheDocs badge

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/libxslt.py
test/test_data/__init__.py
test/test_data/libxslt.py

@terriko please review my PR. #978

New checker libxslt

---

doc/CONTRIBUTORS.md

Not sure if this is the right place to add this. I can probably make this more verbose/detailed if needed.
#1062

Add WSL to doc

---

test/test_scanner.py

Improve error when component is not found in a longtest package

---

cve_bin_tool/egg_updater.py

Add type hints #761
Would continue to add type hints to more files

adding type hints

---

doc/conf.py
setup.py

This should close #1010 
Now we only have to update release no. from version.py
doc/conf.py and setup.py will use this value directly

doc/conf.py & setup.py will use release no. from version.py

---

cve_bin_tool/util.py
cve_bin_tool/version.py
cve_bin_tool/version_signature.py

Added type hints

---

cve_bin_tool/cli.py

As mentioned in Issue #953, an if-statement has been added to check whether a CSV/JSON file is being scanned or directories. It shall then display products or files accordingly.

Added an if statement for Issue #953

---

cve_bin_tool/checkers/python.py
cve_bin_tool/checkers/sqlite.py
cve_bin_tool/extractor.py
doc/conf.py
setup.py
test/test_cli.py
test/test_cvedb.py
test/test_extractor.py
test/test_scanner.py
test/test_strings.py

Here are the isort related changes as discussed in #1093

isort fixes with profile black

---

.github/workflows/pythonapp.yml
.isort.cfg
cve_bin_tool/output_engine/__init__.py
cve_bin_tool/output_engine/pdfbuilder.py
test/test_condensed_downloads.py

Fix isort CI check

---

cve_bin_tool/output_engine/html.py
cve_bin_tool/output_engine/html_reports/templates/base.html
cve_bin_tool/output_engine/html_reports/templates/dashboard.html
cve_bin_tool/output_engine/print_mode.py
cve_bin_tool/output_engine/print_mode/templates/content.html
cve_bin_tool/output_engine/print_mode/templates/showcase.html

Closes #1153 
HTML Reports now:
- Scanning Binaries [output.cve-bin-tool.2021-05-08.17-03-09](https://drive.google.com/file/d/1sUJZNqpsCipA8JlBoj0fUcU1Zy58t34x/view?usp=sharing)
- Scanning CSV [output.cve-bin-tool.2021-05-08.17-03-38](https://drive.google.com/file/d/1OLYxVemH-6LGWHXs0f-VD8zh0r0vFc9U/view?usp=sharing)

Minor HTML report fixes

---

cve_bin_tool/checkers/systemd.py

Fix systemd get_version()

---

cve_bin_tool/cli.py
cve_bin_tool/output_engine/__init__.py
cve_bin_tool/output_engine/html.py
cve_bin_tool/output_engine/pdfbuilder.py

closes #1148 
CVE reports
- HTML Report
- with CVEs: [output.cve-bin-tool.2021-05-16.14-49-43](https://drive.google.com/file/d/1MyXKZXzCM3UaOzen6JuV17-_RBSrbhp7/view?usp=sharing)
- without CVEs: [output.cve-bin-tool.2021-05-16.14-49-33](https://drive.google.com/file/d/1pZRUnpnh5s5fKS86EoLrVlM-ZGFE3R7F/view?usp=sharing)
- PDF Report
- with CVEs: [output.cve-bin-tool.2021-05-18.07-43-30.pdf](https://github.com/intel/cve-bin-tool/files/6497848/output.cve-bin-tool.2021-05-18.07-43-30.pdf)
- without CVEs: [output.cve-bin-tool.2021-05-18.07-43-42.pdf](https://github.com/intel/cve-bin-tool/files/6497850/output.cve-bin-tool.2021-05-18.07-43-42.pdf)

Generate CVE report when there no CVEs

---

cve_bin_tool/helper_script.py
test/test_helper_script.py

added vendor-product pair finding process from the CVE database

added vendor-product pair finding process

---

.github/workflows/pythonapp.yml
.gitignore
cve_bin_tool/cli.py
cve_bin_tool/error_handler.py
cve_bin_tool/merge.py
cve_bin_tool/output_engine/__init__.py
cve_bin_tool/output_engine/util.py
test/json/bad_intermediate.json
test/json/bad_metadata.json
test/json/test_intermediate.json
test/test_merge.py
test/test_output_engine.py

The checklist has been moved to #1174

Add intermediate reports in cve binary tool to merge outputs from different sources

---

README.md
doc/MANUAL.md
doc/how_to_guides/index.rst
doc/how_to_guides/use_intermediate_reports.md

add documentation for intermediate reports

---

README.md
doc/MANUAL.md

* Python Package list
* Ubuntu Package list

Add docs for package list parsers

---

.github/workflows/codeql-analysis.yml

I'm not 100% convinced this is going to be useful to us (we run other scans elsewhere so this could result in duplicated effort) but I thought I'd open up a PR for comment.  Are people interested in trying this out?

Try out Github's codeql analysis workflow

---

cve_bin_tool/output_engine/html.py
cve_bin_tool/output_engine/print_mode.py

Note that I haven't run tests on this because I'm running for lunch so I figured i'd let CI and my local env run in parallel.

Re-enable jinja2 autoescape (fixes #988)

---

README.md
cve_bin_tool/package_list_parser/__init__.py
doc/MANUAL.md

Add support for distros that use `dpkg` and `rpm` package managers.

feat(package-list-parser): dpkg and rpm package list parser support

---

cve_bin_tool/version.py
doc/conf.py

Version and year bump for 2.2 release.

---

cve_bin_tool/output_engine/html_reports/templates/base.html
cve_bin_tool/output_engine/html_reports/templates/row_cve.html
doc/how_to_guides/customize_html_report.md
test/sample_report/html_report.html

https://rules.sonarsource.com/html/RSPEC-5148

fix(security): add noreferer in target=_blank inside html reports

---

test/test_scanner.py

The condensed downloads were made without any proper strings in it due to the changes in #1227.

fix: condensed downloads

---

README.md
cve_bin_tool/cli.py
cve_bin_tool/cvedb.py
cve_bin_tool/error_handler.py
cve_bin_tool/nvd_api.py
doc/MANUAL.md
doc/how_to_guides/index.rst
doc/how_to_guides/use_incremental_updates.md
test/test_nvd_api.py

Need updating the logs while loading the *.gzip.json files
Note - It takes a lot of time

feat: Add NVD CVE Retrieval API

---

doc/conf.py
doc/requirements.csv
doc/requirements.txt

Fix #1158
**In `conf.py`:**
Replaced "recommonmark" in `extensions` with "myst_parser"
**In `requirements.txt`:**
Removed recommonmark==0.6.0 
Added myst_parser

Updated conf.py and requirements.txt 

---

.github/workflows/pythonapp.yml
.pre-commit-config.yaml
README.md
doc/MANUAL.md

This should resolve #1324 
@Molkree

feat: enable pre-commit format_checkers for CI

---

.github/workflows/pythonapp.yml

refactor(windows_tests): Update Python 3.8 to 3.9

---

README.md
doc/MANUAL.md

docs: backport-fix

---

cve_bin_tool/version_scanner.py

fix: unbound output variable in version_scanner

---

cve_bin_tool/package_list_parser/__init__.py
test/test_package_list_parser.py

refactor(package-list-parser): Make invalid packages log warning instead of throwing error

---

.github/workflows/spelling.yml

This should fix
- #1470
I can add a typo to this PR to check if it really fixes the issue.

ci: fix `check-spelling` workflow

---

.github/workflows/testing.yml

Hi, this is my first time contributing. I read that if the contribution is successful I was supposed to find a Contributors.md and add my name to it, but I didn't find that file so I didn't do anything of the sort.  Best, Sho Neriki

changed windows_tests timeout-minutes to 30

---

test/test_cvedb.py

test: disable test_01_nist_scrape in test_cvedb.py

---

.github/workflows/linting.yml
.pre-commit-config.yaml
dev-requirements.txt

ci: upgrade black (fixes #1621)

---

doc/conf.py
doc/requirements.txt

Update of Sphinx from 3.2.1 to 4.0.2 and changed conf.py to fix a warning.
Fixes Issue #1613

fix: Sphinx update #1613

---

CONTRIBUTING.md

Update the docs accordingly. 
fixes #1611

doc: improved finndability for issue (#1611)

---

cve_bin_tool/version.py

Final version bump needed before the 3.1 release!

feat: Bump version to 3.1 for release

---

cve_bin_tool/cvedb.py

refactor: add type hints in cvedb.py

---

cve_bin_tool/checkers/README.md

https://github.com/intel/cve-bin-tool/pull/609 -> this PR changed the path of cve.db from .cache/cvedb to .cache/cve-bin-tool. so i updated the README

docs: update checkers/README.md

---

.github/PULL_REQUEST_TEMPLATE/new_checker.md
cve_bin_tool/checkers/README.md

feat: add new checker pr template (#1268)

---

cve_bin_tool/checkers/README.md

docs: multiline pattern issue in windows vs linux (#1678)

---

doc/CHECKERS.md
doc/index.rst

docs: add checker instructions into Read the Docs build (#1703)

---

cve_bin_tool/format_checkers.py
test/test_format_checker.py

refactor(format_checkers): use pathlib instead of os.path (#1725)

---

test/test_version.py

test: unit tests for version.py

---

cve_bin_tool/extractor.py

test: fix test_extract_file_cab_no_cabextract for windows

---

doc/requirements.txt

https://github.com/ryanfox/sphinx-markdown-tables/issues/36

fix: doc build error

---

.github/workflows/coverity.yml

ci: use coverity filesystem search

---

cve_bin_tool/checkers/systemd.py

fix: fixed systemd checker version pattern

---

.github/workflows/cve_scan.yml

ci: run cve check on main only

---

doc/requirements.csv

my bad, i forgot to update the doc/requirements.csv file

fix: test/test_requirements.py::test_txt_csv_sync

---

.github/workflows/cve_scan.yml

Reverts intel/cve-bin-tool#1804

ci: run cve check on all PRs

---

cve_bin_tool/output_engine/html_reports/templates/base.html
cve_bin_tool/output_engine/html_reports/templates/row_cve.html
test/sample_report/html_report.html

fix #1836
This is due to Bootstrap's changes in https://github.com/twbs/bootstrap/commit/418f17ee2b849dafdc39623ba2378df9229164a7 from v5 onwards

fix: replace `data-*` attributes with `data-bs-*` attributes

---

.github/workflows/cve_scan.yml
dev-requirements.txt
requirements.csv
requirements.txt

In #1665 `pytest` and `py` weren't moved to dev-requirements.txt according to #1312

chore(deps): move pytest and py to dev-requirements.txt

---

cve_bin_tool/data_sources/osv_source.py

fix: OSV ClientConnectorError

---

test/test_source_osv.py

test: add tests for OSV data_source

---

test/test_source_osv.py

fix: OSV tests failing

---

cve_bin_tool/data_sources/__init__.py
cve_bin_tool/output_engine/console.py

fix: quality issues reported by LGTM

---

cve_bin_tool/data_sources/osv_source.py

chore: change unable to fetch osv warning to error

---

test/test_source_osv.py

fix: OSV test failing due to update in CVE

---

.github/workflows/testing.yml
cve_bin_tool/cli.py

fix: improve behaviour when -u never and -n json are both specified

---

cve_bin_tool/format_checkers.py
test/test_format_checker.py

fix(format_checkers.py): add newline at the end of file

---

cve_bin_tool/cvedb.py
test/test_cvedb.py

fix: windows long tests failing

---

cve_bin_tool/parsers/javascript.py

fix: javascript keyerror

---

.github/workflows/testing.yml

ci: ubuntu long tests aren't running when tried manually

---

cve_bin_tool/parsers/go.py

refactor: cleanup go parser constructor

---

cve_bin_tool/output_engine/print_mode.py

refactor(print_mode.py): use pathlib.Path instead of os.path

---

cve_bin_tool/output_engine/html.py

refactor(html.py): use pathlib.Path instead of os.path

---

cve_bin_tool/input_engine.py

refactor(input_engine.py): use pathlib.Path instead of os.path

---

cve_bin_tool/cve_scanner.py

refactor(cve_scanner.py): use pathlib.Path instead of os.path

---

cve_bin_tool/config.py

refactor(config.py): use pathlib.Path instead of os.path

---

cve_bin_tool/output_engine/__init__.py

refactor: use pathlib in output_engine/__init__.py

---

cve_bin_tool/cli.py

refactor: use pathlib in cli.py

---

cve_bin_tool/version_scanner.py

refactor: use pathlib in version_scanner.py (fixes #1982)

---

cve_bin_tool/available_fix/debian_cve_tracker.py
cve_bin_tool/merge.py

refactor: add pathlib support to merge.py & available_fix

---

cve_bin_tool/package_list_parser.py

fixes: #1984
Updated from os.path to pathlib in package_list_parser.py

refactor: update to pathlib in package_list_parser.py

---

.github/actions/spelling/allow.txt
cve_bin_tool/checkers/README.md

Also...
* add table of contents to file
* fix markdown lint errors

docs: Add instructions on finding binaries to checker docs

---

.github/actions/spelling/allow.txt
cve_bin_tool/format_checkers.py

fix: add "pure" to exclude list in format_checkers.py and remove from allow.txt

---

cve_bin_tool/checkers/__init__.py

Fixes https://github.com/intel/cve-bin-tool/issues/2120 🎃

refactor mypy type issues in __init__.py

---

cve_bin_tool/checkers/bind.py
test/test_data/bind.py

Current bind checker doesn't work with some exotic bind library

fix: improve bind checker patterns

---

test/test_language_scanner.py

refactor: test_language_scanner 

---

doc/MANUAL.md

added a sentence under the "How it Works" header. (line 189)

feat(docs): added that the tool only matches strings of length 3+

---

doc/MANUAL.md

Just used the new VS Code [Markdown link validation features](https://code.visualstudio.com/docs/languages/markdown#_link-validation) to find these.

docs(manual): various fixes

---

.mypy.ini

Continuing to prepare for enabling mypy on all code in CI.

fix: add more libraries to mypy types missing list

---

cve_bin_tool/checkers/jhead.py

chore: fix mypy errors in checkers/jhead.py

---

cve_bin_tool/checkers/glib.py
test/test_data/glib.py

Current glib checker doesn't work with some glib libraries

fix: improve glib checker patterns

---

cve_bin_tool/package_list_parser.py

chore: fix mypy errors in package_list_parser.py

---

cve_bin_tool/async_utils.py
requirements.txt

chore: fix mypy errors in async_utils.py

---

cve_bin_tool/version_signature.py

refactor: fix mypy errors in version_signature.py

---

cve_bin_tool/data_sources/curl_source.py
cve_bin_tool/data_sources/gad_source.py
cve_bin_tool/data_sources/osv_source.py
cve_bin_tool/data_sources/rsd_source.py

chore: fix mypy errors in data_sources/*

---

.mypy.ini
dev-requirements.txt

Do not ignore some libs that have stub packages.
Fixes #2254

fix: better handling of 3rd party libs for `mypy`

---

cve_bin_tool/cvedb.py

chore: fix mypy errors in cvedb.py

---

cve_bin_tool/format_checkers.py

refactor: fix mypy issues in format_checkers.py

---

cve_bin_tool/checkers/accountsservice.py
cve_bin_tool/checkers/acpid.py
cve_bin_tool/checkers/apcupsd.py
cve_bin_tool/checkers/asn1c.py
cve_bin_tool/checkers/assimp.py
cve_bin_tool/checkers/asterisk.py
cve_bin_tool/checkers/atftp.py

chore: fix mypy errors in checkers/a*.py

---

cve_bin_tool/checkers/bird.py
cve_bin_tool/checkers/bison.py
cve_bin_tool/checkers/boinc.py
cve_bin_tool/checkers/bro.py
cve_bin_tool/checkers/bubblewrap.py

chore: fix mypy errors in checkers/b*.py

---

cve_bin_tool/checkers/c_ares.py
cve_bin_tool/checkers/chess.py
cve_bin_tool/checkers/chrony.py
cve_bin_tool/checkers/clamav.py
cve_bin_tool/checkers/collectd.py
cve_bin_tool/checkers/connman.py
cve_bin_tool/checkers/cronie.py
cve_bin_tool/checkers/cvs.py

chore: fix mypy errors in checkers/c*.py

---

cve_bin_tool/checkers/darkhttpd.py
cve_bin_tool/checkers/davfs2.py
cve_bin_tool/checkers/dhcpcd.py
cve_bin_tool/checkers/domoticz.py

chore: fix mypy errors in checkers/d*.py

---

cve_bin_tool/checkers/fastd.py
cve_bin_tool/checkers/file.py

chore: fix mypy errors in checkers/f*.py

---

test/README.md

docs: add table of contents to test/README.md

---

cve_bin_tool/checkers/e2fsprogs.py
cve_bin_tool/checkers/elfutils.py
cve_bin_tool/checkers/exim.py
cve_bin_tool/checkers/exiv2.py

refactor: fix mypy errors in checkers/e*.py

---

cve_bin_tool/checkers/haproxy.py
cve_bin_tool/checkers/haserl.py
cve_bin_tool/checkers/hostapd.py

chore: fixed mypy issues in checkers/h*.py

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/checkers/git.py
test/test_data/git.py

feat(checker): add git checker

---

README.md

Fixed #2317 
Updated number of checked from 100 to over 200

fix: Updated number of checkers mentioned in docs

---

README.md
cve_bin_tool/format_checkers.py

Fixed #2317 
Added a function in format_checkers.py to continuously update number of checkers mentioned in docs.

feat: Added function to update number of checkers in docs

---

cve_bin_tool/helper_script.py

Fixes #2326 
I had some errors with test_html.py locally.  I don't have playwright installed and looks like it might depend on it?

fix: escape rich console markup close tags [/]

---

cve_bin_tool/cli.py
cve_bin_tool/cve_scanner.py
cve_bin_tool/output_engine/__init__.py
cve_bin_tool/output_engine/console.py
cve_bin_tool/output_engine/util.py
test/test_source_osv.py

A few other tweaks required relating to report of products with no vulnerabilities and also to produce a report if no vulerabilities found in any of the products.
And few reporting issues as well where the numbers weren't quite right.

fix: Improve output for Mitigated and Ignored CVEs (Fixes #1752)

---

cve_bin_tool/sbom_manager/__init__.py
cve_bin_tool/sbom_manager/cyclonedx_parser.py
cve_bin_tool/sbom_manager/spdx_parser.py
cve_bin_tool/sbom_manager/swid_parser.py

Fixes #2379 
Updated types in cve_bin_tool/sbom_manager.

refactor: update types in cve_bin_tool/sbom_manager

---

cve_bin_tool/extractor.py
test/test_cli.py
test/test_extractor.py

I'm having some trouble with getting #2133 to work, this is a temporary place so I can mess around in my own repo and don't have to keep pushing over someone else's branch.

fix: remove use of tarfile

---

.github/workflows/testing.yml
test/README.md
test/test_available_fix.py
test/test_cvedb.py
test/test_nvd_api.py
test/test_source_gad.py
test/test_source_nvd.py
test/test_source_osv.py
test/utils.py

ci: group tests which rely on external connectivity into a separate CI

---

cve_bin_tool/version.py
setup.py

Some pre-release prep.  I'm hoping to release rc0 this week so people can test it.

chore: bump version, python_requires

---

cve_bin_tool/cli.py
cve_bin_tool/csv2cve.py
setup.py

Fixes #2403 
Fail gracefully when someone tries to use python 3.6

feat: Fail gracefully when someone tries to use python 3.6

---

.github/workflows/update-dev-requirements.py
.pre-commit-config.yaml

Removed unnecessary import
Unindented some code
Renamed some vars to be more clear and consistent
Added some input fixing (`lstrip` whitespaces), also corrected it in yml

refactor: cosmetic fixes to dev reqs updater

---

cve_bin_tool/cvedb.py
cve_bin_tool/version.py

possibly the last commit before we can release 3.2!

fix: Add warning for slow schema updates, bump version to 3.2

---

cve_bin_tool/data_sources/gad_source.py

fix: gad_source error while updating cache

---

cve_bin_tool/output_engine/__init__.py

This should fix encoding issue on Windows from #2498.

fix: encoding issues on Windows

---

test/test_scanner.py

fix: fix recursively typo

---

.github/actions/spelling/allow.txt
README.md

docs: Docs claim that ar is installed by default on Windows

---

.github/workflows/update-cache.yml

Fixes [#2576](https://github.com/intel/cve-bin-tool/issues/2576)

ci: removed windows-specific cache

---

test/README.md

docs: updated test README.md

---

cve_bin_tool/parsers/python.py
test/test_language_scanner.py

Fixes #2622
Fixes test_language_package fails on python requirements.txt and removes hardcoding of string

fix: test_language_package fails

---

cve_bin_tool/checkers/hostapd.py

Update pattern to detect version in hostapd_cli

fix: improve hostapd checker

---

cve_bin_tool/parsers/python.py

fix: wrong pip version slicing

---

cve_bin_tool/checkers/sqlite.py

Update signature checker to catch all SQLITE hashes (needed for upcoming hyperscan addition)

fix: improve sqlite signature

---

cve_bin_tool/checkers/bind.py
test/test_data/bind.py
test/test_data/jacksondatabind.py

Update second pattern to avoid a false positive with jacksondatabind

fix: improve bind checker

---

README.md
cve_bin_tool/sbom_manager/__init__.py
cve_bin_tool/sbom_manager/cyclonedx_parser.py
doc/MANUAL.md
test/sbom/cyclonedx_mixed_test.json
test/sbom/spdx_mixed_test.spdx.json
test/test_sbom.py

fix: Cyclonedx does not read title case product names

---

.github/workflows/formatting.yml

Changed line 1 and line 12 to say "Update checkers table" as required in the corresponding issue.
fixes #2726

ci: Change "Formatting" workflow name to "Update checkers table"

---

.github/workflows/testing.yml

fix: window short test offline flag

---

cve_bin_tool/output_engine/print_mode.py

chore: fix mypy errors in print_mode.py

---

test/test_cli.py

Fixes #2743 
fix windows longtests in test/test_cli.py::TestCLI::test_SBOM

test: windows longtests in test/test_cli.py::TestCLI::test_SBOM

---

.github/workflows/cve_scan.yml
.github/workflows/testing.yml
.github/workflows/update-cache.yml
doc/how_to_guides/cve_scanner_gh_action.md
doc/how_to_guides/cve_scanner_gh_action.yml

ci: windows short tests database error (#2775)

---

cve_bin_tool/checkers/tcpdump.py
test/test_data/tcpdump.py

Update checker to handle 'exotic" binaries

fix: improve tcpdump checker

---

cve_bin_tool/cvedb.py
test/test_cvedb.py

- added timestamp to the metadata of exported data
- added test for import export json

test: add test for import export json

---

cve_bin_tool/output_engine/__init__.py

chore: fix mypy errors in file output_engine/__init__.py

---

.github/workflows/export_data.yml

fix: export database ci

---

cve_bin_tool/output_engine/util.py

chore: fixes most mypy errors in file output_engine/util.py

---

cve_bin_tool/cli.py
cve_bin_tool/error_handler.py

Added new classes and corresponding error codes to avoid returning the -1 values during certain exceptions.

fix: -1 values were replaced with positive integer error codes (fixes  #2838)

---

cve_bin_tool/output_engine/html.py
cve_bin_tool/output_engine/util.py

addresses #2765
fixes mypy errors on `output_engine/html.py#71`, `output_engine/html.py#160` & `output_engine/html.py#170`

fix: mypy errors in `output_engine/html.py`

---

test/test_scanner.py

See #2888 for progress on fixing them.

fix: temporarily disable failing ceph tests

---

.github/workflows/codeql-analysis.yml
.github/workflows/coverity.yml
.github/workflows/cve_scan.yml
.github/workflows/export_data.yml
.github/workflows/formatting.yml
.github/workflows/linting.yml
.github/workflows/sbom.yml
.github/workflows/scorecard.yml
.github/workflows/spelling.yml
.github/workflows/testing.yml
.github/workflows/update-js-dependencies.yml
.github/workflows/update-pre-commit.yml
.github/workflows/update-spdx-header.yml
doc/how_to_guides/cve_scanner_gh_action.md
doc/how_to_guides/cve_scanner_gh_action.yml

ci: updated workflow configurations

---

.github/workflows/testing.yml

CI: Added json tests to "may fail" test job

---

README.md

docs: fix image link in README.md

---

.readthedocs.yml

docs: Change readthedocs build from pdf to html

---

.github/workflows/cve_scan.yml

ci: force directory overwrite during cache mv

---

.github/actions/spelling/allow.txt

ci: "githubusercontent" added to allow.txt

---

cve_bin_tool/data_sources/curl_source.py

fixes #2977 #2969
this issue occurred because of this:
from wayback machine ->
now ->

fix: curl datasource (#2977)

---

cve_bin_tool/package_list_parser.py
test/test_package_list_parser.py

test: Improve coverage for unsupported distros in package_list_parser.py

---

doc/how_to_guides/index.rst
doc/index.rst
doc/new-contributor-tips.md

docs: including doc in build

---

.github/workflows/scorecard.yml

ci: dedeuplicate usage of codeql

---

cve_bin_tool/cvedb.py

refactor: improve explanation of cve year parsing

---

.github/actions/spelling/allow.txt
README.md

docs: update openssf scorecard link in README.md

---

.github/workflows/codeql-analysis.yml

Resolves: https://github.com/intel/cve-bin-tool/issues/3133

chore: exclude autobuild step

---

cve_bin_tool/output_engine/console.py
test/test_output_engine.py

feat: adding EPSS to console table

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feat-request.md

Adds generic templates for bug reporting and feature requests that aren't checkers, with some questions to help guide folk submitting new issues.
* fixes #3222

chore: Add additional issue templates

---

cve_bin_tool/data_sources/osv_source.py

fixes #3260
discussed in #3201
also this was causing the cve-bin-tool github action to fail.

fix: osv version parsing

---

.github/workflows/cve_bin_tool_action.yml

related https://github.com/intel/cve-bin-tool-action/pull/38

ci: use cveb.in mirror in cve-bin-tool-action

---

README.md

docs: cve-bin-tool-action links & instructions

---

cve_bin_tool/checkers/iperf3.py

[CVE-2023-38403](https://nvd.nist.gov/vuln/detail/CVE-2023-38403) is registered under es:iperf3 CPE ID

fix: add additional iperf3 CPE ID

---

cve_bin_tool/cli.py

docs: add missing docstrings to cli.py

---

cve_bin_tool/data_sources/gad_source.py

Addresses #3466 
I have added dockstrings for GAD_Source.format_data and GAD_Source.get

docs: added missing GAD_Source docstrings

---

cve_bin_tool/output_engine/__init__.py
test/test_cli.py

test: re-enable test_SBOM in test_cli.py

---

test/test_package_list_parser.py

test: enable package list

---

cve_bin_tool/checkers/mosquitto.py

Update mosquitto pattern to avoid false positives with libmosquittopp

fix: update mosquitto pattern

---

cve_bin_tool/version.py

There may still be a 3.3rc2 release before 3.3, but I want to be ready.  We're getting close!

chore: bump version for 3.3 release

---

cve_bin_tool/checkers/coreutils.py

Update coreutils pattern to avoid a false positive in `standards.info`

fix: update coreutils pattern

---

test/test_cli.py
test/test_csv2cve.py
test/test_exploits.py
test/test_language_scanner.py
test/test_sbom.py
test/test_triage.py

Temporary measure so CI will stay clean while we work on fixing the tests mentioned in #3653

test: temporarily disable failing tests

---

.github/ISSUE_TEMPLATE/docstrings.md

I'm intending to add a bunch of docstrings issues for beginners so I wanted to make it easier for me (or anyone else!) to do so.

chore: add template for docstrings issues

---

cve_bin_tool/version.py

Bumping version in preparation for a pre-release.

chore: set version to 3.3rc2 for pre-release

---

cve_bin_tool/strings.py

docs: added docstrings to cve_bin_tool/strings.py

---

cve_bin_tool/data_sources/redhat_source.py

* closes #3713 
* Added docstrings for redhat_source.py

docs: Added docstrings to cve_bin_tool/data_sources/redhat_source.py

---

cve_bin_tool/checkers/frr.py

Add frrouting:frrouting CPE ID to avoid missing 28 vulnerabilities

fix: update frr VENDOR_PRODUCT

---

.github/actions/spelling/allow.txt
doc/MANUAL.md

Turns out although we talk about deployment expectations pretty regularly, they're scattered all over.  This is a first pass at collecting together our deployment expectations, best practices, and tips for secure configuration of cve-bin-tool within a CI system.

docs: Deployment best practices guide

---

cve_bin_tool/error_handler.py
test/test_cli.py
test/utils.py

fix: fix network connection related fails of quiet_mode

---

.github/workflows/fuzzing.yml
cve_bin_tool/merge.py
test/test_merge.py

closes #3835.
related: #3800.
addresses: https://github.com/intel/cve-bin-tool/actions/runs/7868298355/job/21465298711
Output:

fix: resolve errors of fuzzing job fuzz_intermediate_report_merge

---

cve_bin_tool/output_engine/print_mode/templates/content.html

fixes #3899 
* Added required conditional check

fix: Html report fix

---

cve_bin_tool/egg_updater.py

fix: [#3878](https://github.com/intel/cve-bin-tool/issues/3878)

docs: add docs to cve_bin_tool/egg_updater.py(fix: #3878)

---

cve_bin_tool/csv2cve.py

**Checklist**
(This is a new PR for the same fix, this time I commited only the changes to csv2cve.py)
I updated `csv2cve.py` with a docstring for `main()`; then I ran `interrogate -vv -i -I -M -C -n -p cve_bin_tool/csv2cve.py` and got the following output:
```
---------------------------------------------------------------------------- Detailed Coverage ----------------------------------------------------------------------------
| Name                                                                                  |                                                                          Status |
|---------------------------------------------------------------------------------------|---------------------------------------------------------------------------------|
| csv2cve.py …
```

docs: Added docstrings to csv2cve.py (fixes #3877)

---

cve_bin_tool/output_engine/pdfbuilder.py

Added docstrings to pdfbuilder.py file.
cc @terriko 
fixes #3455

docs: Add docstrings to pdfbuilder.py

---

cve_bin_tool/checkers/snapd.py

Add an additional CPE ID for snapd checker. While at it, merge two patterns into a single one.

fix: update snapd checker

---

cve_bin_tool/parsers/__init__.py
cve_bin_tool/parsers/go.py

feat: added purl generation for go parser

---

.pre-commit-config.yaml

chore: add interrogate checks for fuzz

---

cve_bin_tool/config_generator.py

fix: config gen format

---

cve_bin_tool/output_engine/console.py

A tiny PR to correct a typo in the console report.
Hopefully useful, but no problems if not.

fix: fix typo of 'UNKNOWN' in console.py

---

cve_bin_tool/available_fix/debian_cve_tracker.py
cve_bin_tool/available_fix/redhat_cve_tracker.py
cve_bin_tool/checkers/sqlite.py
cve_bin_tool/cvedb.py
cve_bin_tool/output_engine/util.py
cve_bin_tool/util.py
cve_bin_tool/version.py
test/test_json.py
test/test_output_engine.py
test/test_source_osv.py

refactor: requests to happen in utils.py

---

cve_bin_tool/validator.py

@isonmeet. please review if everything is correct and let me know. Thank you for your time.

docs: Add docstrings to validators.py

---

cve_bin_tool/parsers/ruby.py

feat: added PURL generation to ruby parser

---

.github/workflows/cve_bin_tool_action.yml
TRIAGE.vex

chore: add triage for false positives

---

cve_bin_tool/parsers/javascript.py

feat: added PURL generation to JavascriptParser

---

cve_bin_tool/input_engine.py
cve_bin_tool/sbom_manager/__init__.py

a quick PR to fix docstring so that my test can run automatically 🥲
cc @terriko

docs: minor docstring fix

---

.github/workflows/build-wheel.yml

I think this is what's breaking the artifact builds from running.

ci: add jobs line in build-wheel.yml

---

.github/workflows/cve_bin_tool_action.yml

More tuning relative to openssf scorecard recommendations.

ci: put write permission in job

---

cve_bin_tool/cli.py
cve_bin_tool/cvedb.py
cve_bin_tool/data_sources/purl2cpe_source.py
cve_bin_tool/parsers/__init__.py
cve_bin_tool/parsers/python.py

feat: Separated data source integration from previous PR

---

cve_bin_tool/parsers/__init__.py
cve_bin_tool/util.py

purl string in ProductInfo class
I think many more things could be improved with this so do let me know your thoughts with this one.
cc @terriko @anthonyharrison @inosmeet

feat: purl in productinfo

---

cve_bin_tool/checkers/__init__.py
cve_bin_tool/cli.py
cve_bin_tool/parsers/parse.py
cve_bin_tool/version_scanner.py
example/oot-checker/oot_checker/checker_name.py
setup.py
test/test_checkers.py

- Related
- https://github.com/intel/cve-bin-tool/pull/4200#issuecomment-2181516335

feat: no entrypoint registration required in tree

---

cve_bin_tool/cvedb.py
cve_bin_tool/fetch_json_db.py
cve_bin_tool/parsers/__init__.py

This ensures a uniform way for all the data-sources, each can be accessed within the cve database.

feat: added purl2cpe into our database

---

cve_bin_tool/parsers/__init__.py

feat: improved purl for productinfo

---

cve_bin_tool/cvedb.py
cve_bin_tool/parsers/__init__.py
cve_bin_tool/parsers/python.py

I've also proposed a possible alternative of using `DELETE` query here.
cc @terriko

refactor: renamed deduplication database to mismatch

---

.github/actions/spelling/allow.txt
README.md
doc/MANUAL.md
doc/how_to_guides/vex_generation.md

documentation regarding the command line arguments for vex added in PR [4226](https://github.com/intel/cve-bin-tool/pull/4226)
cc @anthonyharrison @terriko

docs: documentation regarding vex commands

---

cve_bin_tool/mismatch_loader.py

These flags will be required to write tests for the script.

feat: added flags for mismatch_loader

---

.github/workflows/validate-yml.yml
.github/workflows/yaml_rules.py

Validates `mismatch_relations.yml` modified in latest commit. 

feat: added yaml checks for mismatch_relations file

---

sbom/cve-bin-tool-py3.8.json
sbom/cve-bin-tool-py3.8.spdx

Trying this manually while we sort out what's going wrong in the automated pull request creation.

chore: update SBOM for Python 3.8

---

sbom/cve-bin-tool-py3.9.json
sbom/cve-bin-tool-py3.9.spdx

Trying this manually while we sort out what's going wrong in the automated pull request creation.

chore: update SBOM for Python 3.9

---

sbom/cve-bin-tool-py3.11.json
sbom/cve-bin-tool-py3.11.spdx

Trying this manually while we sort out what's going wrong in the automated pull request creation.

chore: update SBOM for Python 3.11

---

sbom/cve-bin-tool-py3.10.json
sbom/cve-bin-tool-py3.10.spdx

Trying this manually while we sort out what's going wrong in the automated pull request creation.

chore: update SBOM for Python 3.10

---

cve_bin_tool/parsers/dart.py
cve_bin_tool/parsers/go.py
cve_bin_tool/parsers/java.py
cve_bin_tool/parsers/javascript.py
cve_bin_tool/parsers/perl.py
cve_bin_tool/parsers/php.py
cve_bin_tool/parsers/python.py
cve_bin_tool/parsers/r.py
cve_bin_tool/parsers/ruby.py
cve_bin_tool/parsers/rust.py
cve_bin_tool/parsers/swift.py

feat: enabled mismatch feature for remaining parsers

---

requirements.txt
test/test_vex.py
test/vex/test_cyclonedx_vex.json

this PR fixes the test failing due to lib4sbom update
cc @terriko @inosmeet

fix: failing vex test

---

cve_bin_tool/parsers/__init__.py
cve_bin_tool/parsers/dart.py
cve_bin_tool/parsers/go.py
cve_bin_tool/parsers/javascript.py
cve_bin_tool/parsers/perl.py
cve_bin_tool/parsers/php.py
cve_bin_tool/parsers/python.py
cve_bin_tool/parsers/r.py
cve_bin_tool/parsers/ruby.py
cve_bin_tool/parsers/rust.py
cve_bin_tool/parsers/swift.py

refactor: moved repetitive code from parsers to a generic function

---

.github/ISSUE_TEMPLATE/mismatch-report.md

cc @terriko @anthonyharrison @mastersans

feat: new issue template for mismatch information

---

.github/workflows/build-wheel.yml
.github/workflows/codeql-analysis.yml
.github/workflows/coverity.yml
.github/workflows/cve_bin_tool_action.yml
.github/workflows/cve_scan.yml
.github/workflows/dependency-review.yml
.github/workflows/formatting.yml
.github/workflows/fuzzing.yml
.github/workflows/linting.yml
.github/workflows/sbom.yml
.github/workflows/scorecard.yml
.github/workflows/spelling.yml
.github/workflows/testing.yml
.github/workflows/update-cache.yml
.github/workflows/update-js-dependencies.yml
.github/workflows/update-pre-commit.yml
.github/workflows/update-spdx-header.yml
.github/workflows/validate-yml.yml

Apparently there's a pool of github runners available to us that should work better, so I'm switching to use them.

ci: use intel-provided github runners

---

.github/actions/spelling/expect.txt

ci: Removed the terms mentioned in Issue  #4314

---

test/test_language_scanner.py

test: PURL generation for language parsers

---

test/test_mismatch_cli.py

test: mismatch cli utility

---

.github/workflows/validate-yml.yml

ci: mismatch yml checker needs new directory name

---

cve_bin_tool/version.py

Getting the version bump in a bit earlier this time so I can ask for it to be approved alongside what I hope are the last PRs to go in before 3.4.

chore: bump version to 3.4rc1

---

cve_bin_tool/version.py

chore: bump version to 3.4 release

---

cve_bin_tool/version.py

Had to do another pre-release to address a triage issue, but I'm still hopeful that next release really will be 3.4!

chore: bump version to 3.4

---

cve_bin_tool/cvedb.py

Match cve_metrics foreign key to the metrics table definition

---

test/test_util.py

fixes #4186
Adds unit tests for the ProductInfo class and functions.

test: purl in productinfo

---

README.md

Just a couple small updates and linting fixes 😁

docs: minor README improvements
