intel/cve-bin-tool

cve_bin_tool/extractor.py
A Debian package is an 'ar' archive with two files:
- control.tar.gz (metadata)
- data.tar.* (content)
Because cve-bin-tool only cares about the content it can skip iterating the
unpacked archives and go straight to data.tar. This file may be compressed with
a number of compressors so don't hardcode gzip, use glob to find the filename
and let tar determine how to unpack it.
Fixes #2
Signed-off-by: Ross Burton <ross.burton@intel.com>
=> extract: improve .deb extraction

cve_bin_tool/extractor.py
* Some extraction methods change cwd. Paths therefore must be
resolved to absolute paths.
Fixes: #3
=> extractor: Ensure use of absolute path

cve_bin_tool/cli.py, cve_bin_tool/util.py, test/test_util.py
* Check for file and strings binaries and error out before scanning if
not present.
=> cil: Error if required binaries are not in path

cve_bin_tool/NVDAutoUpdate.py
The way that extract_data() used to get version string was C-style iteration of the list, I modified that into using join, which is more pythonic, thus the code becomes more elegant and readable in terms of Python. I have tested in both python 2 and 3, all good.
=> make extract_data more pythonic

cve_bin_tool/NVDAutoUpdate.py
I was finding for ways to reduce download time of cve files and found using threads was a solution. The download time for the cve data can be significantly improved by using threads. 
I know that threading must be done safely. But since none of the threads in this PR access/work on the same resource, I think threads are safe here. 
Asynchronous programming would also have been a good solution . I wanted to use `async/await`,  but it does not work for earlier versions of python.
=> Threading for downloading cve data

cve_bin_tool/cli.py, cve_bin_tool/strings.py, test/test_strings.py
I have read the source code of `strings.c`, and I found it is reading each character in the file per se rather than trying to parse the file, which means categorizing each character and if it is a legal utf-8 character, adding it to the output. However, Python is hard to do that since it treats those differently with bash and neither `encode` nor `decode` could work. Finally I got my naive version of strings based on that, which is able to run.
Of course this has many deficiencies such as unnecessarily added many garbage into `o` and it is potentially able to overflow buffers.
Any thoughts for the improvement would be appreciated.
=> Naively implement strings in pure Python

cve_bin_tool/cli.py, test/test_cli.py
- Made the list of checkers available when you do -h or run with no arguments
- made the error cases return negative numbers to use as error codes (positive returns indicate the # of files with CVEs, 0 indicates all is well and nothing was found)
=> Add list of checkers to usage; improve error output

test/test_extract.py
* check to see if required utilities exist (e.g. rpm, ar, unzip) before downloading files for extraction tests
* error messages now indicate that test failure is due to missing utility
* fixes #145 (well, it addresses the issue -- the test still fails but it's more obvious what's going on)
=> Better error messages in extraction tests

cve_bin_tool/checkers/xerces.py, test/test_scanner.py
Note that this only gets 3.1, not 3.1.1, because I couldn't find an easy signature to do that.  I'll open a new bug for it.
=> Get xerces version from centos package.  Fixes #132

test/test_scanner.py
Turns out that the "expat" package on debian is an example app and doesn't contain the library we're trying to detect.  We should have been testing against "libexpat" so this updates the test.
=> Use correct libexpat file for debian test (fixes #126)

cve_bin_tool/NVDAutoUpdate.py, cve_bin_tool/extractor.py, test/test_nvd.py
Our internal checklist encourages us to set directory permissions explicitly rather than relying on defaults, so that's what this patch is about.  the nvd directory is public info, so it *could* be 755 if we want, but I couldn't really think of too many cases where anyone would care so I defaulted to a less permissive 750.
=> Set explicit directory permissions at creation time

test/test_scanner.py
This was a side effect of testing something for a colleague about xml2 detection, and I figured once I'd done the parsing I might as well just turn it into a regression test because I hear testing is awesome.
Also, every single version of libxml2 has CVEs apparently.
=> Add xml2 file tests for the rpms on the xmlsoft website

cve_bin_tool/extractor.py
When I reviewed the code and tested on Windows I found that an `else` was missing here (which was used on windows system)
=> if statement

cve_bin_tool/cli.py, test/test_cli.py
Argparse does a sys.exit(2) for all bad arguments, but we're using the return code out of main for the # of cves (per a user request to go with quiet mode) so over-ride the behaviour to return a negative number instead, and add tests.
=> Add invalid param tests

cve_bin_tool/NVDAutoUpdate.py, test/test_json.py
Phase one: add test to test suite so we can check performance.  json schema validation takes 20s on my machine, sha256 sum takes 1 second, so sha256 sum wins.
Phase two: add faster check in to nvd updater.
=> Check json metadata

setup.py
Just in case a user has an older version installed, this will make sure their version of `jsonschema` is at least what it is today, or more up to date.
=> setup: requires: Add version to jsonschema

.travis.yml
It looks like travis network is failing during one of the update tests, and leaving us with an incomplete nvd database.  This doesn't seem to be related to our code, so I'm disabling travis for now and we can debug more if someone needs 3.4 support.
=> Disabling python3.4 in travis because of unrelated network errors

.travis.yml
Reverts intel/cve-bin-tool#207 (because it didn't fix the problem, just moved it to another version of python)
=> Revert "Disabling python3.4 in travis because of unrelated network errors"

cve_bin_tool/NVDAutoUpdate.py, cve_bin_tool/cli.py, test/test_nvd.py
Previously, the `nvd.get_cves()` function selected all versions for given package and then check whether the version we want is in the result. I refactored the code by using `LIKE` statement to select the version we want, so the performance is better now (also consumed less memory)
=> Refactor get_cve func

cve_bin_tool/NVDAutoUpdate.py
This just checks if the directory exists before trying to delete it.  Since there's nothing for the user to do if there's no directory, I'm not bothering to print a message.
=> Fail silently if .cache/cve-bin-tool does not exist (fixes #216)

cve_bin_tool/NVDAutoUpdate.py, cve_bin_tool/cli.py
Previously, the tool would print the message `"Updating CVE data. This will take a few minutes."` even if it then decided the database wasn't stale enough to warrant an update, so I've moved that message so it only happens if there's an update in progress. I left a generic "Checking if CVE data needs an update" where that message used to print, although this could maybe be moved to the debug log.
=> Improve CVE update messages

test/test_scanner.py
Fixed the broken package links, commented out a couple of CVEs that are affected by bug #1.  Note that CVE-2016-10087 is being missed due to a bug in NVDAutoUpdate and isn't a bug #1 problem.
=> Fix package links, comment out bug #1 cves

cve_bin_tool/checkers/__init__.py, cve_bin_tool/checkers/bluez.py
modified:   checkers/__init__.py
new file:   checkers/bluez.py
=> Added the Bluez checker

cve_bin_tool/cli.py
The 'version' variable can be an int, and string formatting on python3
fails if so.
also, happy hacktoberfest :)
=> Fix string formatting

cve_bin_tool/checkers/__init__.py, cve_bin_tool/checkers/openssh.py
Tested with a few debian variants (kali, ubuntu)
- listed the binaries with dpkq-query -L openssh-server and dpkg-query -L openssh-client
- checked with actual binaries from a few ubuntu server versions and current kali
Note, some(/all?) distributions ship versions with patches on top of the baseline release, eg: "OpenSSH_8.1p1 Debian-1" instead of just "OpenSSH_8.1". The checker checks for the complete version string, which should reduce the amount of false positives (vendor patched binaries hopefully don't contain vulnerabilities found in the baseline version).
=> Openssh checker

cve_bin_tool/checkers/openssh.py, test/binaries/test-openssh-7.9.c, test/test_scanner.py
In the checker we were doing a direct match on filenames and in the test `filename` = `/path/to/test-openssh-7.9.out` and that isn't and exact match with any of the filenames in the array.
Sorry it took me so long to get to this.
=> Openssh test

cve_bin_tool/checkers/__init__.py, cve_bin_tool/checkers/gnutls.py, test/binaries/test-gnutls-cli-2.3.11.c, test/binaries/test-gnutls-serv-2.3.11.c, test/test_scanner.py
new file:   gnutls.py
Closes #227
=> Added a checker for gnutls

cve_bin_tool/NVDAutoUpdate.py, cve_bin_tool/checkers/expat.py, cve_bin_tool/checkers/openssh.py, cve_bin_tool/cli.py, cve_bin_tool/csv2cve.py
Changes:
- Fixed mutable default arguments used in `cve_bin_tool/csv2cve.py` and `cve_bin_tool/cli.py`
- Removed unused imports in `cve_bin_tool/cli.py`, `cve_bin_tool/checkers/openssh.py` and `cve_bin_tool/NVDAutoUpdate.py`
- Use raw strings in `cve_bin_tool/checkers/openssh.py`, `cve_bin_tool/NVDAutoUpdate.py` and `cve_bin_tool/checkers/expat.py`
- Replaced `range(len(..))` with `enumerate()` in `cve_bin_tool/cli.py`
---
Some more issues on the repo's DeepSource dashboard on my fork [here](https://deepsource.io/gh/sanketsaurav/cve-bin-tool/issues/?show_minor=true).
=> Fix some bug risks and quality issues

cve_bin_tool/cvedb.py
This adds and checks version ranges, but it's using new code in cvedb.py (taken from @pdxjohnny's rewrite of the file handling) so there will sitll need to be work done to remove the old NVDAutoUpdate code and integrate this.  (Plus, the tests may need changes)
Caveats: this assumes that the start/end for a given range is stored in the same node.  A quick inspection showed this seemed to be the case, but it's not *required* to be that way, so further improvements may be needed in practice.
=> Bug #1 fix based on pdxjohnny's new nvd code

cve_bin_tool/checkers/bluez.py, cve_bin_tool/checkers/openssh.py, cve_bin_tool/cli.py
Fixes #268 #263 #259.  The version detection in openssh.py probably has a bug that's causing this still, though.
=> Fix openssh version not found issue, improve version error handling.

cve_bin_tool/NVDAutoUpdate.py, cve_bin_tool/checkers/kerberos.py, cve_bin_tool/checkers/sqlite.py, cve_bin_tool/cli.py, cve_bin_tool/csv2cve.py, cve_bin_tool/cvedb.py, cve_bin_tool/extractor.py, cve_bin_tool/log.py, test/test_nvd.py
1. This PR removes all print statements and replaces it with log statements. 
2. All logs below error level are logged to stdout and all logs above and equal to error level are logged to stderr 
Closes https://github.com/intel/cve-bin-tool/issues/197
Closes https://github.com/intel/cve-bin-tool/issues/182
=> Unify Logging

test/binaries/test-ffmpeg-4.1.3.c, test/test_scanner.py
Signed-off-by: sbs2001 <shivam.sandbhor@gmail.com>
The signature test for ffmpeg is `test_ffmpeg_deb_4_1_1` .
The  CVE mapping test for ffmpeg is `ffmpeg_4_1_3` .
Here is the output:
```
shivam@shivam-Latitude-D630:~/coding/opensource/cve-bin-tool$ python -m unittest test.test_scanner.TestScanner.test_ffmpeg_deb_4_1_1
rm *.out
gcc -o test-nss-3.45.out test-nss-3.45.c
gcc -o test-ffmpeg-4.1.3.out test-ffmpeg-4.1.3.c
gcc -o test-expat-2.0.1.out test-expat-2.0.1.c
gcc -o test-nss-3.35.out test-nss-3.35.c
gcc -o test-png-1.6.26.out test-png-1.6.26.c
gcc -o test-libgcrypt-1.7.6.out test-libgcrypt-1.7.6.c
gcc -o test-png-1.6.36.out test-png-1.6.36.c
gcc -o test-libjpeg-turbo-2.0.1.out test-libjpeg-turbo-2.0.1.c
gcc -o test-openssl-1.0.2g.out test-openssl-1.0.2g.c
gcc -o test-zlib-1.2.8.out …
```
=> Add ffmpeg tests

test/test_scanner.py
#301 looks like it's going to take some careful thinking to handled correctly, so I'm disabling the test so people aren't constantly failing CI while we work that out.
=> Disable kerberos tests temporarily due to #301

MANUAL.md, README.md, setup.py, test/README.md
fixes #297 
We aren't stripping out the remaining 2.7 compat stuff yet (because I've got other issues that have higher priority) but we might as well be clear that we're no longer testing on 2.7 at this point and that 0.3.1 was the last release with official 2.7 support.
=> Remove 2.7 from supported versions

test/test_scanner.py
Added gnutls file test for version 2.3.11. The 2.3.11 version was downloaded from the official gnutls website. All the test were fine. I've attached the test screenshot
=> gnutls file test added for version 2.3.11

cve_bin_tool/checkers/kerberos.py, cve_bin_tool/cli.py, test/test_scanner.py
- Adds a second VPkg listing to kerberos
- Makes the checker return results for both kerberos and kerberos_5
- Updates cli to handle multiple results returned from a single checker
- Updates kerberos tests to check appropriately
=> Improve kerberos checker (fixes #301)

test/test_cli.py
* Fixing error caused by #327 by changing it search only the skips list. 
* Changed the scanner to do a directory without binaries (for speed)
* added some more detailed error messages to the asserts.
=> Fix final_log to check only the skip line

test/test_csv2cve.py
fixes #249 
This test was previously disabled because it was faililng on Github Actions.  The problem appears to have been resolved, so I'm re-enabling it.
=> Enable test_sample_csv

test/test_cli.py, test/test_extract.py, test/test_scanner.py, test/utils.py
My decision making process was subpar when I choose the  name test_definitions.py for the test utilities. This PR renames it to  utils.py
=> test: Rename test_definitions to utils

setup.py
It was reported that running `cve-bin-tool` after running `python3 setup.py install` resulted in file not found error due to missing VERSION file.
=> Fix Version not found error

cve_bin_tool/OutputEngine.py, cve_bin_tool/cli.py, test/test_output_engine.py
Currently, CVE Binary Tool only outputs results in CSV format. It might be good to allow a wider range of uses by implementing alternative output formats such as JSON.
This pull requests implements very naive JSON output:
```
$ python -m cve_bin_tool.cli -f json test/binaries/test-expat-2.0.1.out 
cve_bin_tool.CVEDB - INFO - Using cached CVE data (<24h old). Use -u now to update immediately.
cve_bin_tool.Scanner - INFO - Checkers: bluez, curl, expat, ffmpeg, gnutls, icu, kerberos, libcurl, libdb, libgcrypt, libjpeg, libnss, libtiff, node, openssh, openssl, png, python, sqlite, systemd, xerces, xml2, zlib
cve_bin_tool - INFO - None
cve_bin_tool.Scanner - INFO - test/binaries/test-expat-2.0.1.out contains expat 2.0.1
cve_bin_tool.Scanner - INFO - Known CVEs in version 2.0.1 …
```
=> Add basic json output

cve_bin_tool/OutputEngine.py
Currently, the JSON out file looks something like the below code.
Although the output file can be used by machines as it is but this is not a good human-readable file. So we can use some indentation to reformat the JSON code. The following code shows  the expected output.
=> JSON out_file formatted

cve_bin_tool/checkers/gnutls.py
=>  Add contains functionality in gnults.py

test/test_output_engine.py
As briefly mentioned in #418, we should test the output produced by each method in OutputEngine. This PR tests the CSV output.
EDIT: closes #419
=> Add test for output_csv in OutputEngine

.github/workflows/pythonapp.yml
=> Fixed:Broken checkers cause CI to hang indefinitely 

test/README.md
small fix.
test/test_checker.py -> test/test_checkers.py at two places in the doc.
=> wrong test file name in README.md

.github/workflows/pythonapp.yml
- Sometimes when re-running the CI checking out the repo fails.
Upgrading to v2 of the checkout action fixes this.
=> ci: Use checkout action v2

test/test_scanner.py
Fixes #534 
The previous URL was failing sometimes, probably due to network issues. I switched it to a rpmfind url.
=> modify syslog-ng real binary url

test/test_scanner.py
This is an attempt to fix the CI which is currently broken because the test zlib-bin_1.2.8.dfsg-1ubuntu1.1_amd64.deb isn't working correctly.
=> Disable zlib 1.2.8 ubuntu test which is failing

cve_bin_tool/checkers/python.py, test/binaries/test-python-2.7.c, test/test_checkers.py, test/test_scanner.py
* Added CVE mapping tests for python2.7. Please note adding the CVE-2019-10160 results into failing the tests, even though its a valid CVE affecting this version, hence its commented out. Updating local database also does not help. (check https://nvd.nist.gov/vuln/detail/CVE-2019-10160). 
* Added new checker filename mapping test for python2.7 in `test/test_checkers.py`
* Removed a duplicate instance of downloading a python-3.8.2 package, hence it may help speedup long tests a bit.
=> Added tests for python2.7, since a lot of projects still use this version

test/test_scanner.py
This will fix the broken build issue.  However, I'm a bit concerned that if rpmfind isn't keeping the older files available, that this is always going to be a moving target.  We may need to find a better archival site to use for these tests.
=> Fix lighttpd filename

test/test_scanner.py
two of our tests are failing in CI due to the test files not downloading.  This PR temporarily disables them both.
When I run locally the lightttpd one runs correctly but the ffmpeg one does not.
=> Temporarily disable failing tests

test/test_scanner.py
ubuntu have updated ffmpeg version in archive that's why old link wasn't working. Don't know why Fedora link isn't working.
=> Fixes ffmpeg link for ubuntu and added lighttpd for suse

.github/workflows/pythonapp.yml
as discussed in gitter, runninng codecov on the short tests results in kind of useless automated coverage stuff that always says coverage is going down ~10%.  This is an attempt to make the coverage numbers we get on PRs be more realistic and meaningful.
=> Remove codecov checks from short tests

.github/workflows/pythonapp.yml
We're starting to get close to the 30 minute timeout on the long tests, so I'm upping it to 45 minutes for now.  Hopefully we'll be able to get it back down a bit with cacheing in the future.
=> Up long tests timeout to 45 min (from 30)

test/README.md, test/test_cli.py, test/test_json.py, test/test_scanner.py, test/utils.py
=> Improve handling if LONG_TESTS not set

cve_bin_tool/OutputEngine.py, test/test_output_engine.py
Changes
------------
- changed filename generation function in OutputEngine.py. Changed ```:```  to ```-``` because ```:``` is not a valid name character in Windows. And was the reason my tests were failing in windows.
-  Improved Coverage for cve_bin_tool/OutputEngine.py  (98% from  68.24%)
=> improved_coverage for output_engine

cve_bin_tool/VersionSignature.py, cve_bin_tool/cli.py, cve_bin_tool/cvedb.py, test/test_cli.py, test/test_json.py
Fixes #320 
* Changes back to old default directory of .cache/cve-bin-tool (from .cache/cvedb)
* Adds warning if old directory exists
* Removes old directory when `-u now` is used
I'll likely do the switch back to gzipped json files as well in future, but probably in a separate PR.
=> Switch back to .cache/cve-bin-tool

cve_bin_tool/cvedb.py, test/test_cvedb.py, test/test_json.py
```console
$ du -h ~/.cache/cve-bin-tool/*
226M    /home/johnsa1/.cache/cve-bin-tool/cve.db
20M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2002.json
5.4M    /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2003.json
12M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2004.json
18M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2005.json
28M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2006.json
27M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2007.json
31M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2008.json
30M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2009.json
43M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2010.json
83M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2011.json
40M     /home/johnsa1/.cache/cve-bin-tool/nvdcve-1.1-2012.json
43M …
```
=> cvedb: Store NVD JSON files gzip compressed

test/test_scanner.py
There were two lighttpd tests on the same file, just one stored at fedora and one in the fedora mirror on kernel.org.  Since the fedora one wasn't working, I've removed it and left the kernel.org one for now.  As kernel.org should be a mirror of fedora, I'm guessing if one breaks it's only a matter of time before the other does too.
=> Removed second lighttpd 1.4.54 test

cve_bin_tool/strings.py, test/test_strings.py
Here is the time it take to run comparison of time between pstring and new improved parse_3 function. New native implementation is twice as fast.  
pstring: 0.002876685000046564
string:   0.0014867500001400913
I have kept code i used to measure performance in test_strings.py. If anyone wants to check it.
=> Faster native solution for string parsing and removed parser for python2

README.md, cve_bin_tool/extractor.py
Fixes issue #667. Now tar working fine in windows. zstd compressed archive can be supported via 7zip-zstd fork. 
I have removed "tar" subprocess call because it is too slow compare to "shutil".
Here, is the code I used  for benchmarking and result from it.
```python
import shutil
import subprocess
import os
from time import perf_counter as pc
py, sub = 0, 0
os.mkdir("new1")
os.mkdir("new2")
for i in range(5):
d1 = f"new1/{i}"
d2 = f"new2/{i}"
os.mkdir(d1)
os.mkdir(d2)
d2 = os.path.join(os.getcwd(), d2)
t1 = pc()
shutil.unpack_archive("hadoop.tar", extract_dir=d1)
t2 = pc()
py += t2 - t1
t1 = pc()
subprocess.call(f"tar -C {d2} -xf hadoop.tar")
t2 = pc()
sub += t2 - t1
print(f"round {i} completed.")
print(f"time for subprocess tar: {sub}")
print(f"time for python shutil: {py}")
``` …
=> fixes many issues with extractor

cve_bin_tool/checkers/binutils.py, cve_bin_tool/checkers/png.py, test/binaries/test-binutils-2.31.1.c
Binutils includes some utilities with very short names, such as "ar" and "as" that were causing false positives in the filename checks.  I've updated a number of the shorter and more generic strings in binutils to include start and terminator matching so that we match "ar" but not "binaries" (which was causing binutils false positives on all our tests.  yuck!)
This caused the test case to fail because the test file wasn't matching the filename test.  I added one of the "contains" strings to the test file to trigger the match as expected.
=> Fix binutils false positives (fixes #677)

cve_bin_tool/checkers/__init__.py, cve_bin_tool/checkers/busybox.py, test/binaries/test-busy.box-1.18.3.c, test/binaries/test-busybox-1.10.3.c, test/test_scanner.py
New checker - busybox
CVE Data - https://www.cvedetails.com/product/7452/Busybox-Busybox.html?vendor_id=4282
Strings found used in regex
=> Add checker for busybox

test/binaries/test-binutils-2.31.1.c
Fixes #684 
This PR fixes the indentation error on binutils binary file
=> Indented binutils binary file

cve_bin_tool/csv2cve.py
Python 3.xx doesn't require the above dependency
=> Removed from __future__ import print

test/test_json.py
test_json can now be run in parallel with `pytest -n 4 test/test_json.py`:
```console
=================================================== 19 passed, 4 warnings in 85.99s (0:01:25) ====================================================
```
It is significantly faster now. Past implementation was taking roughly 10 minutes to run.
=> parallelize test_json

cve_bin_tool/version_scanner.py, test/test_scanner.py
This fixes #651, where the scanner would stop with an exception rather than simply skip the file when it encountered a non-regular file or a file that it couldn't open.  Many thanks to @anthonyharrison for the bug report and initial fix, and @darcyshx for helping me understand the urgency of the request better.
=> Skip invalid files without halting scan (Fixes #651)

cve_bin_tool/cve_scanner.py, cve_bin_tool/log.py, cve_bin_tool/output_engine.py
We don't need to specify this anymore since it's fixed in newer version of rich.
=> remove legacy_windows console option

cve_bin_tool/version.py
We've diverged pretty far from the 1.0 release, so it makes sense for the current development tree to have its own version.  1.1 is likely only ever going to be a development version number, as I expect our next release to be numbered 2.0 (to reflect major changes in output and general features).  I'm *hoping* to target the 2.0 release in the early fall after GSoC is complete, but that's not a firm date yet.
=> Update dev tree version to be 1.1

cve_bin_tool/cli.py
I have re-ordered execution order so that it will allow user to update database without having to scan a directory.
Fixes: #822
=> cli: Allow user to update database with `-u now` option without having to specify directory and several small fixes

setup.py
Fixes two of the three issues mentioned in #808
=> Update setup script dependencies and package data

cve_bin_tool/extractor.py, test/test_data/openssl.py, test/test_extractor.py
Note: It wheel only scan compiled C/C++ extension file because cve-bin-tool only support binary file scan.
=> Extractor: Added support for wheel and egg archive

cve_bin_tool/cli.py, cve_bin_tool/cve_scanner.py, cve_bin_tool/cvedb.py, cve_bin_tool/egg_updater.py, requirements.txt, test/test_cli.py, test/utils.py
=> Quiet Mode should not generate any output

cve_bin_tool/version.py
Now we have changed the version to be 1.1 you might have also seen the tool specifying that `we recommend using the latest stable release` but we only want to specify that to those users who are behind the latest version. 
```console
INFO     cve_bin_tool.CVEDB - Updating CVE data. This will take a few minutes.                              cvedb.py:225
INFO     cve_bin_tool.CVEDB - Checking if there is a newer version.                                         cvedb.py:187
[18:34:04] INFO     cve_bin_tool - You are running version 1.1 of cve-bin-tool but the latest is 1.0!                 version.py:37
Alert: We recommend using the latest stable release.                                       
INFO     cve_bin_tool.CVEDB - Downloading CVE data... 
```
=> Updated the info msg in version checker

test/test_checkers.py
I just noticed commented leftover code. So, I thought to clean it and also convert unittest to pytest for consistency.
=> test_checker: remove unnecessary comments and use pytest instead of unittest

.gitignore, cve_bin_tool/cve_scanner.py, cve_bin_tool/linkify.py, cve_bin_tool/log.py, cve_bin_tool/output_engine/console.py, cve_bin_tool/theme.py, requirements.txt, test/test_output_engine.py
Hi, 
I'm the author of Rich. I noticed you've used Rich to great effect, and I thought I could suggest some other things you could do with it.
Main change is a function to turn CVE references in to links that go to https://cve.mitre.org. So for terminals that support links a click (or cmd+click) on the CVE will jump straight to the appropriate page.
I've also made some changes to the found CVE references that were written in the logs. I find it a little easier to read this way...
=> linkify CVEs

cve_bin_tool/output_engine/html.py, cve_bin_tool/output_engine/util.py
Changes
------------
Added Docstring for `output_engine/html.py -> render_cves` and `output_engine/util.py -> group_cve_by_remark`. I had previously added those but I think Niraj's PR has removed that. So Pushing it again.
=> Docstring update for render_cves and group_cve_by_remark

test/test_util.py
Since, CVEScanner is the glue that interact with both InputEngine and OutputEngine if it's signature changes it can break whole build. Since it has happened previously, it would be nice to throw an error if someone change signature of this critical part.
=> Produce error if signature of cve_scanner change

cve_bin_tool/cli.py, cve_bin_tool/util.py, cve_bin_tool/version_scanner.py, test/test_cli.py, test/test_config.py
Closes #819 
In reference to:  #874 
@Niraj-Kamdar
=> add -e --exclude arument for excluding path 

README.md, doc/how_to_guides/cve_scanner_gh_action.yml, doc/how_to_guides/github_action.md
I have tested it on my github repo: https://github.com/Niraj-Kamdar/qpt_generator/actions/runs/219903197
I also want to submit this action for [github action hackathon  by dev.to](https://dev.to/devteam/announcing-the-github-actions-hackathon-on-dev-3ljn). Is it okay?
Fixes: #272
=> Added example yml to run CVE Binary Tool in github actions

doc/multiple_scans_at_once.md
This should wrap up addressing the issue in #821 by making best practices more explicit.  We might want to just incorporate this one into the manual, but this seems like enough of a frequently asked question that a guide might be easier to find.
=> Add how to doc on running multiple copies of cve-bin-tool

cve_bin_tool/async_utils.py, cve_bin_tool/cli.py, cve_bin_tool/cve_scanner.py, cve_bin_tool/cvedb.py, cve_bin_tool/egg_updater.py, cve_bin_tool/output_engine/html.py, test/test_cli.py, test/test_data/icecast.py, test/test_json.py
=> cvedb will scrap data now

README.md
The link to the user manual in the README.md file is not working
=> Fixed link to user manual in README.md

cve_bin_tool/cvedb.py, test/test_cvedb.py
We previously left this out. Without trust_env=True aiohttp won't pick
up proxy environment variables.
Fixes: #922
=> cvedb: Create aiohttp ClientSession with trust_env=True

test/test_extractor.py
Per #936, I'm disabling the CAB extraction test in github actions, because there seems to be a problem with fetching the URL.
=> Skipping CAB extract test in GitHub Actions

cve_bin_tool/cvedb.py
The builds have been timing out since #902 was merged.  I susect the problem is that the indexing as moved to happen after the database was populated, so this moves it back to where it was before (created immediately after the tables are created).
=> Move indexing back to init for performance

README.md
The URL should go to the issue page instead of the main page.
=> Updated URL to issue page

doc/CONTRIBUTORS.md
Fixed some spelling mistakes.
Sorry for the many Pull requests.  As I'm new to opensource don't know much about Github.
=> Fixed some typos in CONTRIBUTORS.md

doc/MANUAL.md, doc/conf.py, doc/how_to_guides/customize_html_report.md, doc/how_to_guides/index.rst, doc/how_to_guides/offline.md, doc/index.rst, doc/requirements.txt
* Improved titles in how to documents
* linked offline how to
* removed links to older documentation (the old docs remain in tree, but won't be picked up by readthedocs unless I push tags for them)
=> Small doc fixes in prepration for 2.0

doc/MANUAL.md
The problem was the Table was getting merged with the `<p>` tag in the above line. I added a simple space between them.
=> Fixed Table in --input-file section on readthedocs

doc/CONTRIBUTORS.md
* Add imposter syndrome disclaimer (thanks @Niraj-Kamdar for suggesting this!)
* Improve flow (so people get told about virtualenvs, tests, and black before trying to push a PR)
* Add instructions for building documentation
* Fill in basic info on tests, virtualenv
=> Improve new contributor documentation

doc/MANUAL.md
This is meant to partially address #957 by pulling the configuration examples (which are reasonably self-documenting through comments) into the MANUAL.md file.  I think we could probably do more, but this should be sufficient for the 2.0 release.
=> Include config file examples, fix linter issues

doc/MANUAL.md
As mentioned in #982 the hyperlinks for MANUAL.md weren't working.
This was happening as the way Markdown handles hyperlink is different in comparison to sphinx. I have updated all the links for this page(file).
=> intradocument hyperlinks in docs/MANUAL.md updated

cve_bin_tool/output_engine/html.py, cve_bin_tool/output_engine/print_mode.py
Reverts intel/cve-bin-tool#967
This causes issues in report generation, so we're reverting the change for now and can re-evaluate if this is worth using in the future.
Fixes #988
=> Revert "Enable jinja2 autoescape"

.github/workflows/pythonapp.yml
Github Actions changed the way they handle environment variables last week; this updates our .yml file to use the new preferred style.
=> New Github Actions environment variables

cve_bin_tool/checkers/gcc.py, cve_bin_tool/checkers/zlib.py, test/test_data/avahi.py, test/test_data/bind.py, test/test_data/bzip2.py, test/test_data/expat.py, test/test_data/gcc.py, test/test_data/glibc.py, test/test_data/gstreamer.py, test/test_data/haproxy.py, test/test_data/international_components_for_unicode.py, test/test_data/lighttpd.py, test/test_data/memcached.py, test/test_data/netpbm.py, test/test_data/openswan.py, test/test_data/png.py, test/test_data/qt.py, test/test_data/systemd.py, test/test_data/wireshark.py, test/test_data/xerces.py, test/test_data/xml2.py, test/test_data/zlib.py, test/test_scanner.py
Centos 6 support has ended and the mirrors are no longer showing those files. This PR updates the tests to use newer versions of centos when available, and updates some other centos packages in 7 and 8 to the current available packages.
It also updates other tests where the files were previously not available.
OpenSwan no longer seems to be included in centos, so that test has been removed entirely.  We may wish to replace it, or consider making a checker for whatever replaced OpenSwan (ipsec or freeswan, maybe?)
Also updated the zlib checker because it was no longer working on more modern files.
=> Update tests previously using centos 6 or otheriwise out of date

MANIFEST.in, cve_bin_tool/extractor.py, requirements.txt, setup.py, test/test_extractor.py
Using rpmfile PyPi library we can extract rpm files if rpm2cpio and cpio
are not present.
=> extractor: Native Python support for rpm files

.pre-commit-config.yaml
This isn't a perfect solution to #909, because I think I should probably change the github action to match, but it *should* resolve issues for folk using the pre-commit hook and getting conflicts with what's in Github Actions for now.
=> Specify black version in pre-commit config

test/test_data/samba.py
As there is a change in the test URL. The test is failing.
=> Updated Samba checker test URL

cve_bin_tool/checkers/__init__.py, cve_bin_tool/error_handler.py
The test fails when the `VENDOR_PRODUCT` pairs provided is not lowercase. ( #987 )
=> Test fails if any VENDOR_PRODUCT pair in checker is not lowercase

cve_bin_tool/checkers/README.md
There is only one relative import in the documentation. 
Fixes #1064
=> Fix relative import in docs

cve_bin_tool/checkers/mysql.py, test/test_data/mysql.py
mysql checker was recognizing version syntax 8.0.20 as 8.0.8.0.20. Currently we are only recognising the pattern 
`mysql\-([0-9]+\.[0-9]+\-[0-9]+\.[0-9]+\.[0-9]+)`
These changes will give us the exact version
This will close #954
=> mysql version pattern bug

README.md
For some reason, the README file recommends running cve-bin-tool without specifying a directory.   Although this *will* just print the help, I think it's better if people know they have to scan something to get it to work.
=> Add directory to instructions, update master->main in badges/links

cve_bin_tool/checkers/README.md, doc/CONTRIBUTORS.md, doc/CSV2CVE.md, doc/MANUAL.md, test/README.md
Looks like GitHub does redirects, but during my first misinterpretation of the PR on the README i just reviewed I thought the goal was to change all the references. So these should be the rest of the references to `master` branch, except for in the docs where I didn't change the links in the old versions of the `.md` files. We should probably update those to point to their respective versions come to think of it... but low priority.
=> Rename master to main in various docs

cve_bin_tool/cvedb.py
Workaround for issue #1081. 
Limits max concurrent connections for downloading the CVE tarballs to two at a time. 
Moves non-response related code out of the async block to avoid holding a semaphore permit unnecessarily.
=> Add rate limiting to address #1081

cve_bin_tool/cvedb.py, test/test_cvedb.py
Pull request by @param211  #1091 can be an alternate solution for #1081.
But I manually tried limiting connections to NVD. And it seems like NVD allows a maximum limit of 20 per host.
```
connector = aiohttp.TCPConnector(limit_per_host=19)
self.session = aiohttp.ClientSession(connector=connector, trust_env=True)
```
This worked for me every time.
I am just putting it here as a feasible solution @terriko 
Also, the only files I changed is cvedb.py and test_cvedb.py (Other changes are related to isort)
=> Limit aiohttp simultaneously opened connections to NVD

test/utils.py
The original URL's SSL certificate isn't functioning properly. (NET::ERR_CERT_DATE_INVALID). 
Temporarily changed it to use HTTP instead of HTTPS.
original URL: https://mirrors.cat.pdx.edu/ubuntu/pool/main/t/tmux/
temp URL: http://mirrors.cat.pdx.edu/ubuntu/pool/main/t/tmux/
=> Temporary fix for ssl certificate error

cve_bin_tool/cve_scanner.py
Fixes #990 
OpenSSL sometimes has version strings with two trailing letters (eg 0.9.8.zc). Modified `openssl_convert` to handle this. 
Also added this conversion to `parse_version` if product is OpenSSL.
=> Fix OpenSSL version conversion

README.md, doc/0.3.1/README.md
A link in the documentation pointing to "Instructions on how to add  a new checker" was broken.
=> Updated a Link in README.md

test/utils.py
I think its best practice to switch it back to https now that the pdx.edu site's SSL certificate is renewed
=> Switch PDX url to https #1104

cve_bin_tool/version.py
This completes the  TODO of mark the 'Update to latest stable version' with some colour.
Please tell me if the colors are not stylistically consistent with the project.
=> Add color to latest version message

.github/workflows/pythonapp.yml
[technote-space/get-diff-action](https://github.com/technote-space/get-diff-action) changed syntax (somewhere between v1 and v4) so when it was updated to v4 in 5944c8ec9489f252841d2bc043ae080877dc71c5 filtering was lost and long tests started to run on every change.
This PR updates workflow to use PATTERNS/FILES options instead.
=> Fix long tests in CI

.github/workflows/pythonapp.yml, test/test_condensed_downloads.py
Closes #1059 
I've added a simple test to check if the condensed downloads are commited according to the `package_test_data` specified in the `test_data` of respective checkers
=> Add condensed downloads test

cve_bin_tool/output_engine/__init__.py, cve_bin_tool/output_engine/pdfbuilder.py
Closes #1151 
Sample PDF:
[output.cve-bin-tool.2021-05-08.11-49-29.pdf](https://github.com/intel/cve-bin-tool/files/6445338/output.cve-bin-tool.2021-05-08.11-49-29.pdf)
pinging @anthonyharrison to take a look since I just followed the pattern in the file to add UNKNOWN severity.
=> Handle UNKNOWN severity in PDF reports

.github/workflows/pythonapp.yml
This is to allow manual runs on a branch. It is helpful when we suspect something external might be breaking tests, like in #1147.
Also gives the option to run long tests if desired.
=> Add manual trigger for CI workflow

cve_bin_tool/checkers/python.py
Fixes wrong detection of newer python2.7 versions
The version pattern of the current checker does not consider python versions
with more than a single digit in the third block of the version string.
Since the latest version of Python 2.7 is 2.7.18, this is falsely reported as
2.7.1.
=> Fix Python Checker

cve_bin_tool/cvedb.py, cve_bin_tool/error_handler.py
Just a small PR that will give better readable errors when the user is ratelimited and also raise on error wherever a request happens , Sorry if I did it wrong. Please CR and tell me any feedback 
Regards.
=> Raise ratelimit user friendly and other network errors. #1109

cve_bin_tool/checkers/sqlite.py, cve_bin_tool/cvedb.py, cve_bin_tool/error_handler.py, cve_bin_tool/extractor.py, cve_bin_tool/file.py, cve_bin_tool/output_engine/console.py, cve_bin_tool/util.py, cve_bin_tool/version_scanner.py, cve_bin_tool/version_signature.py, test/test_checkers.py, test/test_cli.py, test/test_extractor.py, test/test_file.py, test/test_json.py, test/test_output_engine.py, test/test_scanner.py, test/test_strings.py, test/test_util.py, test/utils.py
The [cvedb.py](https://github.com/intel/cve-bin-tool/tree/main/cve_bin_tool/cvedb.py) file has isort issues and made all CI checks fail and also while working on a PR I ran black on the entire directory and found that black formatted 19 files (had to restore files one by one since my work was uncommited).
=> Format files using isort and black

.github/workflows/pythonapp.yml, .pre-commit-config.yaml, cve_bin_tool/checkers/__init__.py, cve_bin_tool/cli.py, cve_bin_tool/config.py, cve_bin_tool/cve_scanner.py, cve_bin_tool/cvedb.py, cve_bin_tool/extractor.py, cve_bin_tool/version_signature.py, doc/conf.py, setup.py, test/test_extractor.py
This is intended to close #642
First commit is just the result of running [pyupgrade](https://github.com/asottile/pyupgrade) with `--py36-plus` flag.
What it did:
- [`.encode()` to bytes literals](https://github.com/asottile/pyupgrade#encode-to-bytes-literals)
- [`super()` calls](https://github.com/asottile/pyupgrade#super-calls)
- Our favorite [f-strings](https://github.com/asottile/pyupgrade#f-strings)
- [Redundant `open` modes](https://github.com/asottile/pyupgrade#redundant-open-modes), in our case it's only `"r"`
- [Unnecessary py3-compat imports](https://github.com/asottile/pyupgrade#remove-unnecessary-py3-compat-imports), in our case it's `from io import open`
- [Generator expressions for some built-in functions](https://github.com/asottile/pyupgrade#generator-expressions-for-some-b …
=> Python 2 cleanup

test/test_condensed_downloads.py
While working on #1165 I noticed that improper decoding of stdout could cause problems in different platforms (had issues on windows). Instead of splitting the string for parsing of the stdout it is properly decoded now.
=> Proper decoding of stdout in condensed download committed or not test

cve_bin_tool/cli.py, cve_bin_tool/cvedb.py, test/test_output_engine.py
There was a mismatch in the way `datetime` was imported in c6d71c6d335ec57972ca58544de9c2cc22183ba4 and 585e578bbe5216366daf081510b9f9d3eaee7609 in the `test_output_engine.py` file leading to failing tests
=> Fix  Tests

cve_bin_tool/checkers/README.md, cve_bin_tool/version_scanner.py
This PR would enable support for python package checkers that only have version strings present in PKG-INFO or METADATA files.
=> Add support for python package checkers

cve_bin_tool/error_handler.py, cve_bin_tool/package_list_parser/__init__.py, cve_bin_tool/package_list_parser/vendor_fetch.py, test/test_package_list_parser.py, test/txt/test_broken_ubuntu_list.txt, test/txt/test_ubuntu_list.txt
=> Ubuntu package list parser

cve_bin_tool/checkers/python.py
=> Remove regex that was catching false positive versions in python checker

cve_bin_tool/cli.py, cve_bin_tool/cvedb.py, test/test_cli.py
BREAKING CHANGE: When NVD scraping fails or a timeout occurs, sometimes the user is left with no database to work with. We can avoid this by creating a temporary local backup and rolling it back in case something fails.
=> feat (cvedb): rollback cachedir if cvedb refresh fails

README.md, cve_bin_tool/package_list_parser/__init__.py, doc/MANUAL.md
=> feat(package-list-parser): Add support for distros using pacman package manager

bandit.conf, cve_bin_tool/checkers/sqlite.py, cve_bin_tool/version.py
This sets a default bandit config (ignoring the subprocess rules) and a few '# nosec' flags for places where we've audited the url loads and do not need to inspect them again.
=> fix(security): Bandit config and nosec flags for reviewed code

cve_bin_tool/version_signature.py
* improves version_signature.py to align with bandit's guidance
* fixes #1229
You can't use bound parameters for things like table names that aren't technically parameters in sqlite3, but Bandit throws errors due to the string construction in queries.  Added some basic input validation into the init function and marked lines for Bandit.  Because bandit doesn't deal well with multi-lines with `nosec` comments, I've added descriptive comments to some select statements instead of the `# nosec` line that would make the line disappear from future runs of Bandit.
=> fix(security): Improve SQL in version_signature.py

test/test_checkers.py
* fixes #708
This should prevent instances where checker tests fail after a new checker is added.
=> fix: add update_egg function to test_checker

test/test_helper_script.py
this should close #1254 
While iterating over helperscript, I updated the `parse_filename()` to return both product and version, but forgot to update the tests for it :(
=> fix: tests for test_helper_script

test/README.md
=> docs: remove adding checker names for tests

.github/workflows/pythonapp.yml
fixes: #1159
This switches the way we're running tests so that it does a full pytest gather for the async tests (minus a few files known to cause rate limiting issues). This will run a few tests that were not previously being run, and will help us so that new test files no longer need to be added manually to CI before they will run.
=> test: change way pytest is run in CI

cve_bin_tool/checkers/__init__.py, cve_bin_tool/checkers/glibc.py, cve_bin_tool/checkers/libdb.py, cve_bin_tool/checkers/sqlite.py, cve_bin_tool/checkers/systemd.py, cve_bin_tool/checkers/xml2.py, cve_bin_tool/strings.py, cve_bin_tool/util.py, cve_bin_tool/version_scanner.py, test/test_checkers.py
~~Attemp to add multiline regex support for #1200 and possibly other checkers which may need multiline regex.~~
The strings obtained by scanning the binaries are further splitted and iterated to scan for versions in our tool using regex. Instead of splitting the lines we could directly employ regex to find the version in the string which will increase the performance by a lot.
Benchmark: https://github.com/intel/cve-bin-tool/pull/1227#issuecomment-881434989
=> refactor(scanner): scan strings without splitting the lines

cve_bin_tool/async_utils.py, cve_bin_tool/extractor.py, test/test_strings.py
=> fix: extract apk packages for alpine and android

.github/workflows/pythonapp.yml, dev-recommended.txt, requirements.csv, requirements.txt
This adds what is basically requirements.txt file for developers, including the specific version of black that we're currently using and pre-commit (which will help you run black and isort)
We may want to move isort into this list, since I believe it's also only needed for developers.
=> feat: Add recommdended dev tools list

cve_bin_tool/helper_script.py, cve_bin_tool/version_scanner.py
I've been trying to refactor this, but it keeps throwing me this error. I tried calling it `version_scanner.py` and it works fine,  but calling it in `helper_script.py` returns me this error: 
```
Downloads via (venv39_CVE_Binary_tool)
➜ python3 /mnt/d/git_stuff/cve-bin-tool/cve_bin_tool/helper_script.py libmatroska-1.5.0-1.el8.x86_64.rpm
Traceback (most recent call last):
File "/mnt/d/git_stuff/cve-bin-tool/cve_bin_tool/helper_script.py", line 70, in extract_and_parse_file
self.logger.warning(VersionScanner.is_executable(filepath))
AttributeError: type object 'VersionScanner' has no attribute 'is_executable'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/mnt/d/git_stuff/cve-bin-tool/cve_bin_tool/helper_script.py", line 324, …
```
=> refactor: helper script for is_executable() and parse_string()

cve_bin_tool/cvedb.py
=> fix(cvedb): skip reject cve entries

cve_bin_tool/async_utils.py, cve_bin_tool/extractor.py, test/test_async_utils.py, test/test_cli.py, test/test_extractor.py
* fixes #1281
* Related to #1181 
Changes in #1181 to check return codes made it so that cve-bin-tool failed if any file did not extract correctly. 
This changes the default so that failures during extraction are logged but do not halt the scan.  Error messages are not logged when the file extension is .exe because users found those confusing (cve-bin-tool tries to unzip all .exe files in case they are self-extracting zipfiles, but many are not)
=> fix: allow extractraction on all files to fail

cve_bin_tool/version_scanner.py
=> fix(scanner): crash when scanning a METADATA file w/o appropriate data

.github/workflows/pythonapp.yml, .isort.cfg, .pre-commit-config.yaml, cve_bin_tool/checkers/systemd.py, dev-requirements.txt, setup.cfg
Fixes #1276
1. GitHub workflow was changed a bit, instead of another job running flake8 through pre-commit I have created a matrix linting job that will run all tools. It looks pretty!
[Link to run](https://github.com/Molkree/cve-bin-tool/actions/runs/1088163557)
2. I've added flake8 to dev-requirements.txt unpinned. The only pinned tool there is Black, if needed I can pin to the same version as in the pre-commit config.
3. I've put both isort and flake8 configs in setup.cfg even though isort "prefers" .isort.cfg->pyproject.toml->setup.cfg. Unfortunately, flake8 doesn't support pyproject.toml and I didn't want to split configs into two files so we are stuck with "old" setup.cfg. I can change it if desired.
P.S. Note about isort: in #1146 I have added dependencies installation per GitHub …
=> ci: add flake8 to CI

test/test_nvd_api.py
This fixes the current linting errors from flake8 and black.  (Caused because of PRs merged before the updated CI rules went through.)
=> lint: remove unused BeautifulSoup import, fix black

cve_bin_tool/cve_scanner.py, cve_bin_tool/cvedb.py, cve_bin_tool/version.py, cve_bin_tool/version_scanner.py, test/test_cli.py
Fix #1293 
I have covered the contents in the issue and I'm now looking for other improvements.
=> refactor(logger): Make logger less verbose

cve_bin_tool/version.py
The 3.0 release is planned for after Google Summer of Code winds down in September, this bump reflects that the current main branch will eventually become the 3.0 release.
=> chore: Update dev version to 3.0.dev0

.github/workflows/update-pre-commit.yml
Per @terriko https://github.com/intel/cve-bin-tool/pull/1260#issuecomment-884447289:
> I can't authorize pre-commit.ci for this repo because it's managed by Intel, so let's focus on getting things working in github actions as is for now.
If pre-commit.ci is not an option (yet?), this workflow can be used to autoupdate pre-commit config.
Here is an [example](https://github.com/Molkree/cve-bin-tool/pull/9) of generated PR.
The body of the PR can be tweaked as well, just don't know if you want something more meaningful.
P.S. If pre-commit hooks will be kept up to date with this workflow it would probably make more sense to unpin Black in `dev-requirements.txt`
https://github.com/intel/cve-bin-tool/blob/281cd76bb67540c4beadf7d46fd1db0b4638c517/dev-requirements.txt#L1
=> ci: autoupdate pre-commit config

test/test_extractor.py
Additional test_bad_* added. (fix #1305)
=> test: add additional bad archive tests

test/test_extractor.py
fix #1325
Used global `BAD_FILE` dictionary to reduce the number of variables (`BAD_*_FILE`)
=> refactor: bad archive file tests

test/test_nvd_api.py
This will fix failing NVD REST API tests.
=> fix(nvd_api): nvd_api fetch results over 2000 limit

test/test_cli.py, test/test_extractor.py
Fixes:
- #1331
I've added `test_bad_files` function in the `TestExtractorBase` class + fixture with extensions. Fixture just uses all supported extensions returned by `extractor.file_extractors[self.extractor.extract_file_type]` and not manually entered by us. I have removed empty files from assets folder and instead create them during tests just like in other extractor tests.
I don't know if there is a way to not run this function in the base class, maybe this whole refactoring can be done differently but for now base class also runs the test:
Because I've removed all asset empty files, I also had to fix `test_extract_bad_zip_messages` CLI test.
`TestExtractor` class was removed as it is pointless by now, all extensions are being tested on real files.
Unrelated to the bad files testing …
=> test(extractor): refactor bad files

setup.py
I think Python 3.9 is officially supported now since it's being explicitly tested in CI.
=> docs: add Python 3.9 classifier

cve_bin_tool/cli.py
We can detect backported fixes on Debian based distros now.
=> chore: change comment about not detecting backported fixes

test/test_package_list_parser.py
=> fix: bump binutils to v2.34-6ubuntu1.3 in package list parser test

.github/workflows/pythonapp.yml, test/test_json.py
* Related to #1438
Due to occasional mistakes in the NVD data, the jsonschema tests are
flaky and have been making our CI results less useful.
Also fixed a whitespace issue in pythonapp.yml
=> test: mark jsonschema tests as xfail

.github/workflows/pythonapp.yml
* related: #1438
The json schema tests are flaky because NVD sometimes provides
non-compliant data.  Currently the 2021 yearly file does not pass.
Users wishing to run these checks can still do so locally, but the value
of running failing tests in CI seems minimal so they're being disabled.
=> CI: disable jsonschema tests due to NVD data errors

cve_bin_tool/available_fix/redhat_cve_tracker.py, test/test_available_fix.py
fix #1444 
Instead of the previous approach of looking for affected versions  and logging the upstream fixes all together now we will use the `affected_release` to find if the package has fixes.
refer https://github.com/intel/cve-bin-tool/issues/1444#issuecomment-974786177 and https://github.com/intel/cve-bin-tool/issues/1444#issuecomment-974790541
=> fix(available-fix): Use `affected_release` for fixed status

cve_bin_tool/cli.py, cve_bin_tool/error_handler.py, test/test_cli.py
* fixes #1135
Previously, cve-bin-tool returned the number of CVEs found, or negative
numbers for error codes.  Because error codes are expected to be in the
range 0-127 that could cause unexpected behaviours (particularly on
Windows) so this PR changes our error codes to be positive values.
error code 1 is reserved to indicate the cves were found
error codes 2+ indicate operational errors.
Signed-off-by: Terri Oda <terri@toybox.ca>
BREAKING CHANGE: Error codes
=> fix!: Make error codes fit standard range

.github/actions/spelling/allow.txt, README.md
I've started filling out the OpenSSF Badge (formerly known as the CII best practices badge).  It's intended to show that we're following security best practices.  It's not done yet, but I think it might be nice to show that it's in progress.
=> OpenSSF Badge (in progress)

cve_bin_tool/package_list_parser.py
This is an unused code left over from #1194
=> refactor(package-list-parser): remove csv path

.github/workflows/spelling.yml
Fixes #1470 
Changed spelling.yml, fulfilling all requirements of the issue.
=> Updated spelling.yml

.github/actions/spelling/allow.txt
I somehow missed this in the last commit.
=> ci: add filetype to allowed word list

.github/workflows/pythonapp.yml, .pre-commit-config.yaml, cve_bin_tool/package_list_parser.py, doc/MANUAL.md, setup.py
=> feat: Remove support for python 3.6 (#1488)

.github/actions/spelling/allow.txt, README.md
=> chore: added LGTM badges to readme (#1380)

test/test_cvedb.py
=> test: Move NVD queries to LONG_TESTS due to rate limits (fixes #1509)

.gitattributes
Our HTML templates and test files are currently dominating our language results
because they're so big, but most of our development is actually done in Python.
We are suppressing html detection to get a better picture for contributors.
=> chore: modify detected languages in github

README.md
Gave output types its own subheading in README.md
Fixes #1506
=> Gave output types its own subheading

test/test_available_fix.py
=> test: Move backported fix tests to LONG_TESTS (#1502)

README.md
Moved --offline up to "Most popular usage options" section in README.md
Fixes #1505
=> Moved --offline up to "Most popular usage options"

cve_bin_tool/cve_scanner.py
- fixes #1518
Regression was introduced in 6cd49cf, first `if` clause returns a tuple of two strings instead of special `Version` objects. This only happens when `product_info.version` is an empty string.
Note that this also affects #1517 ([user report](https://github.com/intel/cve-bin-tool/issues/1300#issuecomment-1008291338)). With the proposed fix scanning completes successfully and just detects empty version for xml2:
```console
INFO     cve_bin_tool - Known CVEs in ('busybox', '1.30.1'), ('curl', '7.66.0'), ('hostapd', '2.9'), ('libcurl', '7.66.0'), ('libxml2', ''), ('lighttpd', '1.4.48'), ('lua', '5.1.5'),      cli.py:565
('openssl', '1.1.1d'), ('openvpn', '2.5.0'), ('sqlite', '3.31.1'), ('wpa_supplicant', '2.9'):
```
P.S. I can't seem to pass all tests in CI in my fork due to NVD …
=> fix(cve_scanner): fix `canonical_convert`

CONTRIBUTING.md, README.md, doc/1.0/RELEASE.md, doc/RELEASE.md
[Original Issue Link](https://github.com/intel/cve-bin-tool/issues/1531)
- Replaced "Github" with "GitHub"
=> Replace "Github" with "GitHub"

.github/workflows/pythonapp.yml, README.md, cve_bin_tool/cli.py, cve_bin_tool/cvedb.py, cve_bin_tool/nvd_api.py, doc/MANUAL.md
This PR will add support for NVD API keys
* fixes #1428
This includes the following:
- adding the NVD notice as required by the NVD API docs
- adding `--nvd-api-key` to the command line
- modifying CVEDB to accept the api key and pass it through to NVD_API
- modifying NVD_API to accept and use the api key by adding it to the parameters sent with the request.
- documentation on how to get and use an api key
- accepting an $nvd_api_key environment variable as alternative to using the command-line flag.  This allows users of GitHub Actions (including us!) to use their built-in secrets options to keep the key private in the CI logs.
- enabled the nvd_api_key in our GitHub Actions setup -- this allows the long tests to pass without being rate limited
=> feat: add NVD API key

.github/workflows/pythonapp.yml
The NVD_API_KEY changes I pushed in #1529 didn't work correctly in github actions.  This PR reverts just the CI part of the patch.
A better fix is coming in #1543 but right now it looks like NVD isn't recognizing the key passed through github secrets.  This PR should just be a stand-in until I figure out how to plumb the secret variable through correctly.
=> ci: remove NVD_API_KEY from CI because it isn't working

test/README.md
Update test/README.md so it shows the correct versions of Python
Fixes #1510
=> Updated so it shows the correct versions of Python

test/README.md
I merged #1515 before we fully fixed the issue with the pdttotext instructions (oops) so this is a partial revert so that the instructions are still there, but updated to indicate that pdftotext is only needed if you intend to run the pdf tests.
=> doc: keep pdftotext windows install instructions (partial revert #1515)

.github/actions/spelling/allow.txt, CONTRIBUTING.md
Adding some information for common problems first time contributors have:
- keeping their `main` branch in sync with `origin/main` . Previously we said it was a good idea but didn't include info on what to do if you accidentally commit to that branch)
- rebasing to `origin/main`.  Just saying that it comes up sometimes in code review and giving a link to a more extensive document on what git rebase means.
=> doc: add info on syncing to origin/main and rebasing

cve_bin_tool/available_fix/debian_cve_tracker.py, requirements.csv, requirements.txt, test/test_available_fix.py
=> test(available-fix): mock cve data

cve_bin_tool/util.py
part of #1539 
Most of the file already had type hints. 
@terriko I did not use ClassVar for class variables as it wasn't already used, Should I add it?
=> refactor: add type hints in util.py

.github/actions/spelling/allow.txt, .github/workflows/linting.yml, .gitlint, .pre-commit-config.yaml, CONTRIBUTING.md, dev-requirements.txt
=> ci(pre-commit): add gitlint

.github/workflows/formatting.yml, .github/workflows/linting.yml, .pre-commit-config.yaml, CONTRIBUTING.md, cve_bin_tool/checkers/README.md
closes #1582 
format_checker no longer runs as a linting check and in pre-commit.
A pull request is created with updated checkers table when a new checker is merged.
=> ci: switch format_checker to run in ci

setup.cfg
=> fix: asyncio warnings (#1558)

cve_bin_tool/egg_updater.py
=> fix: add dynamic version to egg_updater.py

cve_bin_tool/egg_updater.py, setup.cfg, setup.py
* fixes #1623 
(Well, maybe, I'm letting CI try it out because it didn't trigger for me locally)
=> fix: add explicit setuptools package config

cve_bin_tool/version_scanner.py
Add some additional None checks to run_java_checker.
=> fix: add None checks to run_java_checker

README.md
We have the caveat about offline mode in the limitations section, but I wanted to make it more clear.  Also I didn't want it top of the list of most used options because that didn't make sense to me.
=> docs: add link to offline guide, rearrange order

test/test_cli.py
Simple test to make sure that null bytes are handled correctly in filenames specified on the command line.
This is a kind of useless attack in practice for cve-bin-tool: you can only scan files you already have access to on the system so there's not much point in trying to disguise a file with a null byte.  But since it's a relatively small test to prove that this isn't an issue for security compliance reasons, I'm just going to go ahead and add it.
=> test: add test for null byte in filename

cve_bin_tool/egg_updater.py
Found a flaw in the installed 3.1rc2 package: egg_updater was failing because it was trying to get the version incorrectly.  This might not be the best possible fix (we could maybe make sure this code doesn't get loaded for installed packages) but this does the trick for now.
=> fix: fix egg_updater for installed packages

cve_bin_tool/version_scanner.py
Static analysis says we can still sometimes wind up with version set to None in the java version parser.  Set it explicitly to "UNKNOWN" to match the other checkers.
cc @anthonyharrison who might want to review this
=> fix: Default to UNKNOWN in java version checker

cve_bin_tool/output_engine/__init__.py, test/test_output_engine.py
I've added some basic excel macro prevention to the csv output. That means trimming leading special characters (+, -, =, @) used by excel for formulae.
Honestly, it's a bit unlikely that anyone would manage to put an excel macro into the NVD data, but it *is* possible that folk might share triage with intentional or unintentional comments that parse as macros.  Either way, there's no reason for us to allow these characters in output so we might as well add the filter for additional safety.
=> fix: add excel macro filter for csv output

cve_bin_tool/egg_updater.py, cve_bin_tool/version.py
Error report on the new 3.1 package -- apparently we missed a typo in the egg_updater code.
=> fix: typo fix + version bump

cve_bin_tool/cve_scanner.py
addresses #1639
re.search returns `None` on failure, updating to indicate the version is
`UNKNOWN` when this occurs and generating a log message
I noted as well that there are other places in the code where this is unchecked, but it doesn't look like they could normally fail, but this should specifically fix #1639. 
Checklist
----
Have I checked on the results from GitHub Actions?
Please feel free to make any recommendations / suggestions for improvement as this is my first PR to your project.
=> fix: check return on re.search

cve_bin_tool/cvedb.py
=> fix: broken quiet mode in main branch (#1587)

cve_bin_tool/cli.py
=> fix: add debug statement if checkers didn't load (#1440)

.github/actions/spelling/allow.txt, fuzz/Readme.md, fuzz/fuzz-requirements.txt, fuzz/fuzz_main.py
I'm working on some initial exploration into fuzzing cve-bin-tool using the Atheris fuzzer from Google.  This looks like it handles instrumentation of python code and then hooks up libfuzzer.
Fuzzing (for those not familiar) involves sending potentially large amounts of "bad" data into a program and seeing how it responds.  It's regularly used for security and validation to find crashes and potential security holes.  Since we've never done it on cve-bin-tool before I expect we'll find a lot of crashes.  Doing fuzzing can potentially damage data on your system, so I recommend you do this within a vm, docker container, or have some other way of sandboxing the tool.  (Note that virtualenv won't work for this; it does not provide the protections needed.)
=> test: Add Atheris fuzzing setup for cve-bin-tool

requirements.csv, requirements.txt
urllib3 is used by requests.  It had some CVEs last year (and before).  Pip tends to be very conservative about upgrading packages and requests doesn't require a non-vulnerable version of the library, so I'm adding it to our requirements.txt file in order to force an upgrade for users of cve-bin-tool. 
Probably not necessary, as these fixes have been out quite some time, but I happened upon a machine I was using for testing that had the older version, and figured I might as well set this up as a courtesy in case anyone else encounters a similar issue.   This way, when you run `pip install --upgrade -r requirements.txt` urllib3 will be explicitly named and upgraded.  (Without this line, upgrading the other packages would not upgrade urllib3.)
=> fix: add urllib3 explicitly to avoid CVEs

cve_bin_tool/output_engine/__init__.py
=> fix: broken test_console_output_depending_reportlab_existence (#1675)

test/test_package_list_parser.py, test/txt/test_requirements.txt
=> chore(deps): bump html5lib from 0.99 to 0.99999999 (#1686)

cve_bin_tool/checkers/radare2.py
Added contains patterns which included in current RPM, DEB, and git repository binaries from stable versions (checked from 5.4.0 to 5.6.8)
related to [this issue](https://github.com/intel/cve-bin-tool/issues/1349)
=> feat: add radare2 contains patterns

cve_bin_tool/output_engine/__init__.py, test/test_output_engine.py
- Fixed #1691 by replace the depreciated `warn` method with `warning`.
- Fixed the ResourceWarning in `test_output_vex` test. The following warning was printed because the test file was only being opened in default 'r' mode but was never closed. 
The test was run using `python3 setup.py test`
```
test_output_vex (test.test_output_engine.TestOutputEngine)
Test creating VEX formatted file ... /workspaces/cve-bin-tool/test/test_output_engine.py:685: ResourceWarning:
unclosed file <_io.TextIOWrapper name='test.vex' mode='r' encoding='UTF-8'>
```
=> fix: logger.warn() warning & test_output_vex test (#1691)

cve_bin_tool/extractor.py
=> refactor(extractor): Prioritize 7z while extracting pkg files in windows

cve_bin_tool/checkers/expat.py, cve_bin_tool/checkers/polarssl_fedora.py
As discussed in [this PR](https://github.com/intel/cve-bin-tool/issues/1349) contains patterns for polarssl fedora added.
There is also a small modification on docstring.
=> feat(checkers): Add polarssl fedora contains patterns

cve_bin_tool/extractor.py, test/test_cli.py, test/test_config.py, test/test_extractor.py, test/test_file.py, test/test_input_engine.py, test/test_json.py, test/test_language_scanner.py, test/test_merge.py, test/test_output_engine.py, test/test_package_list_parser.py, test/test_requirements.py, test/test_sbom.py, test/test_scanner.py, test/test_strings.py
=> refactor: use pathlib.Path instead of os.path

.github/workflows/cve_scan.yml, .github/workflows/formatting.yml, .github/workflows/linting.yml, .github/workflows/testing.yml, .github/workflows/update-pre-commit.yml, doc/how_to_guides/cve_scanner_gh_action.md, doc/how_to_guides/cve_scanner_gh_action.yml
`setup-python` Action had a breaking change with [v4 release](https://github.com/actions/setup-python/releases/tag/v4.0.0), it's now required to specify `python-version` or it defaults to the `python-version-file` and errors out if it can't find such file.
=> ci: bump `setup-python` version

cve_bin_tool/format_checkers.py, test/format_checkers/checkers.md, test/test_format_checker.py
=> test: added unit tests for format_checkers script

.github/dependabot.yml
This will keep the various GH Actions used in workflows up to date.
I set the interval to daily and not weekly/monthly but I believe it shouldn't create too much noise because:
- major versions of Actions are not updated too often (every few months) and we only pin to major version
- this doesn't produce any new runs in the Actions tab
We will just get pull requests sooner.
I recommend merging #1711 before this PR.
=> ci: use Dependabot to bump GitHub Actions

README.md
faced this error while i was following instructions from the readme
=> docs: fix file extension in package list scanning

test/test_csv2cve.py
=> test: unit tests for csv2cve.py

cve_bin_tool/cvedb.py
=> refactor: switch to pathlib.Path in cvedb.py

cve_bin_tool/cli.py
i noticed a spike in the number of failed CIs, so i investigated a little and found out if there is no cached db to use, it was failing to create a db during the run, so i just moved the block of code that was handling db related tasks before the block of code that was handling merging.
=> fix: update database before merging

.github/workflows/update-spdx-header.yml
=> ci: update year in spdx header automatically (#1753)

.github/actions/spelling/allow.txt, README.md, doc/MANUAL.md
For an unknown reason, the GitHub Action that creates the PR which runs `format_checkers.py` failed (see https://github.com/intel/cve-bin-tool/pull/1705) so fix it by running the script manually
=> fix: add luajit to documentation

.github/workflows/coverity.yml
Trying out the unofficial coverity github action to provide automated builds for scan.coverity.com static analysis.
=> ci: add scan.coverity.com workflow

.github/workflows/coverity.yml
Coverity is failing on main because it's trying to run "make" and it should be using `--no-command` to do a filesystem scan for python files.
=> ci: set coverity build command to --no-command

.github/workflows/testing.yml, doc/requirements.csv, test/test_cli.py, test/test_nvd_api.py, test/test_requirements.py
Two experiments to see if we can get CI back on track:
1. raising the timeout a bit to see if we're just a little over
2. changing the first call to look only at a single file in case we were getting hung up on the new .pkg file in test/assets.
=> ci: raise timeout and change first cli call

.github/workflows/testing.yml
I upped all our timeouts by 10 minutes yesterday to see if just a little more time would solve some tests, but it didn't help considerably so I'm reverting the change.
=> ci: reduce timeouts back to normal

cve_bin_tool/version_scanner.py, test/test_csv2cve.py
I merged two of the refactored package parsers without letting tests complete so of course one of them has a black error. This is a fix for that.
=> chore: fix black issues

.github/workflows/testing.yml
this could probably fix the ci, the long tests were not using the api method to get data from NVD, it was using the json method and the "Try single CLI run of tool" step was passing, so i just changed the method for all tests to use json method to fetch data from NVD.
#1811
=> fix(ci): use json method to get data from NVD

.github/workflows/testing.yml, .github/workflows/update-cache.yml
This will run everyday at 00:20, and first it will run the tool and update the database using the api method with the api key (it'll have access to the secrets because it will run on main branch), then it'll cache the updated database, so that all PRs can use the cached db and avoid updating for the rest of the day.
#1811
=> ci: update cached database

requirements.csv, requirements.txt
today the "Update Cached DB" CI failed due to dependency error: https://github.com/intel/cve-bin-tool/runs/7551314546?check_suite_focus=true#step:7:25
=> fix: update requirements

CONTRIBUTING.md, README.md
Adding some code of conduct info to the main readme and contributors documentation.
Folk participating in Google Summer of Code have always had to adhere to this code of conduct during the course of our participation under the umbrella of the Python Software Foundation, but the [OpenSSF Best Practices Badge requires a Code of Conduct to reach Silver level](https://bestpractices.coreinfrastructure.org/en/projects/5380?criteria_level=1) so it makes most sense to adopt this one year-round and make sure it's documented and clear for all new contributors, not only those who sign up via the GSoC systems.
=> docs: Add Python Community Code of Conduct info

test/test_extractor.py, test/test_helper_script.py, test/test_strings.py
* related: #1839
I still don't know *why* these tests are failing sometimes (and only sometimes) on python 3.7.  But since this code is being tested on the other versions of python, and they're failing reuglarly enough to make it a pain to get a clean PR with all tests passing, I'm going to try disabling them on 3.7 and see if that gives us increased stability for our CI setup.
=> test: Disable tests causing random py3.7 failures

.github/actions/spelling/allow.txt, fuzz/Readme.md
Adding instructions on setting up atheris's protobuf stuff to Readme, since it's not entirely obvious. This is mostly so I can run a script on the ubuntu cloud machines I'm playing with for running longer-term fuzzing.
=> docs: Add atheris protobuf setup to readme

test/test_extractor.py, test/test_helper_script.py
Fixed #1892 
Disabled sometime failing tests in Python 3.7
=> Fix: Disable failing tests in Python 3.7

.github/workflows/spelling.yml
Hi,
I'm providing a small change to the workflow.
By default permissions for GitHub workflows are very permissive. It's possible for an org to lock down permissions, but most organizations don't.
Since you're just relying on users reading the output from the workflow, there's no reason to allow the permission to have any write permissions.
This is generally listed here:
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#restricting-permissions-for-tokens
=> ci(spelling): Pull in permissions from check-spelling/spell-check-this

cve_bin_tool/version_scanner.py
Fixed: #1742 
Wrapped the `decode` method in try/except to catch the exception and log it. Error was in the `version_scanner.py` on line 112.
=> fix: Decode error during file scan in version_scanner.py (#1742)

cve_bin_tool/output_engine/__init__.py, cve_bin_tool/output_engine/console.py, cve_bin_tool/output_engine/util.py, test/test_output_engine.py
root is set to filename and filename is set to " - " since https://github.com/intel/cve-bin-tool/commit/a8d9eebbf109448e13a734eadeda1d3f04a3b194 which seems awkward when root is a path and not an archive:
```
╭─────────────────╮
│  NewFound CVEs  │
╰─────────────────╯
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃ Vendor       ┃ Product        ┃ Version      ┃ Root            ┃ Filename ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━┩
│ sudo_project │ sudo           │ 1.9.5p2      │ sudo_logsrvd    │  -       │
│ sudo_project │ sudo           │ 1.9.5p2      │ sudo_sendlog    │  -       │
```
So fix this issue with the proposal of @anthonyharrison to get this display when root is a short path:
```
╭─────────────────╮
│ …
```
=> fix: fix filename and root display

.github/actions/spelling/allow.txt
Fixed #1914 
Removed server from allowed list of words.
=> fix: Removed server from list of allowed words list

cve_bin_tool/data_sources/osv_source.py
fixes #1932 
CVEs will only be incrementally downloaded for an ecosystem if they are above a threshold value, otherwise zip file containing all the CVEs will be downloaded as it is faster.
=> fix: slow incremental updates for OSV

cve_bin_tool/version_scanner.py
When running `cve-bin-tool` on some of my projects, I get an `UnicodeDecodeError` upon decoding the output of `strings`. I thought it was best to handle it instead of completely stopping.
It is using the `"backslashreplace"` error handler which will use the hex form of the byte value with format `\xhh`.
Error example:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 853: invalid start byte
```
It would thus keep `\xff` in this case.
=> fix(strings): Handle Unicode decoding errors instead of crashing

cve_bin_tool/checkers/zlib.py
`cpe:2.3:a:gnu:zlib` has been deprecated since "2022-06-22T16:40:44.440Z": https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Agnu%3Azlib
`cpe:2.3:a:zlib:zlib` is the new correct CPE ID for zlib: https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Azlib%3Azlib
=> fix: fix zlib CPE ID

cve_bin_tool/checkers/cups.py
`cpe:2.3:a:apple:cups`, `cpe:2.3:a:cups:cups` and
`cpe:2.3:a:openprinting:cups` are valid CPE IDs for cups:
https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Aapple%3Acups https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Acups%3Acups https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Aopenprinting%3Acups
=> fix: fix cups CPE ID

cve_bin_tool/helper_script.py
Allow the user to give an executable file as an input,  e.g.:
`cve-bin-tool /usr/sbin/dnsmasq`
or
`cve-bin-tool /usr/lib/x86_64-linux-gnu/libarchive.so.13.6.0`
=> feat(helper_script): take an executable file as an input

.github/actions/spelling/allow.txt, cve_bin_tool/format_checkers.py
=> feat(format_checkers.py): exclude dictionary words from allow.txt

test/test_cli.py
This particular test seems to still break on windows.  I don't think it should be a rate limit thing since it's happening even with a nvd api key set in main, but since I'm trying to improve the stability of our CI in preparation for hacktoberfest, I'm experimenting with disabling it.
=> ci: disable failing update test on windows

test/test_extractor.py, test/test_helper_script.py
* fixes #1927
We're still seeing the occasional py3.7 failure, and I want to clean that up before hacktoberfest since it slows down PR approvals. I think these are the last of the ones I've seen fail, but I wouldn't swear I've gotten them all forever since we still don't know what's causing these other than it seems to be related to mock and possibly file accesses and only occurs on python 3.7.
=> ci: disable py3.7 tests causing sporadic failures

.github/workflows/update-cache.yml
This *SHOULD* resolve #1950 by only running the job *IF* the repository is 'intel/cve-bin-tool'.  It's probably also worth adding a check for the NVD_API_KEY as well just to be on the safe side, but I believe this resolves it (noting this is somewhat hard to actually test, for obvious reasons).
Signed-off-by: John 'Warthog9' Hawley <warthog9@eaglescrag.net>
=> Only run update-cache if you are the main repository

test/test_cli.py, test/test_cvedb.py
* fixes #1968
We've got two more tests that are sporadically failing on windows (but run fine on windows) possibly due to network issues or rate limiting.  In the interest of making CI more stable (especially before new hacktoberfest try to do PRs with us), I'm disabling them for the time being.
=> ci: disable intermittently failing windows tests

cve_bin_tool/helper_script.py, cve_bin_tool/parsers/python.py, cve_bin_tool/strings.py, cve_bin_tool/version_scanner.py
Extract `parse_strings` method to `strings.py` instead of `util.py` to avoid circular imports.
Closes #1966.
=> refactor: extract `parse_strings` method to `strings.py`

cve_bin_tool/helper_script.py
=> refactor(helper_script.py): use pathlib.Path instead of os.path

cve_bin_tool/util.py
=> refactor: use pathlib in util.py

.github/actions/spelling/allow.txt, cve_bin_tool/format_checkers.py
Signed-off-by: JoaoDanielRufino <joaodaniel0405@gmail.com>
- Added `tool` word on https://github.com/intel/cve-bin-tool/blob/main/cve_bin_tool/format_checkers.py#L94
- Removed `tool` word on https://github.com/intel/cve-bin-tool/blob/main/.github/actions/spelling/allow.txt
Closes #2037
=> fix: Add word "tool" to exclude list in format_checkers.py

test/test_scanner.py
* related #2054 
This test is currently failing in both linux and windows.  The file in question is correctly detected as python when I run the tool manually, so the problem is likely in the test code itself.  I'm temporarily disabling it while we try to determine a fix or a replacement test.
=> ci: disable test_version_in_package_make_download temporarily

test/test_helper_script.py
* related: #2038
These 4 tests are failing fairly consistently on windows in CI.  I still need to investigate further as to why and see if we can get them fixed, but in the interest of having stable CI (particularly with all the hackerfest requests coming in) I'm going to go ahead and disable them temporarily while we investigate.
=> ci: temporarily disable tests failing on windows

test/test_scanner.py
These tests are failing due to a filesystem error I haven't managed to track down in windows. I'm temporarily disabling them while we work out a better fix.
=> ci: temp disable libsrtp and p7zip tests on windows

cve_bin_tool/checkers/ppp.py, test/test_data/ppp.py
Current ppp checker doesn't work with some exotic pppd binary
=> fix: improve ppp checker patterns

.mypy.ini
A number of the 3rd party libraries we use don't yet have type hints (and maybe never will) so I've set up a mypy.ini file to guide mypy to ignore those for now.  We could replace this with stubs or remove entries if we want to improve the type checking in the future, but I'm okay with leaving these disabled for our first pass on type hinting.
=> feat: add mypy.ini file to deal with missing imports

cve_bin_tool/strings.py
By default, strings command will only return strings which have at least 4 characters:
"Print sequences of displayable characters that are at least min-len characters long.  If not specified a default minimum length of 4 is used."
This is an issue to catch some package versions such as upcoming chrony. This issue can already be tested by replacing the version of dnsmasq from 2.80 to 2.8 in mapping_test_data of test/test_data/dnsmasq.py.
To fix this issue, give a minimum length of 1. An other option would be to always use the python Strings function.
=> fix: fix strings call

cve_bin_tool/package_list_parser.py
The `--explicit` flag is used to get a list of all packages installed explicity on a system. This omits all packages installed as dependencies in the same transaction.
$ pacman --query | wc -l
1114
$ pacman --query --explicit | wc -l
74
Fixes: f57e7100c2ca3676bfba71f516307bfaddc8a1de
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> fix: ensure all pacman packages are accounted for

cve_bin_tool/strings.py
=> fix: change python strings to return only strings of length 3+

cve_bin_tool/checkers/curl.py, test/test_data/curl.py
Current curl checker doesn't work with some exotic libcurl library
=> fix: improve curl checker patterns

cve_bin_tool/checkers/avahi.py, test/test_data/avahi.py
Current avahi checker doesn't work with some exotic avahi binary
=> fix: improve avahi checker patterns

test/test_extractor.py
Resolves #2168
Wasn't sure of any other methods to do it, but the tests run just fine
=> refactor: extractor is now inherited in test_extractor.py

cve_bin_tool/util.py
I missed a typo in #2134 but it was caught by static analysis.  Yay for automation!
=> fix: fix dirname/filename typo in util.py

test/test_scanner.py
Added type-hints to pass `mypy` tests. #2129
=> refactor: add type-hints for test/test_scanner.py

cve_bin_tool/extractor.py, test/test_data/grub2.py, test/test_data/kerberos.py, test/test_data/kerberos_5.py, test/test_data/unbound.py
Moved self.tempdir up to the BaseExtractor class to clean up the mypy errors. fixes #2191
Added typing to test_data fixes #2131
=> refactor: fix mypy errors in cve_bin_tool/extractor.py

README.md, doc/MANUAL.md
Closes issue #2190 
Added sections in README.md and MANUAL.md regarding how NVD's current rate limiting scheme can block them and to setup an api_key to avoid it.
=> docs: warn users that nvd may block them if they are not using an api_key

cve_bin_tool/checkers/json_c.py, test/test_data/json_c.py
Current json-c checker doesn't work with some exotic json-c library
=> fix: improve json-c checker patterns

cve_bin_tool/checkers/sqlite.py, test/test_data/sqlite.py
Current sqlite checker doesn't work with some exotic sqlite library because sha256 is slighty different of what is returned by https://www.sqlite.org/changes.html
Expected value:
`2018-04-10 17:39:29 4bb2294022060e61de7da5c227a69ccd846ba330e31626ebcd59a94efd148b3b`
Value in library:
`2018-04-10 17:39:29 4bb2294022060e61de7da5c227a69ccd846ba330e31626ebcd59a94efd14alt2`
To fix this issue, truncate last four characters which are not guaranteed to be constant as specified in
https://www.sqlite.org/c3ref/c_source_id.html:
> If the source code has been edited in any way since it was last checked in, then the last four hexadecimal digits of the hash may be modified.
=> fix: improve sqlite checker patterns

cve_bin_tool/checkers/qt.py, cve_bin_tool/checkers/quagga.py, cve_bin_tool/checkers/rdesktop.py, cve_bin_tool/checkers/rsync.py, cve_bin_tool/checkers/rsyslog.py, cve_bin_tool/checkers/rtl_433.py, cve_bin_tool/checkers/samba.py, cve_bin_tool/checkers/sane_backends.py, cve_bin_tool/checkers/shadowsocks_libev.py, cve_bin_tool/checkers/snort.py, cve_bin_tool/checkers/sofia_sip.py, cve_bin_tool/checkers/spice.py, cve_bin_tool/checkers/squashfs.py, cve_bin_tool/checkers/squid.py, cve_bin_tool/checkers/strongswan.py, cve_bin_tool/checkers/stunnel.py, cve_bin_tool/checkers/suricata.py, cve_bin_tool/checkers/sylpheed.py, cve_bin_tool/checkers/tcpdump.py, cve_bin_tool/checkers/thrift.py, cve_bin_tool/checkers/thttpd.py, cve_bin_tool/checkers/timescaledb.py, cve_bin_tool/checkers/tinyproxy.py, cve_bin_tool/checkers/tor.py, cve_bin_tool/checkers/tpm2_tss.py, cve_bin_tool/checkers/transmission.py
Fixes #2282
I've done `from __future__ import annotations` and used `list` instead of doing `from typing import List` and using it. This way when we drop Python 3.8 we can just drop the import and leave type hints untouched. But I can switch it to `typing` if you prefer.
=> refactor: fix mypy errors in checkers q-t

cve_bin_tool/checkers/__init__.py, cve_bin_tool/helper_script.py
Closes #2127
I commented on this in the issue but to add the typing to `helper_script.py` I had to change the typing of the base `Checker` class.  I realize this may have a larger impact so look forward to any feedback.  Tests all passed so I think it's okay. 
Also, I used `Optional` in the typing instead of `|` so there's an extra import in the output of `helper_script.py`.
Note that I still get two exceptions in my pytest run (python 3.9):
```
FAILED test/test_extractor.py::TestExtractFileRpm::test_bad_files - struct.error: unpack requires a buffer of 96 bytes
FAILED test/test_extractor.py::TestExtractFileRpmWithZstd::test_bad_files - struct.error: unpack requires a buffer of 96 bytes
```
I was getting those exceptions prior to working on the issue though.
=> refactor: type hints helper script

README.md, cve_bin_tool/cli.py, cve_bin_tool/input_engine.py, test/csv/test_triage_input.csv, test/test_input_engine.py, test/test_requirements.py, test/test_triage.py, test/vex/test_triage_triage_input.vex, triage.json
As discussed in #2316, provide a way to load the (scanned) dependency data and the (manually enriched) triage data from separate files.
Another way to implement this might have been to allow multiple `--input-file` parameters, but  making an explicit separation between dependency input and triage input seems like a good idea, as we might want to handle those differently (and not rely on detecting them by looking at file extensions) in the future.
This implementation also assumes the triage data is in `vex` format and not in the internal `json` format. I think this makes sense since you might want to exchange triage data between different parties/tools, so having the `vex` format as a 'first-class citizen' rather than supporting `vex` and the internal format side-by-side seems more …
=> feat: explicit option to load triage file

cve_bin_tool/checkers/openssl.py
Improve openssl checkers to avoid a false positive with curl binary raised because of this help text embedded in the binary:
```
--tls13-ciphers <ciphersuite list>
(TLS)  Specifies which cipher suites to use in the connection if
it negotiates TLS 1.3. The list of ciphers suites  must  specify
valid  ciphers.  Read up on TLS 1.3 cipher suite details on this
URL:
https://curl.se/docs/ssl-ciphers.html
This option is currently used only when curl  is  built  to  use
OpenSSL 1.1.1 or later. If you are using a different SSL backend
you can try setting TLS 1.3 cipher suites by using the --ciphers
option.
```
=> fix: improve openssl checkers

cve_bin_tool/output_engine/console.py
The new version of pyupgrade merged in #2019 seems to have found one issue it wants resolved.
=> fix: pyupgrade fix for output_engine/console.py

cve_bin_tool/output_engine/console.py, cve_bin_tool/strings.py
It was passed as `"-n 3"` instead of `"-n", "3"`.
Yielded the error:
```
CalledProcessError: Command '['strings', '-n 3', 'lib.so']' returned
non-zero exit status 1.
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strings: unknown flag: -n 3
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strings [-] [-a] [-o] [-t format] [-number] [-n number] [[-arch <arch_flag>] ...] [--] [file ...]
```
=> fix: strings -n 3 args passing

cve_bin_tool/checkers/libjpeg.py
Current libjpeg checker will result in false positives, for example with the following line in `iwconfig`:
`%-8.16s  no wireless extensions.`
=> fix: improve libjpeg checker patterns

test/test_html.py
Rename `setup` & `teardown` to `setup_method` & `teardown_method`, as the latter is supported by pytest natively.
See https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
=> refactor(html-test): rename `setup` & `teardown`

.github/workflows/cve_scan.yml, .github/workflows/sbom.yml, .github/workflows/testing.yml, .github/workflows/update-cache.yml, doc/how_to_guides/cve_scanner_gh_action.md, doc/how_to_guides/cve_scanner_gh_action.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
=> ci: use `$GITHUB_OUTPUT` instead of `set-output`

cve_bin_tool/input_engine.py, test/vex/test_triage_triage_input.vex
consistent with the schema at https://github.com/CycloneDX/specification/blob/master/schema/bom-1.4.xsd#L1810
When the rating is provided, the severity is still taken into account.
=> fix: treat rating in VEX triage files as optional

.github/workflows/coverity.yml
Currently our Coverity scans do a file system capture on everything in the cve-bin-tool directory.  Unfortunately, that means coverity scans its own analysis (stored in cov-analysis) and also our 3rd party schemas, and it finds a lot of things in both of those.  I'm currently ignoring those in the web interface so we don't miss real, fixable issues, but this change would (hopefully, assuming I didn't make a typo) mean they don't get captured in the first place so they'll stop showing in our "defect density" going forwards.
=> ci: skip analyzing things we can't fix in coverity

cve_bin_tool/cvedb.py, cve_bin_tool/error_handler.py, cve_bin_tool/helper_script.py
Coverity scan raised a few issues about the case where the database cursor could be None.  I'm not convinced this happens in practice short of a catastrophic database failure, but I don't see any reason not to put checks in anyhow.  I feel like there's maybe more than just these few places where it could happen and I'm not sure why only these are flagged.
=> fix: address potential None in db cursor

cve_bin_tool/output_engine/console.py
Reduce path length from 45 to 30 as 45 is too much and results in truncated path since the addition of radvd and pppd which have very long vendor and product names (i.e. `point-to-point_protocol_project:point-to-point_protocol` and `litech:router_advertisement_daemon`)
While at it, also add a note for vendor and product if they are too long
=> fix: improve console notes

cve_bin_tool/input_engine.py
Static analysis is complaining that there's a case where the vendor might not ever be found, and thus when we try to do vendor.strip() a few lines further down that it's going to fail.  I've marked the vendor as "UNKNOWN" the same way we mark versions so that this won't break.  Given that we're trying to actually report everything found in the future, I *think* this is probably the correct way to handle that fallthrough case, but I'm pinging @anthonyharrison to look at it and see if he knows of any way it's likely to cause weirdness.
We could equally set the vendor to "UNKNOWN" in the first case, not sure if that's better or more confusing.
=> fix: Set vendor to UNKNOWN if all else fails

cve_bin_tool/checkers/ppp.py, test/test_data/ppp.py
Current ppp checker doesn't work with some exotic ppp binaries
=> fix: improve ppp checker patterns (#2214)

test/test_cli.py
* related: #2382
I still am unsure as to what's causing quiet_mode to fail in the longtests.  Testing to see if temporarily disabling it in longtests and only there will improve stability of our CI for now.
=> ci: disable quiet_mode test in long tests

cve_bin_tool/checkers/samba.py, test/test_data/samba.py
Current samba checker doesn't work with samba3 binaries
=> fix: improve samba checker patterns

.github/workflows/testing.yml
* Noticed thanks to #2368 
For some reason, windows long tests were still running test_requirements.py. We had intentionally moved that into a separate test runner so that it was easier to spot new CVEs that might affect us and it looks like we just  forgot to exclude it on windows.
=> ci: requirements do not need to be tested during windows longtests

cve_bin_tool/extractor.py, test/test_extractor.py
* fixes #1748
Currently, when files can't be extracted because a tool is not installed, we throw an exception and halt the scan.  This is great for getting attention but terrible if you're scanning a large system and maybe just don't care about scanning those files.  It also causes a problem in the issue linked above when attempting to run cve-bin-tool on a system outside of the ones we actually support.
This PR switches us to logging a message and allowing the scan to proceed.  I think that's mostly what users want, but there's still a couple of questions here:
- Should these be `logger.warning` or `logger.error` ?  I started with warning because that's what we have elsewhere but I worried that people might not realize some things weren't being scanned that maybe could be, so I switched …
=> fix: Change extraction exceptions to logged warnings

test/test_language_scanner.py, triage.json
The current check for language findings uses an assert all() that gives kind of lousy output because it doesn't tell you *which* item wasn't found, so this changes that test to be a bit more user friendly and also removes "rand" which is no longer being detected.
Sample new output:
```python
FAILED test/test_language_scanner.py::TestLanguageScanner::test_language_package[/home/terri/Code/cve-bin-tool/test/language_data/Cargo.lock-products1] - AssertionError: assert 'rand' in ['bumpalo', 'cranelift-codegen', 'crossbeam-chan...
```
=> fix: improve language test output, fix failing tests

cve_bin_tool/cve_scanner.py, cve_bin_tool/cvedb.py
* fixes #2428 (on main; a new release would likely be needed to address the 3.1.1 release)
Turns out we weren't really using LegacyVersion for anything so this PR just tries removing the places it existed.  It's possible this will break some type checking, but the type checking for this file was still a work in progress anyhow.
=> fix: remove LegacyVersion

requirements.txt
The fix I attempted where we removed the LegacyVersion uncovered some other changes in packaging that may be causing us problems.  This uses the same "temporarily avoid version 22.0" solution that I used for the 3.1.2 release to see if that resolves the problem short-term while I see if we can work out a better long-term fix (see #2435 )
Note: I'm using 22.0 locally and not seeing any of these errors, so I'm not 100% sure what's going on in CI.
=> fix: downgrade packaging temporarily

.github/workflows/testing.yml, .github/workflows/update-cache.yml
* fixes #2441 
Turns out the environment variable used for the date wasn't getting set and exported correctly on windows because windows uses a very different environment variable setup.  The key part of how to fix it was found here https://github.com/actions/runner-images/issues/5251
=> ci: fix windows date variable for caching

.github/workflows/update-cache.yml
Windows cache update timed out.  It didn't look like it hung so it may need more time.
=> ci: increase cache timeout on windows

.github/workflows/testing.yml
Fixes #2431 
Upgrade long tests and external connectivity tests to python 3.10
=> ci: Switching version of python used for long tests

cve_bin_tool/version.py
This changes our working version number to be 3.2.1dev0 so you can easily tell if you're running the release version or working on the development tree.  (The next release will either be 3.2.1 or possibly 4.0 depending on whether NVD removes access to NVD API 1.0.)
=> chore: bump version to 3.2.1dev0

.github/actions/spelling/allow.txt, doc/new-contributor-tips.md
I usually cut and paste a set of tips into issues that I mark as "good first issue" so I figured I'd put them into the docs directory so it was faster to find them when I needed them.
=> docs: Add short new contributor tips for copying into pull requests

cve_bin_tool/checkers/firefox.py, test/test_data/firefox.py
Fixes #2453 
Changed version strings to avoid false positives
=> fix: Improve firefox checker pattern

.github/workflows/testing.yml
Removes pdf tests from windows short tests
fixes: #2464
=> ci: remove pdf tests from windows short tests

.github/workflows/sbom.yml, sbom/cve-bin-tool-py3.10.json, sbom/cve-bin-tool-py3.10.spdx, sbom/cve-bin-tool-py3.11.json, sbom/cve-bin-tool-py3.11.spdx, sbom/cve-bin-tool-py3.7.json, sbom/cve-bin-tool-py3.7.spdx, sbom/cve-bin-tool-py3.8.json, sbom/cve-bin-tool-py3.8.spdx, sbom/cve-bin-tool-py3.9.json, sbom/cve-bin-tool-py3.9.spdx
Born from discussion in related issue https://github.com/intel/cve-bin-tool/issues/1646#issuecomment-1369296509.
This will run a scheduled workflow that should update SBOMs every week if there are any changes. Also added an option to run it manually if there's a need (as part of a release workflow for example).
=> ci(SBOM): better SBOM maintenance

.github/workflows/update-js-dependencies.yml
I have noticed that the workflow for updating JS dependencies [has failed](https://github.com/intel/cve-bin-tool/actions/runs/3819307107) so I've updated it with changes from #1667 and #1925.
=> ci(js): update workflow for updating JS

.github/workflows/linting.yml, .pre-commit-config.yaml, dev-requirements.txt
This will type check only the files specified in the pre-commit config. This way we won't regress and we can slowly (or quickly) add new files to be checked.
I've also added mypy to the dev-requirements.txt (it's curious that we had type stubs there already and even mypy config in the root of the project but not mypy itself).
Related to #2316.
=> ci: add mypy for type checking

test/test_requirements.py
There is no `importlib.metadata` on Python 3.7.
Without this fix test discovery fails in VSC with pytest. I guess it just means that not a lot of people if anyone use 3.7 in VSC for the development of cve-bin-tool anymore? 😄
We haven't noticed this issue in CI because this test only runs [on latest Python](https://github.com/intel/cve-bin-tool/blob/10c97660312b4138cc79a03df204f5174389ba39/.github/workflows/cve_scan.yml#L17).
=> fix(tests): use importlib_metadata.version on 3.7

cve_bin_tool/checkers/sqlite.py, test/test_data/sqlite.py
`sqlite(\d+)\.debug` pattern has been added more than 3 years ago to detect major version of sqlite:
https://github.com/intel/cve-bin-tool/commit/1c8c77206731f3a1f6b79f8f4fa0586ba587bdaa
However, the latest version 2 of sqlite (2.8.17) has been released in December 2005 so it is extremely unlikely that a system ships anything else that version 3.
So drop this pattern and instead add a new one that will display the date/hash if the hash isn't found on https://www.sqlite.org/changes.html
=> fix: improve sqlite pattern

cve_bin_tool/error_handler.py, test/test_cli.py
Previously, `cve-bin-tool --version` returned an error code of '2', as if it was an invalid argument.
With this change, it returns successfully, consistent with standard argparse behavior.
=> Let 'cve-bin-tool --version' return success

cve_bin_tool/checkers/__init__.py
Use `match` instead of `search` to only detect a match at the beginning of the filename for `FILENAME_PATTERNS` otherwise false positives will be raised. For example:
- `named` (i.e. bind) for `systemd-hostnamed`
- `eroute` (i.e. openswan) for `traceroute6`
- `scp` (i.e. openssh) for `libxt_dscp.so`
- `libc` (i.e. glibc) for `libuClibc.so`
=> fix: fix false positives with filename patterns

cve_bin_tool/checkers/capnproto.py
=> fix: type for capnproto checker

.github/workflows/testing.yml
This is absolutely a cheat, but I can't think of any particular reason we need two caches and windows is clearly flakier than linux in github actions.
=> ci: use linux cache since windows is broken

cve_bin_tool/output_engine/__init__.py, test/test_cli.py
* fixes #2556 
(This was a partial fix but I decided to put both fixes in a single PR so I didn't have to wait for CI twice.)
=> fix: test_update_flags and pdf encoding error

test/test_scanner.py
Replace space in test filename to avoid a failure on Windows (raised since commit 877691522d51bb104d7e88ddcd4ab18e48515623)
Fix #2533
=> fix: replace space in test filename

README.md
=> fix: Remove LGTM badge

cve_bin_tool/cve_scanner.py, test/test_csv2cve.py
Display `vendor.product` in affected instead of just the `product` as some products have multiple vendors (e.g. `zlib`)
=> feat(cve_scanner): add vendor to affected

test/test_language_scanner.py
Commonmark was removed as a dependency (in favour of markdown-it) by one of the packages cve-bin-tool uses.  The SBOMs all updated correctly and have been merged, but our python language scanner test used our own requirements.txt and was expecting it.  This removes it from the test, although it doesn't add the new dependency.
=> fix: commonmark no longer a dependency

.github/workflows/testing.yml
Windows has been a bit spotty again lately, failing around 82% on the last job I checked.  This might extend it enough to keep things moving, though I'm wondering if we need to do something else with windows because an hour is a long time...
=> ci: extend windows timeouts

test/test_data/gimp.py
Remove libjpeg-turbo from other_products of gimp
=> fix: libjpeg-turbo not found in gimp

.github/workflows/update-dev-requirements.py, .pre-commit-config.yaml, dev-requirements.txt
Fixes #2617
This will install isort 5.12.0 for Python >= 3.8 and the latest available for Python 3.7 (3.11.5 right now). Both have the original issue fixed. 5.12.0 requires Python 3.8.
Note that this WILL break running isort hook using pre-commit on Python 3.7. There are ways to skip only isort hook and run all others but I don't think it's worth it to add this to documentation for 5 months when 3.7 goes EOL.
An alternative would be to pin to 3.11.5 until 3.7 goes EOL.
First commit is needed so that the auto-update script doesn't remove environment markers.
=> ci: fix running isort using pre-commit

cve_bin_tool/checkers/tcpdump.py, test/test_data/qemu.py
Update checker to avoid false positives (e.g. with qemu)
=> fix: improve tcpdump checker

cve_bin_tool/checkers/gcc.py
Drop `gcc:gcc` CPE ID which doesn't exist in NVD NIST database: https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Agcc%3Agcc
The only CVE that referenced this ID is the very old CVE-1999-1439: https://nvd.nist.gov/vuln/detail/CVE-1999-1439
=> fix: improve gcc checker

cve_bin_tool/checkers/json_c.py, test/test_data/json_c.py, test/test_data/tpm2_tss.py
- Replace `JSONC_([0-9]+\.[0-9]+\.?[0-9]*)\r?\nGLIBC_` pattern which can raise false positive by `([0-9]+\.[0-9]+\.?[0-9]*)\r?\njson-c`
- Improve latest pattern to detect exotic libraries
=> fix: improve json-c checker

test/test_json.py
Don't run test_json.py if `EXTERNAL_SYSTEM` is False to avoid a test failure if NVD schema can't be downloaded
=> fix: improve test_json.py

cve_bin_tool/checkers/dbus.py
Drop `dbus_connection_set_dispatch_status_function` to avoid returning an `UNKNOWN` dbus version for `bluetoothd` or `libavahi-client.so`
While at it, also drop `dbus_connection_get_adt_audit_session_data` which could also raise false positives
=> fix: improve dbus checker

.github/actions/spelling/allow.txt, CONTRIBUTING.md
* Related to #2618 
* fixes #2492
This adds an explainer to our contributors docs explaining what versions of python we support, which ones they should probably use to start, and explains that the oldest version may not be supported by all our linters.    Also I updated the version of python used in our virtualenv setup docs to be 3.11 in line with our guidance to use the latest or latest-1. (it was previously 3.9)
=> docs: Explain recommended versions of python + linter concerns

cve_bin_tool/checkers/zlib.py, test/test_data/zlib.py
Drop `too many length or distance symbols` from `CONTAINS_PATTERNS` to avoid returning an `UNKNOWN` zlib version with libfreetype
=> fix: improve zlib checker

cve_bin_tool/checkers/expat.py, test/test_data/expat.py
Drop `libexpat:expat` CPE ID which doesn't exist in NVD NIST database: https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Alibexpat%3Aexpat
=> fix: improve expat checker

cve_bin_tool/checkers/xml2.py
Drop the very convoluted `guess_xml2_version` function and instead use standard `VERSION_PATTERNS` which is working perfectly fine
=> fix: improve xml2 checker

test/test_scanner.py
If the user adds a valid product in `other_products` but this product doesn't have any test in test_data (e.g. open_source for asterisk), `product_not_present.remove(option)` will fail.
Add a dedicated message to help the user in this case
While at it, also improve the message when the product is not found in the test package
=> fix: improve product_not_present

cve_bin_tool/config.py
=> fix: Any type in config.py

cve_bin_tool/checkers/janus.py, test/test_data/janus.py
Improve janus signature to avoid catching the string 0.1.19 in version 1.1.0
=> fix: improve janus signature

cve_bin_tool/checkers/tor.py, test/test_data/tor.py
Update tor signature to avoid catching the following string in tor 0.4.5.10 binary:
`The v0 control protocol is not supported by Tor 0.1.2.17 and later; upgrade your controller.`
=> fix: update tor signature

cve_bin_tool/checkers/__init__.py
Drop Python 3.5 "compatibility function" as Python 3.5 is not supported anymore (no security update since 13 Sep 2020:
https://endoflife.date/python)
=> fix: drop Python 3.5 "compatibility function"

cve_bin_tool/checkers/seahorse.py
Improve seahorse checker to avoid catching "3.2" or "3.20" strings for 3.20.0 binary
=> fix: improve seahorse checker

cve_bin_tool/checkers/putty.py, test/test_data/openssh.py
Update second pattern to avoid a false positive in openssh raised by the following string: PuTTY-Release-0.5*,
=> fix: improve putty checker

.github/workflows/scorecard.yml
* Related: #2707 
For some reason this job is working in that I have info in the security tab about results, but it's generating an error on every pull request.  This changes it to run only weekly, and changes the time of the weekly run to not be at midnight since that tends to be an entirely too popular time to run such things.
It can be re-enabled per pull request if someone can figure out why it's generating a segfault every time, but until that's fixed I don't think running in on main is helpful (and in fact, it's actively detrimental right now since I can't tell easily if a more critical test starts failing).
=> ci: skip scorecard runs on every push until error is fixed

test/test_scanner.py
Update `make_condensed_from_download` to allow it to condense binary which is not an archive. This is needed for the upcoming linux_kernel checker and its OpenWRT vmlinuz test binaries
=> fix: improve make_condensed_from_download

CONTRIBUTING.md, doc/new-contributor-tips.md
Explain how to "claim" an issue on github in both the tips I cut/paste into "good first issue" bugs and also in the contributor documents.  Honestly I though it was in the contributor documents but if it is it didn't have its own section.
=> docs: Explain how to claim an issue

cve_bin_tool/checkers/nbd.py
Update nbd pattern to avoid false positive with upcoming linux_kernel checker
=> fix: improve nbd checker

cve_bin_tool/util.py
Update `DirWalk.walk` to disable following symlinks, this will avoid scanning host binaries when analyzing an embedded rootfs target (e.g. if the target has an `./bin/echo` symlink pointing to `/bin/busybox`)
=> fix: don't follow symlink

.github/workflows/testing.yml
#2799 due to this issue, cached db is not being generated everyday. so windows tests are failing, because as of now they are dependent on the cache, and runs on offline mode. this pr will change that temporarily and will make it work on cache by default and also work when the cache is not available (just by simply updating the db).
=> ci: run windows test even when cached db is not present

cve_bin_tool/csv2cve.py
fixes: #2764
The argv parameter was originally type annotated in the main function signature. Removing the second type annotation to argv resolved all four mypy errors.
Although only changing a type annnoation I ran code quality tools with pre-commit and tests were run on WSL using Python 3.11. On the first run of tests I received over 900 failures with the following errors:
`RuntimeError: Cannot run the event loop while another loop is running`
`RuntimeError: This event loop is already running`
Adding:
```
import nest_asyncio
nest_asyncio.apply()
```
to my local tests directory's `__init__.py` resulted in 6 failing tests on the second run. See below for test summary:
=> fix: remaining mypy errors in csv2cve.py

.github/workflows/export_data.yml
Website: WEBSITE_LINK_OF_THE_PRODUCT
CVEs: CVEDETAILS_PRODUCT_PAGE
closes #2801
=> Commented out schedule run option in export_data yaml

test/test_scanner.py
All long tests are broken since https://github.com/intel/cve-bin-tool/commit/23b25e166e23c996bc7be3983f1c7dc6f5aab8f6 because for an obscure reason, `package_test_data` becomes empty after the loop so fix this issue
=> fix: fix long tests

cve_bin_tool/checkers/iptables.py
Update iptables checker to avoid returning a false positive with the following string:
```
192.168.1.1
iptables -t nP
```
=> fix: improve iptables checker

cve_bin_tool/checkers/libsndfile.py
Add additional CPE ID to catch "old" CVEs
=> fix: improve libsndfile checker

cve_bin_tool/checkers/netkit_ftp.py
Fix typo in vendor of `netkit_ftp` checker to avoid missing CVE-2007-5769 and CVE-2007-6263
=> fix: fix netkit_ftp checker

.github/workflows/testing.yml
* fixes #2833
Trying to address some sporadic CI fails with longer timeouts (particularly on the short tests).  Also trying some specific versions of ubuntu rather than ubuntu-latest because we've seen reductions in queue time before jobs are run.
=> ci: increase timeouts, try specific ubuntu versions

doc/Makefile, doc/index.rst, doc/requirements.csv, doc/requirements.txt, doc/sboms_for_humans, sbom/Makefile, sbom/sboms_for_humans/README.md
this commit adds a build process for SBOM markdown files triggered by the docs build process.
From your review in the previous implementation: 
>Could we maybe make it so the human-friendly SBOM formats are generated only for the readthedocs site (e.g. run the  >sbom to markdown conversion in doc/Makefile) but not checked in to github as md files every week?
The `sbom/Makefile` is triggered in `doc/Makefile`. 
I like this one!
=> feat: human readable sbom integration

cve_bin_tool/extractor.py
The deb extractor within `extractor.py` now handles zstd-compressed archive contents, which is supported in newer dpkg releases.
fixes: #2942
=> fix: handle data.tar.zst within deb archives

cve_bin_tool/nvd_api.py
Submitter notes: added the timeout suggested by another contributor and tested that pulling from NVD still works.
fixes: #2580
=> fix: add timeout in NVD API 2.0 code

cve_bin_tool/checkers/proftpd.py, test/test_data/lynx.py, test/test_data/proftpd.py
Improve proftpd checker to avoid a false positive with lynx which has a check for broken ProFTPD 1.2.5rc1 and so embeds the following string: `ProFTPD 1.2.5`
=> fix: improve proftpd checker

cve_bin_tool/checkers/pango.py, test/test_data/pango.py
Improve pango checker to avoid false positives with upcoming emacs checker
=> fix: improve pango checker

cve_bin_tool/checkers/tcpdump.py, test/test_data/tcpdump.py
Update tcpdump checker to avoid a false positive with `shortcut-fe.ko`
=> fix: update tcpdump checker

cve_bin_tool/version.py, requirements.txt
Sorting the requirements makes it easier for me to update our licensing paperwork.
=> chore: Bump version for 3.2.1 release, sort requirements

cve_bin_tool/parsers/java.py
if the product did not have - in name and the vendor was found it would return None even though the match was found
* fixes #2960
=> fix: java parser failing to match vendor on product without '-'

.github/actions/spelling/allow.txt, README.md, doc/how_to_guides/sbom.md, doc/how_to_guides/sbom_generation.md
The changes to SBOM support documentation that are left over after hackathon event.
=> fix: Enhance SBOM docs (fixes #2922)

cve_bin_tool/version.py
Bump version to 3.2.2dev0 so it's easy to tell if you're using the dev tree (e.g. installed from github) vs a released version.
The next release may actually be numbered 3.3 or 4.0 and will likely occur in late July after GSoC mid-terms depending on feature progress at that time.
=> chore: bump to dev version 3.2.2dev0

.github/dependabot.yml
Doing some experiemntation to see if we can improve our depenabot.yml config and to try to get the checker to run before things are merged to main because that's just annoying. It looks like it might run on non-fork branches so I'll try that.
=> ci: Dependabot "duplicated" lines and ignore "*"

.github/workflows/testing.yml
The short tests on both windows and now linux have been periodically timing out. This raises the limits for both the long and the short tests while we decide if the short tests need to be reduced to improve our CI experience.
Fixes #3046
=> ci: up timeouts on short and long tests

cve_bin_tool/cve_scanner.py, test/test_csv2cve.py
Replace `v{product_info.version}` by `version {product_info.version}` to allow the version number to be displayed in the same color (i.e. `4.19.205` will be displayed in blue and `version` in white instead of displaying `19.205` in blue and `v4.` in white)
=> feat(scanner): slight update in version display

cve_bin_tool/cvedb.py
=> feat: updating schema

cve_bin_tool/cvedb.py, cve_bin_tool/fetch_json_db.py
fetch from mirror was not working due to recent changes in the db structure (two tables were added cve_metrics and metrics)
=> fix: fetch cves from mirror not working

cve_bin_tool/checkers/dnsmasq.py, test/test_data/dnsmasq.py
Update dnsmasq pattern to catch version on 'exotic' binary
=> fix: improve dnsmasq checker

cve_bin_tool/cvedb.py, test/test_cvedb.py
=> feat: adding EPSS data

cve_bin_tool/cvedb.py
fixes: #3144 @terriko I already had done work for this one and was asking if to include it in that PR or create a separate issue for this PR.
=> fix: refactor insert queries

test/language_data/fail_pom.xml, test/test_language_scanner.py, test/test_package_list_parser.py
* Fixes #3157
The improvement to avoid data from multiple sources from clobbering each other caused a few tests to suddenly get new results, so they needed to be updated.
This doesn't feel like the most "correct" fix for the package lsit parser's test_valid_ubuntu_list, but that one may need more investigation. This should be ok as a workaround while we sort out the data issue that's causing us to get "unknown" vendors.
=> test: fix tests broken by improved data

.github/workflows/update-cache.yml, test/test_package_list_parser.py
Pretty sure this test is failing related to the cache problem, but it needs to be disabled so the branch protection rules will let me merge any fix.
=> ci: extend cache timeout, disable failing test

.github/workflows/cve_bin_tool_action.yml
=> ci: add cve-bin-tool-action

sbom/cve-bin-tool-py3.10.json, sbom/cve-bin-tool-py3.10.spdx, sbom/cve-bin-tool-py3.11.json, sbom/cve-bin-tool-py3.11.spdx, sbom/cve-bin-tool-py3.8.json, sbom/cve-bin-tool-py3.8.spdx, sbom/cve-bin-tool-py3.9.json, sbom/cve-bin-tool-py3.9.spdx
Turning on branch protection has broken my ability to merge our automatic SBOM jobs.  They don't run the tests because they don't need to, but then the branch protection rule won't let me merge until the tests pass and there's no way to force them to run.
This is a workaround where I pull all of the SBOM updates into a personal branch so I can force the tests to run.  I hope this won't be our long-term fix since it's a pain, but it will do for this week until I figure out a better solution.
=> chore: SBOM updates july24

cve_bin_tool/cvedb.py
=> feat: Populate cvss

cve_bin_tool/cli.py, cve_bin_tool/cvedb.py
I was working on a fix for downloading cves from mirror, and found out these while importing json manually.
=> fix: import json flag

cve_bin_tool/cve_scanner.py, cve_bin_tool/cvedb.py, cve_bin_tool/data_sources/epss_source.py, cve_bin_tool/util.py, test/test_source_epss.py
This PR is to be only considered after closing #3147.
=> feat: Update queries

cve_bin_tool/checkers/libksba.py
libksba_project:libksba has been deprecated by NVD [0], gnupg:libksba should be used instead.
[0]: https://nvd.nist.gov/products/cpe/detail/AA709F75-0B9E-4B67-ACEA-C1DCF33E7745?namingFormat=2.3&orderBy=CPEURI&keyword=libksba&status=FINAL
=> fix: update libksba CPE ID

test/language_data/package-lock.json
This is a kind of silly update.
The package-lock.json file we use for language tests has a version of semver that's triggering some CVE warning in one of my dashboards. Normally, I mark these as irrelevant because files in test/language_data are used only for tests of the scanner (the vulnerable code described is never downloaded or used).  But for some reason this particular dashboard isn't giving me the usual way to dismiss the warning.  
Since fixing that particular private dashboard might take a while, I'm going to try updating the one thing that's throwing an error so I don't have to get daily warnings about this component.
It's possible this change will break the tests.  I am running them locally but uploading this PR while I wait so they can happen in parallel.
=> fix: update nodejs semver in test files to avoid warning

test/test_scanner.py
gimp tests have been disabled in January 2021 by commit a5d6c25fdf59fedab2da63336328968ef3ada165 but they seem to work perfectly fine nowadays (at least on Linux)
=> fix: enable gimp tests

dev-requirements.txt
py used to be a dependency of pytest, and we had it explicitly added to our requirements file as a workaround to avoid an older vulnerable version.  As of pytest 7.2.0 this dependency is no longer required.
=> chore: remove dependency on py

cve_bin_tool/data_sources/osv_source.py, test/test_source_osv.py
removed use of `ECOSYSTEM` versions, and corrected vendor name guessing from package name.
fixes #3200 
partial work on #3201
=> fix: handling of product versions and vendor name guessing

cve_bin_tool/data_sources/nvd_source.py
fixes #3136   (at least partially: it excludes the "longer term potential feature" part)
As described in above issue, NVD source provides a list of affected CPE for a given CVE. This list may include non-vulnerable products such as OSes an affected product runs on, e.g. application v3.4 is vulnerable when it runs on Windows. The latter, although being mentioned in a CPE for this CVE, is not vulnerable with regard to that CVE. 
Whether a CPE is vulnerable or not is provided in a `vulnerable` attribute that can be used during data ingestion. See [Response `configuration` JSON sample](https://nvd.nist.gov/developers/vulnerabilities). This PR ignores non-vulnerable CPEs when building/refreshing the CVE DB
Limitations
- On a DB refresh, `vulnerable` will be used, but it won't remove existing …
=> fix: ignore non-vulnerable CPEs from NVD CVEs

cve_bin_tool/cve_scanner.py, cve_bin_tool/input_engine.py, test/test_input_engine.py
=> fix: blank path gets added when using triage_input_file option

.github/actions/spelling/expect.txt, .github/workflows/testing.yml, README.md, cve_bin_tool/cli.py, cve_bin_tool/data_sources/nvd_source.py, doc/MANUAL.md, test/test_cli.py
=> feat: use cveb.in mirror by default

test/test_helper_script.py
=> fix: spelling issue

.pre-commit-config.yaml, cve_bin_tool/cvedb.py, test/test_checkers.py
=> chore: update pre-commit and fix linter errors

cve_bin_tool/output_engine/console.py
Products with no identified vulnerabilities are broken since commit 6b0f36e03b74abc76cd2b83a0d3207c4ceaa4d02 because `products_with_cves` will always contain a dictionnary of all products. So replace the broken lamba function with a more clear way of computing products with CVEs (i.e. `len(cve_data["cves"]`))
=> fix: fix products with no identified vulnerabilities

cve_bin_tool/checkers/openssh.py
[CVE-2023-25136](https://nvd.nist.gov/vuln/detail/cve-2023-25136) is registered under openssh:openssh CPE ID
=> fix: add additional openssh CPE ID

doc/how_to_guides/sbom.md
fixes #3272
docs : updated the version of cycloneDX in  "doc/how_to_guides/sbom.md"
=> docs: updated version of cycloneDX #3272

.pre-commit-config.yaml, dev-requirements.txt
https://github.com/psf/black/releases/tag/23.9.0 introduced a faster mirror (claimed to be 2x speedup) and https://github.com/psf/black/releases/tag/23.9.1 contained a bugfix to really make it fast
=> ci: switch to a faster Black mirror

README.md
fixed : #3347 by adding the new build status URL to the readme
=> fixed : #3347

.github/dependabot.yml
These were a nice idea, but the auto-ignores are causing a problem with an internal automated script so they'll need to be disabled and I'll need to go back to manually discarding dependabot results in `test/language_data`
=> ci: Remove dependabot ignores

.readthedocs.yml
* fixes #3323
Looks like readthedocs needs a build.os specified in the config file.  I should probably also update this to use a more recent version of python but I'm trying to avoid making too many changes at once since it's not easy to test this config file locally.
=> docs: specify docs build.os

test/language_data/pom.xml, test/test_language_scanner.py
* Related: #3360
* Fixes: #3361
For some reason we're getting non-deterministic behaviour around commons-io (with a dash) vs commons_io (with an underscore) during detection.  Since the test doesn't really need to detect that partcular library, we're leaving it out for now while the issue is investigated further.
=> test: improve flaky java language scanner test

cve_bin_tool/fetch_json_db.py
=> docs: Add missing docstrings fetch_json_db.py

cve_bin_tool/package_list_parser.py
This PR fixing the ISSUE #3377 
- ✅Docstrings added to each of the functions of the file mentioned.
=> Fix : add missing docstrings to package_list_parser.py #3377

.github/workflows/sbom.yml
=> Add conditional execution for SBOM workflow on the main repository

cve_bin_tool/cvedb.py
Closes #3379 
I've added all of the docstrings that were missing in cvedb.py. I also fixed a couple typos in existing docstrings and comments.
=> docs: add missing docstrings to cvedb.py

cve_bin_tool/checkers/hostapd.py
Improve hostapd checker to avoid the following false positive with a proprietary library: `AP configuration based on hostapd v0.5`
=> fix: improve hostapd checker

.github/workflows/testing.yml
Fixes #3415
Job will skip if match this condition:
- The author is github-actions[bot]
- Source branch start with 'chore'
This approach is different from my comment on the issue because i see there's a pattern on the PR created by `github-actions`. Also, I see several workflow file for automatic update on this repo (sbom, js dependencies, etc). I think this changes has pros and cons described below.
I use [github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to retrieve information about the PR author and the source branch ref
Pros
- More simple compared to my proposed approach
- Will skip all PR created by `github-actions[bot]`
Cons
- Manually update in the folder `sbom/` will trigger the tests
I've test this on my private repo, here's the …
=> ci: Add condition to skip job when PR author is Bot

.github/actions/spelling/allow.txt, README.md, doc/MANUAL.md, doc/how_to_guides/index.rst, doc/how_to_guides/scan_installed_packages.md
* fixes #3071
Our README.md file was getting pretty long.  This streamlines it (moving some content to the manual or how-to guides) and reorganizes, as well as updating in preparation for 3.3 when we'll be using the mirror directly instead of needing an nvd_api_key for all installs.
=> docs: streamline readme file and reorg docs

.pre-commit-config.yaml
Fixes:  #3436 
Added an exclusion of fuzz/generated sub-directory for linting.
=> fix: pre-commit-config file

cve_bin_tool/output_engine/console.py, test/test_output_engine.py
Since commit 66e1df391c7598b05a7c3afbbf9808ce1b140648, console width is hardcoded to 120 and so width auto-detection is disabled. Drop this line as most modern screens can display more than 120 characters and a lot of lines are truncated now that EPSS data, latest version, etc. are displayed.
=> fix: do not hardcode console width

.github/workflows/fuzzing.yml
fixes: #3443 
Added the fuzzing.yml file for performing fuzz testing in rotation on 07.00 UTC every Monday with 60 min timeout only on the Main Repo.
I opened this PR for initial review, also needed guidance for handling the errors or exception,
I used the fuzz_main , fuzz_go and fuzz_cyclonedx script for testing all of them ran fine.
=> ci: github actions for fuzz testing

.github/workflows/testing.yml
The earlier PR skipping tests caused issues with our branch protection rules and had to be disabled because it blocked merging of pull requests (if the tests were skipped, the PR could never be merged).  This allows part of the job to run (so it'll pass branch protection checks) while skipping the install and running of tests on sbom jobs provided by our automated job.
Note that this is the same code as I had in #3446 but I'm separating it out so it gets a proper code review from someone who is not me.  
It won't do anything interesting when the tests are run here (because this isn't a bot PR for an sbom) but you can see what it's supposed to do on #3446
=> ci: skip running tests on bot-generated sboms

.github/workflows/formatting.yml, .github/workflows/linting.yml, .github/workflows/testing.yml, .github/workflows/update-js-dependencies.yml, .github/workflows/update-pre-commit.yml
Fixes #3494 
Replaced "3.x" with "3.11" in exactly 5 workflow files.
=> Ci: Change workflows to use python 3.11 

.pre-commit-config.yaml, dev-requirements.txt
=> chore: add interrogate to linters called by pre-commit

cve_bin_tool/output_engine/__init__.py
Added missing docstrings for methods and classes mentioned in issue #3463 
Referred PEP 257 – Docstring Conventions
fixes #3463
=> docs: add missing docstrings to output_engine/init.py

cve_bin_tool/output_engine/console.py
Sort CPE summary by product instead of vendor, this is especially useful for product with multiple vendors (e.g. dnsmasq).
=> feat(console): sort CPE summary by product

test/test_version_compare.py
with that construct, the second line was never executed
=> test_version_compare: use different pytest.raises for each instruction

cve_bin_tool/version_compare.py, test/test_version_compare.py
=> version_compare: support + in versions

cve_bin_tool/version_compare.py, test/test_version_compare.py
Currently version_compare rasies an error when it gets a hash, since we can't really compare those without more knowledge of the product. This changes the code to silently drop hashes and similar distro markers from the end of versions, which should make our code more robust to real-life cases.  We may also want to put in an error handler to log the versions we can't handle without halting the program, but this doesn't do that yet.
Fixes #3556
=> fix: improve version_compare to drop hashes

cve_bin_tool/checkers/openssl.py
Update openssl pattern to catch version on 'exotic' library
=> fix: improve openssl checker

cve_bin_tool/version_compare.py
Coverity was warning about unreachable code because I forgot to put in an if statement.
=> fix: improve version_compare logic

cve_bin_tool/version_compare.py, test/test_version_compare.py
This switches the logic so we treat all non-alphanumeric characters as separators equivalent to `.` in version strings.  This should make the code more robust to unusual version strings.
* Fixes #3558 (in that we will be able to handle `~`)
=> fix: non-alphanumeric characters as separators

cve_bin_tool/output_engine/html_reports/js/main.js, cve_bin_tool/output_engine/html_reports/templates/base.html, cve_bin_tool/output_engine/html_reports/templates/row_product.html
Coverity is issuing a warning about this function and it's easier for me to temporarily disable it than fix it this week.
=> fix: remove resizeGraph function

README.md, cve_bin_tool/cli.py, cve_bin_tool/cve_scanner.py, cve_bin_tool/output_engine/__init__.py, cve_bin_tool/output_engine/console.py, cve_bin_tool/output_engine/util.py, test/test_output_engine.py
Since commit 06b55f7e2aab435e7964fec90ebb30e15ed87585, to get metrics, a database query is made for every single CVE. This behavior dramatically increases processing time. For example, **2 seconds** was needed before this change to scan `apache2-bin_2.4.10-10+deb8u12_amd64.deb.tar.gz`. After this change, **30 seconds** is needed to extract the metrics of the 60 CVEs related to apache 2.4.10.
Time increase depends on number of CVEs so the increase is even greater when parsing a directory (e.g. an IoT firmware dump).
I assume that most users are not that interested with those metrics and would prefer to get a quick result so only retrieve metrics if the user asks it through the new `--metrics` option.
=> feat: disable metrics by default

cve_bin_tool/checkers/gnutls.py
`gnutls:gnutls` has been added with commit 11b9d7b4d71c9b705ed0dbd3e602d171d399294e but it is not a valid CPE ID: https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Agnutls%3Agnutls
=> fix: drop wrong gnutls VENDOR_PRODUCT

cve_bin_tool/checkers/squashfs.py
Replace `squashfs-tools` by `squashfs-tools_project` as `squashfs-tools:squashfs-tools` is not a valid CPE ID: https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3Asquashfs-tools%3Asquashfs-tools
=> fix: update squashfs VENDOR_PRODUCT

cve_bin_tool/checkers/tor.py
Replace `tor-project` by `tor_project` as no CVEs are associated to `tor-project:tor` CPE ID
=> fix: update tor VENDOR_PRODUCT

cve_bin_tool/checkers/gawk.py
Update gawk pattern to avoid a false positive in `gawk.info` raised by `GNU Awk 4.1.2, API: 1.1`
While at it, fix following typo: binutils -> gawk
=> fix: update gawk pattern

cve_bin_tool/checkers/glibc.py, test/test_data/glibc.py, test/test_data/gnomeshell.py
Update glibc pattern to avoid false positives in:
- `libgnome-shell.so` rasied by `the new format specifier introduced in glibc 2.27`
- `gmp-info.1` raised by `is the older GLIBC 2.0.x style.`
=> fix: update glibc pattern

cve_bin_tool/checkers/zsh.py, test/test_data/zsh.py
Update zsh pattern to avoid a false positive in `autoconf.info` raised by `$ zsh-4.3.4 ./lineo`
=> fix: update zsh pattern

cve_bin_tool/checkers/gdb.py
Improve gdb pattern to avoid a false positive with `annotate.info` or `gdb-info.1`
=> fix: improve gdb pattern

cve_bin_tool/checkers/binutils.py, test/test_data/binutils.py, test/test_data/gdb.py, test/test_data/linux_kernel.py, test/test_data/u_boot.py
Update binutils pattern to avoid a false positive in `libtool.info-1` raised by `libbfd-2.9.0.so`
=> fix: update binutils pattern

cve_bin_tool/checkers/bison.py, test/test_data/bison.py
Update bison pattern to avoid a false positive in `bison.info` raised by `Introduced in Bison 3.0.3.`
=> fix: update bison pattern

cve_bin_tool/checkers/gpgme.py
`gpupg:gpgme` is a CPE ID without any CVEs so drop it: https://www.cvedetails.com/vulnerability-list/vendor_id-4711/product_id-94121/Gnupg-Gpgme.html
=> fix: drop gpgme CPE ID without CVEs

cve_bin_tool/checkers/netatalk.py
`netatalk_project:netatalk` is a CPE ID without any CVEs so drop it: https://www.cvedetails.com/vulnerability-list/vendor_id-20887/product_id-61360/Netatalk-Project-Netatalk.html
=> fix: drop netatalk CPE ID without CVEs

.github/workflows/testing.yml, dev-requirements.txt, test/test_package_list_parser.py
This code was causing more tests to be skipped than intended because of a bad string compare.
fixes #3629
=> ci: fix sbom test skipping logic

README.md, cve_bin_tool/cli.py
detailed option was added by commit 4f3538e89d5510d5bfc1c2c288dd96f491485884 with the following description: "display detailed report" which is a bit cryptic so replace it by "add CVE description in csv or json report (no effect on console, html or pdf)".
=> fix: update detailed description

cve_bin_tool/cli.py
Enable metrics if epss-percentile or epss-probability is set by the user. This commit also fix this following broken logic which allowed negative epss values:
`
if float(args["epss_percentile"]) > 0 or float(args["epss_percentile"]) < 100:`
replaced by:
`if float(args["epss_percentile"]) >= 0 and float(args["epss_percentile"]) <= 100:`
Tentative fix for #3625
=> feat: Enable metrics if epss-{percentile,probability} is set

test/test_cli.py
This is not a proper fix, just a temporary measure so other PRs can pass while #3674 is resolved.
=> fix: temporary disabling due to #3674

test/test_output_engine.py
fixes: #3626 
Added a test for OutputEngine's output_console with metrics=False.
=> test: added test for OutputEngine with metrics=False

cve_bin_tool/cli.py, doc/MANUAL.md
- Resolves #3582 
- Updated documentation clarifying the failover to api2
=> fix: Deprecate NVD API 1.0

doc/MANUAL.md
closes #3638 
The addition of PHP (#2567) support was not documented in the MANUAL.md file.
=> docs: add PHP launguage specification to docs

cve_bin_tool/cli.py, doc/MANUAL.md
* resolves #3625 
- Added documentation clarifying automatic activation of `--metrics`.
- Updated epss related help
=> docs: Clarifying use of --metrics and epss options

cve_bin_tool/output_engine/print_mode.py
@terriko 
This docstring should work better for issue #3457 than PR #3675. Interrogate still passes, but then again it is only checking for the presence of a docstring (see attached image below). Please let me know if this works, or if I'm still missing the function description.
=> docs: Add appropriate docstring to output_engine/print_mode.py (#3457)

.github/actions/spelling/allow.txt, README.md
I have updated the options list in **README.md** by adding the missing options which I got from `cve-bin-tool --help`  . Also I have added the links to the MANUAL file for the options which were present in the MANUAL file. Few of the options were not present in the MANUAL file, so I couldn't add the links for those options.
fixes #3652
=> docs(README.md): updated options list in README.md

.github/workflows/linting.yml, .pre-commit-config.yaml
This is just the interrogate fix extracted from #3694 for easier review/merging.
=> ci: improve interrogate/pre-commit config

cve_bin_tool/cvedb.py, test/test_csv2cve.py, test/test_exploits.py, test/test_language_scanner.py, test/test_sbom.py
Fixes #3653
I was able to get the tests to fail locally, but it looks like my local database was messed up because OSV had over-written the NVD severity data, causing tests to fail.  Refreshing the data *has* fixed it, but it's possibly because we're having other OSV issues and that data isn't getting loaded.  Going to re-enable the tests and make sure nvd is loaded last (so it over-writes any bad data from OSV) but I'll need to keep an eye on this because something bigger is likely wrong with the way our data sources are loading.
=> test: re-enable failing tests from #3653

cve_bin_tool/util.py
closes #3710 
This pr adds docstrings to `cve-bin-tool/util.py` file.
=> docs: add docstrings to cve-bin-tool/util

cve_bin_tool/sbom_manager/swid_parser.py
closes #3712 
This Pr Adds docstrings to `cve_bin_tool/sbom_manager/swid_parser.py`
=> docs: added docstring to swid_parser.py

cve_bin_tool/version_compare.py, experiments/sqlite-experiments.py, test/test_version_compare.py
As described in #3657, this switches us to splitting version strings up a bit differently so all numbers and letters are handled as separate entities
So for example,  `1apple23banana456carrot` would be parsed out as `1.apple.23.banana.456.carrot`
We've got some *very* rudimentary git hash detection in there right now to avoid total nonsense compares, but I suspect we'll need to handle other types of hash correctly as well.
Also, I hit an issue with the new interrogate setup and had to modify the .pre-commit.config file or it wouldn't let me commit anything, so... uh, that's definitely going to be an issue.
=> fix: improve robustness of version compare

.github/workflows/cve_bin_tool_action.yml, .github/workflows/testing.yml
Looks like we missed a couple of workflows when I last updated the permissions to fit OpenSSF recommendations, so this should fix that.
=> ci: set default permissions on workflows

.github/workflows/testing.yml
* fixes #3495 
@milinddethe15 did some investigation and found that things should work if the -dev package was installed.  Looks like we can't explicitly install python3.12-dev but we already install python3-dev with the pdf testing components so this may work.
(I haven't checked if the tests will pass yet, though)
=> ci: Add python 3.12 with fix from @milinddethe15

cve_bin_tool/checkers/darkhttpd.py
Add unix4lyfe:darkhttpd to avoid missing 2 CVEs published in 2024
=> fix: update darkhttpd VENDOR_PRODUCT

cve_bin_tool/config.py, requirements.txt
Closes #3777
Using the tomllib module for Python 3.11 and later deployments instead of the toml module. Also added some docstrings.
=> feat: Using tomllib instead of toml in python 3.11 and later deployments

cve_bin_tool/cli.py, test/test_cli.py
=> fix: fixed quiet_mode test to ignore unimportant logs

.github/workflows/testing.yml, .pre-commit-config.yaml, cve_bin_tool/extractor.py
Had an external report that we weren't sufficiently careful when opening tarfiles because we're using Python's (insecure) default behaviour here.  That default *is* changed in python 3.12 but since we support 3.8-3.11 as well then we need a fix.  
This uses the file filters if available as recommended by the tarfile docs (it's not quite a `from __future__` but similar idea I think) and does a simple "skip symlinks and absolute paths" check if filters are not available.
Edit:
This is still missing
- test
- a fix that works in windows
I'm hoping we can merge what I have so we have mitigation on Linux in main, but those will definitely be coming in future PRs.  (The test would have been in this one but I'm feeling unwell so I'm sending it for code review while I won't be touching it for a …
=> fix: use tarfile extract filters to open tarfiles more safely

cve_bin_tool/checkers/bind.py, cve_bin_tool/checkers/binutils.py, cve_bin_tool/checkers/cups.py, cve_bin_tool/data_sources/gad_source.py, cve_bin_tool/data_sources/nvd_source.py, cve_bin_tool/data_sources/osv_source.py, cve_bin_tool/nvd_api.py, cve_bin_tool/output_engine/__init__.py, cve_bin_tool/output_engine/html.py
=> chore: update inconsistency in files with black v24.1.1

cve_bin_tool/cli.py
fixes #3801 
* Updated default_source initialization when NVD is disabled.
=> fix: initialize data_source when NVD is disabled

cve_bin_tool/extractor.py, cve_bin_tool/util.py, cve_bin_tool/version_scanner.py
`is_symlink` can return `PermissionError` exception so handle those thanks to try/except blocks.
=> fix: handle is_symlink PermissionError

cve_bin_tool/sbom_manager/__init__.py, test/test_cli.py
related: #3800 
added purl validation.
addresses: https://github.com/intel/cve-bin-tool/actions/runs/7444190703/job/20250200079
Output:
=> fix: resolve errors of fuzzing job fuzz_cyclonedx

cve_bin_tool/cli.py, cve_bin_tool/config_generator.py, test/test_cli.py
fixes: #2821 
this PR continues work of @Rexbeast2 on making ConfigGenerator Robust,
problem fixed :
- format of Toml including boolean values and list of values as string rather than lower case boolean values and normal list.
- improvement in variable naming, usage of spaces for indentation in yaml, apparently yaml don't like tabs for indentation  ; (
=> fix: make config generator robust

CONTRIBUTING.md
On some systems or misconfigured virtual environment, running `python -m pytest` instead of `pytest` can avoid typical errors related to Python's module search path, issue #3816
=> docs: Add tip about python -m pytest #3816

fuzz/fuzz_cargo_lock.py, fuzz/fuzz_cpanfile.py, fuzz/fuzz_cyclonedx.py, fuzz/fuzz_go.py, fuzz/fuzz_intermediate_report_merge.py, fuzz/fuzz_main.py, fuzz/fuzz_package_list_parser.py, fuzz/fuzz_package_lock.py, fuzz/fuzz_pom_xml.py, fuzz/fuzz_python_requirement_parser.py, fuzz/fuzz_renv_lock.py, fuzz/fuzz_tuples.py
Closes #3682 
This Pr adds docstrings to `cve-bin-tool/fuzz` module.
=> docs: add docstrings for fuzzing modules

cve_bin_tool/output_engine/__init__.py
Pass `width` parameter when writing console output to a file to avoid the following exception when running `cve-bin-tool -f console -o output` raised since commit ec4f10e4aa9d4bee0dddd8ffc0b896e331bec9a7:
```
│ /home/fabrice/cve-bin-tool/venv/lib/python3.11/site-packages/rich/console.py:1303 in render      │
│                                                                                                  │
│   1300 │   │   """                                                                               │
│   1301 │   │                                                                                     │
│   1302 │   │   _options = options or self.options                                                │
│ ❱ 1303 │   │   if _options.max_width < 1: …
```
=> fix: set default width for console output

.pre-commit-config.yaml, bandit.conf, cve_bin_tool/cve_scanner.py, cve_bin_tool/cvedb.py, cve_bin_tool/version_signature.py, setup.cfg, test/test_cvedb.py
fix: improve bandit config #3830
**Checklist:**
1. remove B608 from our skips list - ✅
2. run bandit with the new config file - ✅
3. Review any findings and mark reviewed findings with # nosec as needed (should just be a couple of SQL statements probably all in cvedb.py) - ✅
4. Spelling correction done in line-92 bandit.conf file. ✅
**Regarding the TASK 3:** (Findings of BANDIT in cvedb.py file)
**Line 256** - The table name is directly interpolated into the SQL query string, which can lead to SQL injection if the table name comes from an untrusted source. 
Severity: Medium
Confidence: Low
**CURRENT CODE:**
255        cursor = self.db_open_and_get_cursor()
256        schema_check = f"SELECT * FROM {table_name} WHERE 1=0"
257        result = cursor.execute(schema_check)
**PROPOSED …
=> fix: improve bandit config #3830

cve_bin_tool/cli.py, cve_bin_tool/config_generator.py
The ConfigGenerator class contains the config_generator method. Currently config_generator isn't decorated as a class or static method and the signature doesn't contain 'self'. This has the potential to create issues in the future if an instance of the ConfigGenerator class is instantiated or the method requires access to class attributes.
This commit refactors the ConfigGenerator class into a function named config_generator. A standalone function was chosen over a method decorator as the ConfigGenerator class maintained no state and contained a single method. This change removes the potential issues highlighted above and simplifies the code structure to meet current requirements.
fixes: #3941
=> refactor: convert ConfigGenerator class to config_generator function

cve_bin_tool/output_engine/util.py
If network is unavailable, `make_http_requests` will return `None` so it must be checked before calling `jsonResponse["total_items"]`
=> fix: handle None for make_http_requests

cve_bin_tool/parsers/swift.py
Related: #3771.
Instead of vendor, domain is used as namespace for swift PURLs.
=> feat: added PURL generation for swift parser

cve_bin_tool/parsers/java.py
Part of #3771 Step-1.
The regular expression used for normalizing `version` is not the standard one we would use for Maven. Instead, I modified it a bit so that it includes also includes some specific characters like `1.0-SNAPSHOT`.
However, I think we would still need to adjust some more edge cases as we work more with PURLs in the future.
=> feat: added PURL generation to JavaParser

cve_bin_tool/parsers/perl.py
=> feat: added PURL generation to PerlParser

cve_bin_tool/output_engine/__init__.py
add fix in init.py for output_engine to prevent unknown vendor overwrite when sbom is generated for packages with same version and name
=> feat: add fix to prevent unknown vendor overwrite

.github/workflows/testing.yml, cve_bin_tool/extractor.py
I have been unable to find a sufficently good safe tar workaround on windows when python < 3.12, so I'm disabling support.
- windows users will get an error message asking them to install python 3.12 if they try to extract a tarfile
- Since most of our tests use tar files, there is no point in running tests on windows on older versions of python.  I have changed windows_longtests to use python 3.12 and have disabled testing on other versions of python
- effectively this means we only support windows users using python 3.12 going forwards, although we aren't going to stop users from trying to use it.  If you're not scanning tarfiles, things will probably still work, we just don't have a way to test reliably.
I don't like this solution, but I haven't been able to find a better workaround. …
=> fix: windows needs python3.12 for tarfile support

cve_bin_tool/checkers/python.py
Version patterns in python checker right now does not match with a pattern such as `python3.11-3.11.x` so added special character `+` to allow for that.
=> feat: update regex in python checker to match python3.11-3.11.x pattern

cve_bin_tool/sbom_manager/__init__.py, test/sbom/cyclonedx_bad_cpe22.json, test/sbom/cyclonedx_bad_purl.json, test/test_sbom.py
fixes: #4013
- the cpe22 specification regex is too much flexble so in order to test bad cpe22 test data is tweaked.
- validation is refactored to happen in one function
References:
[cpe2.3 and cpe2.3 schema](https://csrc.nist.gov/schema/cpe/2.3/cpe-naming_2.3.xsd)
=> fix: cpe validation and standardize tests data

cve_bin_tool/cvedb.py
=> refactor: database schema code

cve_bin_tool/checkers/python.py
Fixes this issue: https://github.com/intel/cve-bin-tool/issues/4003
The current tool is not able to detect python3.11 on a python3 DLL file due to the fact that its version pattern does not match any existing pattern in `checkers/python.py`. I added `r"tags/v([23]+\.[0-9]+\.[0-9]+)\r?\nversion_info"` as a version pattern since this is the unique way that the DLL displays the python version.
=> feat: add fix to allow detection of python3.11 on DLL file

cve_bin_tool/parsers/r.py
=> feat: added PURL generation for r parser

cve_bin_tool/version.py
Setting a dev version number of 3.3.1dev0 just to help people distinguish git main from the released version before we diverge too much in behaviour.
=> chore: set dev version number

cve_bin_tool/sbom_manager/__init__.py
=> fix: improved cpe parsing in sbom code

.github/dependabot.yml
This changes our dependabot scan frequency to weekly insead of daily in order to limit the amount of "noise" generated by daily automated PRs. We could consider switching to monthly if weekly isn't enough reduction.
I've also removed the /doc section in hopes of eliminating the duplicate PRs we get on doc requirements.
=> ci: reduce dependabot scan frequency

cve_bin_tool/checkers/ppp.py
samba:ppp is also a valid CPE ID:
https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:samba:ppp
=> fix: add additional ppp CPE ID

.github/workflows/testing.yml
GitHub recently made generating and uploading SLSA evidence easier!
Related: https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
Attestations: https://github.com/intel/cve-bin-tool/attestations/
=> feat: upload slsa to github on testing ci build job

.github/workflows/testing.yml
This updates the Testing workflow (testing.yml) using recommendations from Step Security's harden-runner action. Recommendations were taken from the most recent Testing workflow run (6232, see links below) where all jobs ran with only the 'Get Yesterday's cached database if today's is not available' step not running on relevant jobs.
As harden-runner only runs on Ubuntu VMs, a job-level permission was added to the 'Windows long test' job to account for the removal of the top-level workflow permission.
As the Build job has only recently been added, the `egress-policy` key has been left with the value `audit`. The harden-runner recommendations suggest changing the value to `block` after 10+ runs of the job.
@terriko your input on the following would be appreciated:
- Should I remove the …
=> ci: update Testing workflow with harden-runner recommendations

requirements.txt
Dependabot is reporting that requests has a session handling bug that could impact security and should be updated to version 2.32.0 or later.
=> chore(deps): requests>=2.32.0 due to session bug

cve_bin_tool/output_engine/__init__.py, test/test_output_engine.py
=> test: added test for generate_sbom function

.github/workflows/build-wheel.yml, .github/workflows/testing.yml
Mostly fixes for openssf scorecard, which doens't like it if there's no explicitly defined top permission.
Put in a small tweak that may solve #4137 as well, I haven't tested it extensively.
=> ci: openSSF scorecard fixes, fix build-wheel

cve_bin_tool/parsers/__init__.py, cve_bin_tool/parsers/dart.py, cve_bin_tool/parsers/go.py, cve_bin_tool/parsers/java.py, cve_bin_tool/parsers/javascript.py, cve_bin_tool/parsers/perl.py, cve_bin_tool/parsers/php.py, cve_bin_tool/parsers/python.py, cve_bin_tool/parsers/r.py, cve_bin_tool/parsers/ruby.py, cve_bin_tool/parsers/rust.py, cve_bin_tool/parsers/swift.py
Version information isn't particularly useful for queries on the purl2cpe.
=> feat: removed version info from purls in language parsers

cve_bin_tool/checkers/dnsmasq.py
Update dnsmasq pattern to catch version in 'exotic' dnsmasq binary
=> fix: update dnsmasq checker

cve_bin_tool/data_sources/epss_source.py
Thanks to @alext-w for finding this one.
Needed to add trust_env=True to the aiohttp connections in the epss data source because otherwise it ignores proxy settings (and thus won't work at all for users behind a proxy)
* fixes #4083
=> fix: let epss work behind proxy

README.md, cve_bin_tool/cli.py, cve_bin_tool/data_sources/nvd_source.py, doc/MANUAL.md, test/test_cli.py
Adding a disabled source test for #4125, and also made it possible to disable the nvd_api_key to make it easier to avoid nvd2 api calls
=> fix: disable nvd_api_key, test disabled sources

cve_bin_tool/vex_manager/__init__.py, cve_bin_tool/vex_manager/generate.py, requirements.csv, requirements.txt, test/test_vex.py, test/vex/test_cyclonedx_vex.json
cc @anthonyharrison @terriko 
Initial VEXGenerate class for generation using Lib4vex
=> feat: cyclonedx vex generation

cve_bin_tool/data_sources/osv_source.py, test/test_source_osv.py
OSV database sometimes as entries such has https://osv.dev/vulnerability/PYSEC-2020-209 with no severity field but an alias to an other OSV entry which has one: https://osv.dev/vulnerability/CVE-2020-14365
Since its addition in commit 09417a2632a2d17b8ad6d93e71aa785648f914f1, cve-bin-tool will create an entry for CVE-2020-14635 but this entry will not contain any score which is obviously wrong so drop this alias mechanism.
Moreover, this alias mechanism combined with the fact that OSV updated many "old" entries (such as https://osv.dev/vulnerability/CVE-2017-1000099 updated in May 2024) raises the following issue with libcurl 7.54.1 with 19 `UNKNOWN` CVEs:
```
╭─────────────────╮
│  NewFound CVEs  │
╰─────────────────╯
┏━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━ …
```
=> fix: remove alias mechanism from osv

cve_bin_tool/parsers/__init__.py, cve_bin_tool/parsers/dart.py, cve_bin_tool/parsers/go.py, cve_bin_tool/parsers/java.py, cve_bin_tool/parsers/javascript.py, cve_bin_tool/parsers/perl.py, cve_bin_tool/parsers/php.py, cve_bin_tool/parsers/python.py, cve_bin_tool/parsers/r.py, cve_bin_tool/parsers/ruby.py, cve_bin_tool/parsers/rust.py, cve_bin_tool/parsers/swift.py, test/language_data/fail_pom.xml, test/test_language_scanner.py
Changed all the language parsers according to the purl2cpe database and made the database query universal for all parsers.
=> refactor: changed language parsers and query

cve_bin_tool/parsers/__init__.py, cve_bin_tool/parsers/java.py, cve_bin_tool/parsers/python.py, test/test_language_scanner.py
This was probably my bad during code review, but we were using placeholder filenames in the parsers instead of just using the filename which was part of the class.
This may break some tests but my database is updating locally so I'm uploading this as a draft to take advantage of the cache while I wait.
=> fix: use real filenames in language parsers

cve_bin_tool/cli.py, cve_bin_tool/cvedb.py, cve_bin_tool/version_scanner.py
`get_vendor_product_pairs` function doesn't handle disabled sources passed by the user. As a result, the user can't disable a datasource (e.g., OSV) when parsing a python `PKG-INFO` file.
Fix this by passing `enabled_sources` from cli to version_scanner and then to cvedb. To achieve this functionality, `source_nvd` must also be added to `enabled_sources` when appropriate.
nosec must be added to disable this bandit warning:
```
>> Issue: [B608:hardcoded_sql_expressions] Possible SQL injection vector through string-based query construction.
Severity: Medium   Confidence: Low
CWE: CWE-89 (https://cwe.mitre.org/data/definitions/89.html)
Location: cve_bin_tool/cvedb.py:681:12
More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b608_hardcoded_sql_expressions.html
```
Indeed, `sources` is …
=> fix: handle disabled_sources in get_vendor_product_pairs

cve_bin_tool/cvedb.py, cve_bin_tool/parsers/__init__.py, cve_bin_tool/parsers/python.py, test/language_data/FAIL-PKG-INFO, test/test_language_scanner.py
I've disabled the test_language_package_none_found test for `FAIL-PKG-INFO` because it didn't really make any sense. And python-parser for `PKG-INFO` or `metadata` was constructed solely to bypass this test which too didn't make any sense.
Also, adding the table in our existing database (`cve.db`) makes me wonder if I should add the purl2cpe table into it too.
Let me know what you think @terriko @anthonyharrison
=> feat: added deduplication database table

cve_bin_tool/cli.py, cve_bin_tool/cvedb.py, cve_bin_tool/data_sources/epss_source.py, cve_bin_tool/data_sources/nvd_source.py
This will make it so that `-d EPSS` will actually disable the EPSS data source, and should make it fail more gracefully when the source is not working for any reason.
Note that the EPSS source may not be working correctly even when not disabled; I'll file a separate issue.
* fixes #4083
=> fix: make EPSS behave like other data sources

triage.json
removed plotly data field for fixing error with https://github.com/intel/cve-bin-tool/pull/4160
cc @terriko
=> chore: remove plotly from triage.json

test/test_mismatch_loader.py
added test to check loader's functionality.
=> test: mismatch_loader

data/pypi/zstandard/mismatch_relations.yml
Here, I've added the vendor mismatch information for python's zstandard under `pypi` namespace.
Should be merged after #4236.
=> feat: added mismatch information for python's zstandard

cve_bin_tool/parsers/__init__.py, cve_bin_tool/sbom_manager/parse.py, cve_bin_tool/util.py
=> refactor: decode_cpe23

test/test_source_purl2cpe.py
=> test: purl2cpe database

dev-requirements.txt, requirements.csv, requirements.txt
fixes #4282 
* Moved `setuptools>=65.5.1` from `dev-requirements.txt` to `requirements.txt`
* Modified comment as `not directly required` is untrue
* Added a line for setuptools to requirements.csv based on best guess for vendor entry looking at adjacent packages in PyPI
=> build(deps): Move setuptools to requirements.txt (from dev reqs)

cve_bin_tool/mismatch_loader.py, mismatch/cli.py, setup.py
- mismatch -> this command will run the loader and load the default database with default data.
- mismatch loader [--dir] [--database] -> same as previous but with ability to define custom data directory and database file.
- mismatch lookup PURL [--database] -> takes PURL as an argument and returns vendor names associated from database and error if nothing is found.
default values for --dir and --database is tailored for cve-bin-tool, but I think if we were to make it truly standalone, we should make those flags compulsory.
cc @terriko
=> feat: convert mismatch utility into a standalone entity

.github/workflows/testing.yml, test/test_scanner.py
Our short tests are currently not much shorter than our long tests. Since we've seldom seen only one version of python have a problem with a checker, I'm experimenting to see if running the many MANY mapping tests only in the long_tests jobs will help us reduce the time it takes for short tests to run.
I've also added some pytest insrumentation so we can see which of our tests take the longest to run so that we can hopefully find other places to reduce our usage footprint.
* fixes #4315
=> test: Reduce tests run in short tests jobs

cve_bin_tool/cvedb.py
In the course of some other refactoring in cvedb.py, we've got another way to handle schema valiation such that bandit won't complain.
* fixes #3933
* closes #3965
=> fix: improve schema validation for bandit

doc/requirements.csv, doc/requirements.txt, requirements.csv, requirements.txt
Snyk recommended bumping a few minimum versions to avoid vulnerabilities.
This replaces the following couple of issues because I didn't think it was worth running tests twice for the different files:
* closes #4296
* closes #4295
=> chore(deps): bump min versions per snyk

cve_bin_tool/output_engine/__init__.py
* partially addresses #4326
This doesn't add regression tests, but it should at least get you a blank report.
=> fix: 0 cve pdf report was not generating

.github/workflows/cve_scan.yml
Our csv-based CVE scan (i.e. the old scan) is failing slightly sporadically since we switched github runners.  I'm intending to get rid of it eventually (see #4294 ) but haven't done the work yet, and I don't have the time to figure out how to do that or fix it right now.
Since we have multiple cve scans going (cve-bin-tool action, snyk, dependabot, etc.) it's "safe" to disable this one so it's not getting in the way while we figure out the best solution, so this PR should make this so it only runs manually and will no longer run on pull requests and pushes to main.
=> ci: disable csv cve scan temporarily

.github/actions/spelling/allow.txt, doc/mismatch_cli.md, mismatch/cli.py
Closes: #4323 
cc @terriko @anthonyharrison @mastersans
=> docs: mismatch cli utility

test/test_scanner.py
* fixes #3923 (well, maybe)
This is a quick test to see if the snapd and libsrtp tests work on windows since we upgraded the version of python used on windows.  Previously they were both failing.
=> ci: re-enable windows tests that previously failed

.github/actions/spelling/allow.txt, .github/workflows/spelling.yml, cve_bin_tool/cli.py, doc/MANUAL.md
- Adds log info messages about the mirrors
- Updates the manual to include more explanation of the mirror option
- Fix some logic around when we display a message about the nvd_api_key
- Switch so having an nvd_api_key doesn't automatically switch you to api2 (this turned out to be surprising in cases of people trying out the mirror)
- fixes #4037
=> fix: Help users learn about the mirrors

requirements.txt
Set packaging minimum version to 22.0 to avoid the following error with setuptools 71.x:
```
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```
Likelihood of encountering this error increased since commit e4239bd3b838b1717e295412113030ee42631fc6 which bumped minimum version of setuptools from 65.5.1 to 70.0.0
More information:
- https://github.com/pypa/setuptools/issues/4483
- https://github.com/pypa/setuptools/issues/4501
=> fix: set packaging minimum version

cve_bin_tool/cli.py, cve_bin_tool/error_handler.py, test/test_cli.py
* Related to #4326
If pdf output is selected but isn't available, then cve-bin-tool tells you to install reportlab, but it was easy to miss that message as the scan continued and pushed it off the screen.  This changes those messages to be errors insead of info messages, and exits without doing a scan if pdf is the only output mode selected.
=> fix: halt if pdf selected but unavailable

cve_bin_tool/version.py
Decided that now that we're down to mostly test/diocs issues left, it was fair game to call this a release candidate rather than an alpha or a beta.
=> chore: bump version to 3.4rc0 for pre-release

test/test_cli.py
Adds a regression test for 0-cve pdf report behaviour.  This should help us avoid bugs that cause the report to fail in the case where 0 cves were found.
This is the last piece needed to close #4326.  Other pieces:
* #4329 fixed the check that was causing report generaiton to fail.
* #4354 changed the UI so it's more obvious when reportlab is needed.
* fixes #4326
=> test: regression test for 0 cve pdf report

test/test_csv2cve.py, test/test_exploits.py, test/test_language_scanner.py
* replaces #4353
* partial fix for #4243
Re-enables the tests that are now passing consistently, fixes expectations for zstandard vendor.
=> test: re-enable some disabled tests

cve_bin_tool/cvedb.py
This message was firing so frequently that it was making it difficult to debug another issue.  As it didn't seem useful I've removed it rather than commenting it out.  We can always add it back in later if it's needed for future debug work.
=> fix: remove excessively noisy cvedb debug message

cve_bin_tool/data_sources/nvd_source.py
* fixes #4370
Turns out our cvss score loading code was out of date and thus wasn't loading scores correctly and was throwing off a lot of log messages.
=> fix: modernize cvss score loading

requirements.txt
To match the test update in #4403
=> chore: min version of lib4vex to 0.2.0

cve_bin_tool/cli.py, cve_bin_tool/output_engine/__init__.py, cve_bin_tool/sbom_manager/parse.py, cve_bin_tool/util.py, cve_bin_tool/vex_manager/generate.py, cve_bin_tool/vex_manager/parse.py
- Enabled auto detection for vex 
- Added linkage check of cyclonedx vex and sbom using bom-link.
cc @anthonyharrison @terriko
=> feat: auto detect for vex and added linkage check

test/test_scanner.py
Replace colon and backslash in `filename` to avoid a failure on Windows in `condensed_filepath` function as already done in `test_version_mapping` function
Fix #4401
=> fix: handle : in filenames better

cve_bin_tool/cli.py, cve_bin_tool/error_handler.py
* related to #4417
This adds a little bit of backwards compatibility for vex triage
* If --triage-input-file is used, display deprecation warning and convert to --vex-file" so scan can continue.
* If file extension in .vex, the first time, make a copy and scan anyhow.  On subsequent times, print an error asking the user to use --vex-file <new file name>
It might be more elegant to edit lib4vex to handle .vex filenames more seamlessly there, but I feel like "give people one chance and then error" is probably more likely to help people switch to the new arguments so we don't have to support the old ones forever and won't break as many CI jobs.
=> fix: Backwards compatibility for vex triage

cve_bin_tool/vex_manager/parse.py, test/test_vex.py
* related to #4417 
We're getting a "comment" field from lib4vex and then trying to parse a "comments" one.  this is an experiment to see if any of our tests breaks if I "fix" it.  (it is not, incidentally, fixing the full issue in 4417)
=> fix: improve comment propagation from lib4vex

cve_bin_tool/checkers/glibc.py
Drop wrong patterns to avoid the following false positive with the following lines of `/usr/lib/python3/dist-packages/psutil-5.9.8.dist-info/METADATA`:
```
>>> p.memory_maps()
[pmmap_grouped(path='/lib/x8664-linux-gnu/libutil-2.15.so', rss=32768, size=2125824, pss=32768, shared_clean=0, shared_dirty=0, private_clean=20480, private_dirty=12288, referenced=32768, anonymous=12288, swap=0),
pmmap_grouped(path='/lib/x8664-linux-gnu/libc-2.15.so', rss=3821568, size=3842048, pss=3821568, shared_clean=0, shared_dirty=0, private_clean=0, private_dirty=3821568, referenced=3575808, anonymous=3821568, swap=0),
pmmap_grouped(path='[heap]',  rss=32768, size=139264, pss=32768, shared_clean=0, shared_dirty=0, private_clean=0, private_dirty=32768, referenced=32768, anonymous=32768, swap=0), …
```
=> fix: fix glibc patterns

cve_bin_tool/output_engine/__init__.py
=> fix: handle unset serial number

cve_bin_tool/vex_manager/parse.py, test/test_vex.py
* workaround for #4439
I decided it was probably better to retain the 3.3 behaviour for now; we can decide if that's the right choice for future releases later.
=> fix: prepend justification to comments

README.md, doc/MANUAL.md
fixes: #4393
Updated the arguments list in both MANUAL.md and README.md
=> docs: update argument list

cve_bin_tool/cli.py
fixes #4455 
This PR updates the CLI arguments description changed in #4443 in the [cli.py](https://github.com/intel/cve-bin-tool/blob/main/cve_bin_tool/cli.py) file.
@terriko
=> fix: match cli arguments description

.github/actions/spelling/allow.txt, doc/RELEASE.md
Fixes #4458. I removed the GitHub changelogs and any references to them, since the notes for the previous releases don't include them. I also added a brief release note for release 3.4rc3 which didn't have one. Please let me know if you'd like anything changed.
=> docs: add missing release notes to RELEASE.md

.github/scorecard.yml
OpenSSF scorecard currently complains about our binary files.  This adds an annotation explaining what's in them and why we have them in case anyone's curious.
=> chore: annotate testing binaries (OSSF scorecard)

.github/workflows/fuzzing.yml
**Issue:**
In bash, when you use `((` for arithmetic evaluation, numbers with leading zeros are interpreted as octal numbers. Since '9' isn't a valid octal digit, you get the error: value too great for base (error token is "09").
**Fix:**
This PR updates the script to force decimal interpretation of the week number using 10# in the arithmetic expression:
`at_index=$(((10#$(date -u +%U)) % ${#fuzzing_scripts[@]}))`
As you can see now, the correct script is being selected for week 9. I've also tested running fuzzing script on my fork in GitHub Actions.
https://github.com/its403/cve-bin-tool/actions/runs/13652954835/job/38165491473
=> fix: week error in fuzzing scripts

cve_bin_tool/output_engine/html_reports/templates/base.html
- Improved footer wording
- Implemented minor accessibility features to the footer buttons
- Replaced the GitHub link (previously linked to new issue), to link to the GitHub repository
Not sure if this is a fix or a feature due to adding accessibility so I'll let maintainers decide 😅 
New:
Old:
=> feat: improve wording and accessibility in HTML report template

test/README.md
Edited the test README to improve flow and formatting
=> docs: improve test README

test/language_data/invalid-package-lock.json, test/test_language_scanner.py
Add test for invalid package-lock.json handling. As mentioned in #4787, I was planning to take this on during the Intel hackathon, but forgot to submit this in time.  
Please let me know if you'd like this handled in a different way, e.g. commit to the other PR's fork, help the other contributor get their PR merged, close this for someone else to work on, etc.
fixes: #3932
=> test: add invalid package to test language scanner

mismatch_data/pypi/tabulate/mismatch_relations.yml
CVE-2024-13223 is for a WordPress plugin by vendor `samwilson`, but it was incorrectly matched to the Python package `tabulate` due to name similarity.
This mismatch entry excludes the invalid vendor `samwilson` for `pkg:pypi/tabulate` to prevent a false positive.
Fixes: #5082
=> fix(mismatch): ignore CVE-2024-13223 for tabulate
